### DISCUSSION TITLE
unit fahrenheit convert

### DISCUSSION THREAD

**Discussion by skyw33** [echavet/MitsubishiCN105ESPHome#104] [General]
I'm trying to convert to fahrenheit. This [thread](https://gist.github.com/kmdm/29f740e5f36036fb23daba8f2109c359) attempts to do so by changing:

```
      current_temperature_template: "{{ value_json.roomTemperature }}"
      temperature_state_template: "{{ value_json.temperature }}"
```
in the climate section of swicago implementation, but those keys do not exist for this implementation. Any suggestions for using Fahrenheit?

**Comment by phidauex** [comment]
I'm a Fahrenheit user myself. I did not bother to try to convert within the unit, since ultimately the comms between the indoor unit and the ESP will be in Celcius, and the HomeAssistant climate entity will convert automatically depending on your unit settings for HomeAssistant.

That means my ESP's web interface shows C:
<img width="844" alt="image" src="https://github.com/echavet/MitsubishiCN105ESPHome/assets/49047/5c85d5c2-8629-42ed-9670-d7c5d9023979">

But my HA shows F (using the simple-thermostat HACS card here):
<img width="400" alt="image" src="https://github.com/echavet/MitsubishiCN105ESPHome/assets/49047/2d032bdc-da3d-4570-8ac6-f6aa99964e9c">

The only wrinkle is when sending external temps, the unit expects to receive the input service value in C. I convert inside the unit, so my automations stay simpler:

```yaml
# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
  services:
    - service: set_remote_temperature
      variables:
        temperature: float
      then:
# Select between the C version and the F version
# Uncomment just ONE of the below lines. The top receives the temperature value in C,
# the bottom receives the value in F, converting to C here.
        - lambda: 'id(hp).set_remote_temperature(temperature);'
#        - lambda: 'id(hp).set_remote_temperature((temperature - 32.0) * (5.0 / 9.0));'
    - service: use_internal_temperature
      then:
        - lambda: 'id(hp).set_remote_temperature(0);'
 ```
This lambda function receives the remote temperature from the HA service call, converts it to F, and then sends it to the indoor unit.

Does this help?
