### DISCUSSION TITLE
Internally set temp not matching external temperature sensor

### DISCUSSION THREAD

**Discussion by Quarks-1** [echavet/MitsubishiCN105ESPHome#114] [Q&A]
I'm using the sensor implementation to set the current temperature on my HVAC, but the temperature being displayed as 'current' is often a bit off or dated compared to the actual
![image](https://github.com/echavet/MitsubishiCN105ESPHome/assets/67989420/4112cec7-9eb9-4058-94a8-e2132bc96bb5)
![image](https://github.com/echavet/MitsubishiCN105ESPHome/assets/67989420/52558edd-000d-4bc5-b255-4503e9820eb7)
Below is the YAML of the portion dealing with sensors and the climate component
```# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: ${name} Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${name} WiFi Signal
    update_interval: 120s
  
  - platform: homeassistant
    id: current_temp
    entity_id: sensor.living_room_temperature_sensor_temperature
    internal: true
    on_value:
      then:
        - lambda: |-
            id(hp).set_remote_temperature((x - 32.0) * (5.0 / 9.0));

# Create a button to restart the unit from HomeAssistant. Rarely needed, but can be handy.
button:
  - platform: restart
    name: "Restart ${friendly_name}"

climate:
  - platform: cn105
    id: hp
    name: "${friendly_name}"
    icon: mdi:heat-pump
    visual:
      min_temperature: 16
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
    compressor_frequency_sensor:
      name: ${name} Compressor Frequency
    vertical_vane_select:
      name: ${name} Vertical Vane
    horizontal_vane_select:
      name: ${name} Horizontal Vane
    isee_sensor:
      name: ${name} ISEE Sensor
    remote_temperature_timeout: 30min
    debounce_delay : 500ms
    update_interval: 4s```

Any idea what could be done to fix this?

**Comment by Quarks-1** [comment]
I have also tried using the api with this automation
```alias: Set Basement Remote Temp
description: ""
trigger:
  - platform: state
    entity_id: sensor.basement_temp_sensor_temperature
condition: []
action:
  - service: esphome.basement_ac_set_remote_temperature
    data:
      temperature: "{{ states('sensor.basement_temp_sensor_temperature') | float }}"
mode: single
```
and this service in the esp32 yaml
```

# Enable Home Assistant API
api:
  services:
    - service: set_remote_temperature
      variables:
        temperature: float
      then:
# Select between the C version and the F version
# Uncomment just ONE of the below lines. The top receives the temperature value in C,
# the bottom receives the value in F, converting to C here.
        # - lambda: 'id(hp).set_remote_temperature(temperature);'
       - lambda: 'id(hp).set_remote_temperature((temperature - 32.0) * (5.0 / 9.0));'
    - service: use_internal_temperature
      then:
        - lambda: 'id(hp).set_remote_temperature(0);'
```
But it still doesn't update when the automation is fired.  Any ideas?
