### DISCUSSION TITLE
Working Examples

### DISCUSSION THREAD

**Discussion by akifbayram** [echavet/MitsubishiCN105ESPHome#129] [Show and tell]
ESP32-WROOM

```
substitutions:
  name: heatpump-family
  friendly_name: Family Heatpump
  
esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf   

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO1
  rx_pin: GPIO3

logger:
  level: INFO

ota:
  password: "x"
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

web_server:
  port: 80

api:
  encryption:
    key: "x"
  services:
    - service: set_remote_temperature
      variables:
        temperature: float
      then:
# Select between the C version and the F version
# Uncomment just ONE of the below lines. The top receives the temperature value in C,
# the bottom receives the value in F, converting to C here.
        - lambda: 'id(hp).set_remote_temperature(temperature);'
#        - lambda: 'id(hp).set_remote_temperature((temperature - 32.0) * (5.0 / 9.0));'
    - service: use_internal_temperature
      then:
        - lambda: 'id(hp).set_remote_temperature(0);'

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

climate:
  - platform: cn105
    id: hp
    name: "${friendly_name}"
    icon: mdi:heat-pump
    visual:
      min_temperature: 15
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
    vertical_vane_select:
      name: ${name} Vertical Vane
    remote_temperature_timeout: 30min
    debounce_delay : 500ms
    update_interval: 4s
```

**Comment by akifbayram** [comment]
Adafruit Feather Huzzah ESP8266

```
substitutions:
  name: heatpump-bedroom
  friendly_name: Bedroom Heatpump
  
esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: huzzah

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO1
  rx_pin: GPIO3

# Enable logging
logger:
  baud_rate: 0

ota:
  password: "x"
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

web_server:
  port: 80

api:
  encryption:
    key: "x"
  services:
    - service: set_remote_temperature
      variables:
        temperature: float
      then:
# Select between the C version and the F version
# Uncomment just ONE of the below lines. The top receives the temperature value in C,
# the bottom receives the value in F, converting to C here.
        - lambda: 'id(hp).set_remote_temperature(temperature);'
#        - lambda: 'id(hp).set_remote_temperature((temperature - 32.0) * (5.0 / 9.0));'
    - service: use_internal_temperature
      then:
        - lambda: 'id(hp).set_remote_temperature(0);'

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

climate:
  - platform: cn105
    id: hp
    name: "${friendly_name}"
    icon: mdi:heat-pump
    visual:
      min_temperature: 15
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
    vertical_vane_select:
      name: ${name} Vertical Vane
    remote_temperature_timeout: 30min
    debounce_delay : 500ms
    update_interval: 4s
 ```

**Comment by akifbayram** [comment]
ESP8266 Wemos D1 Mini

```
substitutions:
  name: heatpump-master
  friendly_name: Master Heatpump
  
esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: d1_mini

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO1
  rx_pin: GPIO3

logger:
  baud_rate: 0

ota:
  password: "x"
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 
captive_portal:

web_server:
  port: 80

api:
  encryption:
    key: "x"
  services:
    - service: set_remote_temperature
      variables:
        temperature: float
      then:
# Select between the C version and the F version
# Uncomment just ONE of the below lines. The top receives the temperature value in C,
# the bottom receives the value in F, converting to C here.
        - lambda: 'id(hp).set_remote_temperature(temperature);'
#        - lambda: 'id(hp).set_remote_temperature((temperature - 32.0) * (5.0 / 9.0));'
    - service: use_internal_temperature
      then:
        - lambda: 'id(hp).set_remote_temperature(0);'

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

climate:
  - platform: cn105
    id: hp
    name: "${friendly_name}"
    icon: mdi:heat-pump
    visual:
      min_temperature: 15
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
    vertical_vane_select:
      name: ${name} Vertical Vane
    remote_temperature_timeout: 30min
    debounce_delay : 500ms
    update_interval: 4s
```

**Comment by klim123123** [comment]
WT32-ETH01 by Wireless-Tag, board with ethernet.

```
esphome:
  name: wt32-eth01
  friendly_name: Koridor AC wt32-eth01

esp32:
  board: wt32-eth01  

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

# Enable logging
logger:
  level: INFO
  
# Enable Home Assistant API
api:

ota:
 - platform: esphome
   password: "x"

web_server:
  port: 80
  
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

uart:
  id: HP_UART
  baud_rate: 9600
  tx_pin: GPIO2
  rx_pin: GPIO4

climate:
  - platform: cn105
    name: "Koridor AC Mitsu"
    update_interval: 2s
    supports:
      mode: [COOL, HEAT]
      fan_mode: [AUTO, LOW, MEDIUM, MIDDLE]
      swing_mode: []


```
