### DISCUSSION TITLE
Config working on ESP32 but not on Wemos D1 Mini

### DISCUSSION THREAD

**Discussion by aimoehi** [echavet/MitsubishiCN105ESPHome#137] [General]
Hi everyone,

first of all great project! did work the first time on my MVZ-LN Unit - but only on a ESP32 i had lying around.
Now i want to get the second unit connected but only having a Wemos D1 Mini V4.0.0 (with 4mb) - but this thing just wont connect and talk serial with it ;)

Config
```
substitutions:
  name: aircon1
  friendly_name: Aircon1

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

esp8266:
  board: d1_mini
  

# Enable logging
logger:
  hardware_uart: UART1 # This line can be removed for ESP32 devices
  #baud_rate: 0
  level: DEBUG

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: 1
  rx_pin: 3

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
#improv_serial:

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

wifi:
  # Set up a wifi access point  
  ap: {}
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Optional manual IP
  manual_ip:
    static_ip: ---
    gateway: ---
    subnet: ---

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
#esp32_improv:
#  authorizer: none

# To have a "next url" for improv serial
web_server:

# Sensors with general information.
sensor:
  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${name} WiFi Signal
    update_interval: 120s

# Create a button to restart the unit from HomeAssistant. Rarely needed, but can be handy.
button:
  - platform: restart
    name: "Restart ${friendly_name}"

# External component reference
external_components:
  - source: "github://echavet/MitsubishiCN105ESPHome"
    refresh: 0s

# Climate entity configuration
climate:
  - platform: cn105
    id: hp
    name: "Aircon1"
    update_interval: 4s        # update interval can be ajusted after a first run and logs monitoring*     
    debounce_delay : 500ms
```

this is the log: (with debug) - never getting any information. Also tried swapping RX and TX, adding 10k pullup - no changes.
interesstingly, the error changes from three times "NOT CONNECTED" to "We think Heatpump is not connected anymore.."
21:04:56 | [E] | [CN105:032] | --> Heatpump did not reply: NOT CONNECTED <--
-- | -- | -- | --
21:04:56 | [I] | [CN105:033] | Trying to connect again...
21:04:56 | [D] | [CN105:018] | Envoi du packet de connexion...
21:04:56 | [D] | [CN105:084] | writing packet...
21:04:56 | [D] | [WRITE:157] | FC 5A 01 30 02 CA 01 A8
21:05:06 | [E] | [CN105:032] | --> Heatpump did not reply: NOT CONNECTED <--
21:05:06 | [I] | [CN105:033] | Trying to connect again...
21:05:06 | [D] | [CN105:018] | Envoi du packet de connexion...
21:05:06 | [D] | [CN105:084] | writing packet...
21:05:06 | [D] | [WRITE:157] | FC 5A 01 30 02 CA 01 A8
21:05:16 | [E] | [CN105:032] | --> Heatpump did not reply: NOT CONNECTED <--
21:05:16 | [I] | [CN105:033] | Trying to connect again...
21:05:16 | [D] | [CN105:018] | Envoi du packet de connexion...
21:05:16 | [D] | [CN105:084] | writing packet...
21:05:16 | [D] | [WRITE:157] | FC 5A 01 30 02 CA 01 A8
21:05:26 | [W] | [CN105:159] | Heatpump has not replied for 40 s
21:05:26 | [I] | [CN105:160] | We think Heatpump is not connected anymore..
21:05:26 | [D] | [CN105:139] | reconnectUART()
21:05:26 | [D] | [CN105:128] | disconnectUART()
21:05:26 | [D] | [climate:396] | 'Aircon Schlafzimmer' - Sending state:
21:05:26 | [D] | [climate:399] | Mode: OFF
21:05:26 | [D] | [climate:401] | Action: OFF
21:05:26 | [D] | [climate:404] | Fan Mode: OFF
21:05:26 | [D] | [climate:416] | Swing Mode: OFF
21:05:26 | [D] | [climate:419] | Current Temperature: nan°C
21:05:26 | [D] | [climate:425] | Target Temperature: nan°C
21:05:26 | [I] | [CN105:095] | setupUART() with baudrate 2400
21:05:27 | [D] | [CN105:106] | UART est configuré en SERIAL_8E1
21:05:27 | [D] | [CN105:018] | Envoi du packet de connexion...
21:05:27 | [D] | [CN105:084] | writing packet...
21:05:27 | [D] | [WRITE:157] | FC 5A 01 30 02 CA 01 A8
21:05:27 | [W] | [component:237] | Component esphome.coroutine took a long time for an operation (66 ms).
21:05:27 | [W] | [component:238] | Components should block for at most 30 ms.

thanks for any help!
