### DISCUSSION TITLE
Heatpump not connecting with esp32 wroom

### DISCUSSION THREAD

**Discussion by ofer8** [echavet/MitsubishiCN105ESPHome#144] [Q&A] [answered]
Hi,
I've been trying to get this going but the log keep showing that the heat pump is not replying.
my config:
```
esp32:
  board: esp32dev
  framework:
    type: esp-idf
# External component reference
external_components:
  - source: github://echavet/MitsubishiCN105ESPHome
uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO17
  rx_pin: GPIO16

# Climate entity configuration
climate:
  - platform: cn105
    id: hp
    name: "My Heat Pump"
    update_interval: 4s        # update interval can be ajusted after a first run and logs monitoring* 

# Default logging level
logger:
  level: INFO
```
  
i'm using the airzone CN105 splitter to keep using my aidoo controller as well for the time being, not sure if that is the culprit.
I have tried different framework types, different esp devices (esp32-s3, esp8622) and nothing works for me. 
Any advice?

**Comment by tmchow** [comment]
Which board are you using?

**Reply by echavet** [reply]
I'm using an old esp32 wroom on one of my unit with this config: 
Perhaps the logger baud_rate ?

```Yaml
  logger:
    baud_rate: 0
  ...

  ...
  esp32:
    board : esp32doit-devkit-v1
  ...

  uart:
    id: HP_UART
    baud_rate: 2400
    tx_pin: GPI017
    rx_pin: GPI016
```
