### DISCUSSION TITLE
Remote Temperature Behavior

### DISCUSSION THREAD

**Discussion by githoss** [echavet/MitsubishiCN105ESPHome#159] [Q&A]
(First, thanks @echavet and collaborators for all your work on this!)

I have this running in 6 FS head units, each reading temp off a remote sensor. I'm not using api calls, instead listing each in the `Sensor` section of the config. E.g.:

```
sensor:
  # Remote temperature sensor.
  - platform: homeassistant
    id: current_temp
    entity_id: sensor.jill_puck_temperature
    internal: true
    on_value:
      then:
        - lambda: |-
            id(hp).set_remote_temperature((x - 32.0) * (5.0 / 9.0));
```

Was just hoping to get some general clarification on how the remote temp updates work:

1. If I turn on a unit using the manual remote (not via ESPHome), will the head still reference the remote temp sensor's reading for Current Temp?
2. If the remote temp sensor times out and ESPHome falls back to the internal temp sensor, if the remote temp sensor comes back online and updates state, will ESPHome switch back to the remote temp?
3. Just curious if there's a way to see in the logs at any given moment, if Current Temp is based on the internal or remote sensor.

I'm a novice, so sorry if any of this is easy to see in the code or logs. Appreciate the help!

**Comment by phidauex** [comment]
You can try this larger sensor entry - it converts F to C in the filter, does some range checking and throttling, and prints to the log (as long as your logger is set to at least `INFO`) when it receives a value. It will also show up in the webUI if you have that enabled, which can be used for troubleshooting.

```yaml
# Creates the sensor used to receive the remote temperature from Home Assistant
# Uses sensor selected in substitutions area at top of config
# Customize the filters to your application:
#   Uncomment the first line to convert F to C when remote temps are sent
#   If you have a fast or noisy sensor, consider some of the other filter
#   options such as throttle_average.
sensor:
  - platform: homeassistant
    name: "Remote Temperature Sensor"
    entity_id: ${remote_temp_sensor}
    internal: false
    disabled_by_default: true
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"
    filters:
    # Uncomment this line to convert F to C on incoming temperature
      - lambda: return (x - 32) * (5.0/9.0);
      - clamp: # Limits values to range accepted by Mitsubishi units
          min_value: 1
          max_value: 40
          ignore_out_of_range: true
      - throttle: 30s
    on_value:
      then:
        - logger.log:
            level: INFO
            format: "Remote temperature received from HA: %.1f C"
            args: [ 'x' ]
        - lambda: 'id(hp).set_remote_temperature(x);'
```   

To your questions:

1. If you turn a unit ON with the remote, then it should continue to use the remote temperature value it last received (confirmed on my units). If your unit is different and the remote overrides the remote temperature, then it may switch back to internal, but then would switch back to remote again on the next sensor update.
2. Yes, if the remote sensor times out, and the units reverts to internal, then on the next update from the remote temp sensor it will switch back to remote temp.
3. See above to add to logs
