### DISCUSSION TITLE
Control fan not show in web

### DISCUSSION THREAD

**Discussion by oscarsan1** [echavet/MitsubishiCN105ESPHome#160] [Q&A]
![imagen](https://github.com/user-attachments/assets/e5a42ea5-0549-4356-820d-f7adfcaad6d4)

With Mitsubishi HP, the fan control doesn't appear on the web page.
Mode and vane appear correctly.

How can i control the fan from de web?

climate:
  - platform: cn105
    id: hp
    name: "${friendly_name}"
    icon: mdi:heat-pump
    visual:
      min_temperature: 15
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
    compressor_frequency_sensor:
      name: ${name} Compressor Frequency

    supports:
      mode: [COOL, HEAT, FAN_ONLY, DRY]
      fan_mode: [AUTO, QUIET, LOW, HIGH]

**Comment by thecem** [comment]
use web 3 not 2 is more HA like

**Reply by oscarsan1** [reply]
What is Web 3? how can i use web 3?. I don't use HA, I use MQTT.

**Reply by thecem** [reply]
Thought you use ESHome: https://esphome.io/components/web_server.html

**Reply by oscarsan1** [reply]
Thanks, version 3 looks better.

web_server:
  port: 80
  version: 3



But the problem persist, no way to control fan. 

![imagen](https://github.com/user-attachments/assets/9a8f7b8d-3395-4fca-b180-3efdf8496f21)

climate:
  - platform: cn105
    id: hp
    name: "${friendly_name}"
    icon: mdi:heat-pump
    visual:
      min_temperature: 15
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
    compressor_frequency_sensor:
      name: ${name} Compressor Frequency

    supports:
      mode: [COOL, HEAT, FAN_ONLY, DRY]
      fan_mode: [AUTO, QUIET, LOW, HIGH]
      swing_mode: ["OFF", VERTICAL]

    vertical_vane_select:
      name: ${name} Vertical Vane

**Reply by thecem** [reply]
is missing:

    horizontal_vane_select:
      name: Horizontal Vane
    isee_sensor:
      name: ISEE Sensor

**Reply by oscarsan1** [reply]
Yes, not compatible with my HP.
Also vertical Vane is not compatible but I maintain it only for show in the picture.

**Reply by thecem** [reply]
seem to be not implemented in web server 3 try  with webserver 1:
https://github.com/esphome/esphome/pull/7476

**Reply by oscarsan1** [reply]
Thanks. 
I've tried whith de developement brach of ESPHome but it doesn't work for me. 
I've wait for the development.

**Comment by echavet** [comment]
Hello, 
I have tested chatGPT creativity on your request and it seems to be proposing an interessant idea:
I didn't test this. But it looks like chatGPT is manually adding a fan attribute which is bound to the climate fan one. Maybe it's a lead... 

```yaml
fan:
  - platform: template
    id: fan_climatiseur
    name: "Ventilation Climatiseur"
    speed_count: 4
    on_speed_set:
      then:
        - if:
            condition:
              lambda: 'return x == 0;'
            then:
              - climate.control:
                  id: climate_climatiseur
                  fan_mode: "Auto"
        - if:
            condition:
              lambda: 'return x == 1;'
            then:
              - climate.control:
                  id: climate_climatiseur
                  fan_mode: "Low"
        - if:
            condition:
              lambda: 'return x == 2;'
            then:
              - climate.control:
                  id: climate_climatiseur
                  fan_mode: "Medium"
        - if:
            condition:
              lambda: 'return x == 3;'
            then:
              - climate.control:
                  id: climate_climatiseur
                  fan_mode: "High"

```
