### DISCUSSION TITLE
Unable to get external temperature sensor working

### DISCUSSION THREAD

**Discussion by tmchow** [echavet/MitsubishiCN105ESPHome#169] [Q&A] [answered]
I have the standard setup working with an ESP01 board, but want to get the _external temperature sensor_ working as my mini split is using the internal temp from the unit itself and it does not represent the room temp.

I have a working Aqara zigbee sensor exposed as `sensor.ruby_room_temperature` that I can see in Home Assistant.  However, when I've followed the directions to use that sensor with this integration, it's not working. It's showing 32F all the time.

Here's my relevant parts of my YAML config for ESPhome for this particular device:

```
esphome:
  name: ruby-room-climate-controller
  friendly_name: Ruby Room Climate Controller

api:
  encryption:
    key: <my_key_here>
  services:
    - service: set_remote_temperature
      variables:
        temperature: float
      then:
# Select between the C version and the F version
# Uncomment just ONE of the below lines. The top receives the temperature value in C,
# the bottom receives the value in F, converting to C here.
        - lambda: 'id(ruby_room_climate).set_remote_temperature(temperature);'
#        - lambda: 'id(ruby_room_climate).set_remote_temperature((temperature - 32.0) * (5.0 / 9.0));'
    - service: use_internal_temperature
      then:
        - lambda: 'id(ruby_room_climate).set_remote_temperature(0);'
```

then later in the file:

```
climate:
  - platform: cn105
    id: ruby_room_climate
    name: "${friendly_name}"
    update_interval: 2s
    icon: mdi:heat-pump
    visual:
      min_temperature: 15
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
    debounce_delay: 500ms
```

and

```
sensor:
  # Uptime sensor.
  - platform: uptime
    name: ${name} Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${name} WiFi Signal
    update_interval: 120s

  - platform: homeassistant
    id: current_temp
    entity_id: sensor.ruby_room_temperature
    internal: true
    on_value:
      then:
        - lambda: |-
            id(ruby_room_climate).set_remote_temperature(x);
```

This is a screenshot of the sensor from HA:

<img src="https://github.com/user-attachments/assets/3c19c36d-0f5f-406d-ad9a-5f3adc1dbd54" width="350">

I also tried commenting the F vs C lines in the `api` section as I thought maybe I was sending the wrong value for the temperature unit, but that didn't change anything. What am I doing wrong? I must be missing something basic.

**Comment by disruptivepatternmaterial** [comment]
You are almost there :) 

here is my code...works on all 9 of my units...

```
api:
  id: ha_api
  services:
    - service: set_remote_temperature
      variables:
        temperature: float
      then:
        - lambda: 'id(splitunit).set_remote_temperature(temperature);'

    - service: use_internal_temperature
      then:
        - lambda: 'id(splitunit).set_remote_temperature(0);'
  encryption:
    key: !secret api_key_1
  reboot_timeout: 2min

climate:
  - platform: cn105
    name: ${friendly_name}
    id: splitunit
    update_interval: 2s
    compressor_frequency_sensor:
      name: Compressor Frequency
    vertical_vane_select:
      name: Vertical Vane Orientation
    remote_temperature_timeout: 30min  
    debounce_delay : 500ms
    stage_sensor:
      name: Stage Sensor
    sub_mode_sensor:
      name: Sub Mode Sensor     
    auto_sub_mode_sensor:
      name: Auto Sub Mode Sensor
      
sensor:
  - platform: homeassistant
    name: Remote Temperature
    id: room_temperature
    entity_id: ${remote_temp_sensor}
    on_value:
      then:
        #- lambda: 'id(splitunit).set_remote_temperature(x);'
        - lambda: 'id(splitunit).set_remote_temperature((x-32.0) * 5.0/9.0);'
  ```

**Reply by tmchow** [reply]
@disruptivepatternmaterial I'm not seeing what the meaningful difference is between our setups....sorry if i'm missing it.

**Reply by disruptivepatternmaterial** [reply, marked as answer]
Convert the temp in the sensor not the api.

**Reply by tmchow** [reply]
@disruptivepatternmaterial oof, i missed that. It's different than the instructions in the readme. Let me give that a try.

**Reply by tmchow** [reply]
YES! That did it! Thanks so much.

<img src="https://github.com/user-attachments/assets/df34440c-a20c-41fb-a848-6db86c2b1eef" width="350">

**Reply by disruptivepatternmaterial** [reply]
no problemo :) I am not sure why it has you doing that in the api section in the example...let me ask @echavet to comment. I never set mine up there way, I so it in the sensor.

**Reply by tmchow** [reply]
I submitted a PR for this to update the README for @echavet to review
https://github.com/echavet/MitsubishiCN105ESPHome/pull/170

**Reply by phidauex** [reply]
Having it in the API is the "old school" way to do it from the earlier versions of the project, the idea was that you'd use an HA automation to call the service and send it a value. The service call "intake" would then do the conversion from F to C if necessary. The thinking at the time was that you might want your automation doing some error handling, because we didn't have an internal timeout yet, so if your sensor became unknown or unavailable, you'd need the automation to call `use_internal_temperature`. I had some other things configured in the automation as well, such as a rate limit, and a check for valid values.

With the timeout implemented, that whole dance might not be necessary. Some benefits of using the HA sensor in ESPHome would be easier config (no HA automation or blueprint necessary), unit conversion could happen there (as you've done), and even a throttle filter or check for valid values could be done.

EDIT:

How about this? Converting in the filter could be seen as a bit more elegant (only have to uncomment one line for F conversion), rather than swap lines. Filter can then provide an out-of-range check. This also provides a complete configuration for the sensor, making it visible in the webui, sending a log update, but remaining disabled in Home Assistant unless you turn it on.

I'd also suggest updating some of the other associated text to describe the sensor strategy (rather than using an automation).

```yaml
# Creates the sensor used to receive the remote temperature from Home Assistant
# Uses sensor selected in substitutions area at top of config
# Customize the filters to your application:
#   Uncomment the first line to convert F to C when remote temps are sent
#   If you have a fast or noisy sensor, consider some of the other filter
#   options such as throttle_average.
sensor:
  - platform: homeassistant
    name: "Remote Temperature Sensor"
    entity_id: ${remote_temp_sensor}
    internal: false
    disabled_by_default: true
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"
    filters:
    # Uncomment this line to convert F to C on incoming temperature
      - lambda: return (x - 32) * (5.0/9.0);
      - clamp: # Limits values to range accepted by Mitsubishi units
          min_value: 1
          max_value: 40
          ignore_out_of_range: true
      - throttle: 30s
    on_value:
      then:
        - logger.log:
            level: INFO
            format: "Remote temperature received from HA: %.1f C"
            args: [ 'x' ]
        - lambda: 'id(hp).set_remote_temperature(x);'
```
