### DISCUSSION TITLE
How to create an automated dehumidifier with HA

### DISCUSSION THREAD

**Discussion by nununo** [echavet/MitsubishiCN105ESPHome#173] [Q&A]
Hello,

I am trying to create an automated humidifier based on a HA automation (actually, a blueprint). It all was going well but then I ran into a problem. Let me explain:

First I created this Blueprint:

```yaml
blueprint:
  name: Automated AC dehumidifier
  description: Control an AC device based on humidity sensor values.
  domain: automation
  input:
    climate_device:
      name: Climate Device
      description: The climate device to control.
      selector:
        entity:
          domain: climate
    humidity_sensor:
      name: Humidity Sensor
      description: Sensor providing the humidity level.
      selector:
        entity:
          domain: sensor
          device_class: humidity
    max_humidity:
      name: Maximum Humidity
      description: If the humidity exceeds this value, the climate device will turn on in DRY mode.
      default: 75
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    min_humidity:
      name: Minimum Humidity
      description: If the humidity goes below this value, the climate device will turn off.
      default: 65
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

trigger:
  - platform: state
    entity_id: !input humidity_sensor

condition: []

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input climate_device
            state: 'off'  # Only turn on if the device is currently off
          - condition: numeric_state
            entity_id: !input humidity_sensor
            above: !input max_humidity
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input climate_device
            data:
              temperature: 16
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_device
            data:
              hvac_mode: dry
          - action: climate.set_fan_mode
            target:
              entity_id: !input climate_device
            data:
              fan_mode: high
      - conditions:
          - condition: state
            entity_id: !input climate_device
            state: 'dry'  # Only turn off if the device is in DRY mode
          - condition: numeric_state
            entity_id: !input humidity_sensor
            below: !input min_humidity
        sequence:
          - service: climate.turn_off
            target:
              entity_id: !input climate_device
mode: single
max_exceeded: silent
```

This takes a climate device, a humidity sensor and a range of humidity values as parameters. Whenever the humidity is above the max allowed value, it turns on the AC in DRY mode at 16ºC with high fan. When the min humidity is reached, it turns the AC off.

Then I create an automation for each AC unit:

```yaml
alias: Desumidificador escritório
description: ""
use_blueprint:
  path: nununo/auto_ac_dehumidifier.yaml
  input:
    climate_device: climate.t4_escritorio_ac
    humidity_sensor: sensor.t4_4quartos_humidity
    max_humidity: 70
    min_humidity: 65
```

Simple. And it was working. Look:
<img width="1654" alt="image" src="https://github.com/user-attachments/assets/3d9fa415-fb23-4067-b1e1-de4159bfa179">

As you can see, it started working on October 13th at 20h. All was going well, when suddenly on October 15th around 19h this happened:
<img width="1662" alt="image" src="https://github.com/user-attachments/assets/aba9320f-a07e-4f13-bd93-8bcdbc1c977d">

Looking at the temperature chart confirmed my suspicions:
<img width="1655" alt="image" src="https://github.com/user-attachments/assets/fbd22feb-37a5-432b-9a6f-e2e3e2f90e34">

Exactly: when the room temperature reached 16ºC, the AC automatically went into IDLE even though it was set to DRY.

We only come here on the weekends but we want to keep the humidity under control to avoid mold and other problems. But the house gets pretty cold in the winter, around 11ºC when no one's here.

So, now, finally, the request for help: given that 16ºC is the minimum that can be set on the device, how can I keep dehumidifying even when the temperature is <16ºC?

Thanks!
