### DISCUSSION TITLE
Ideal installation with the M5Stack NanoC6!

### DISCUSSION THREAD

**Discussion by cortices** [echavet/MitsubishiCN105ESPHome#183] [Ideas]
Wanted to note how extremely easy it was to get this working with the M5Stack NanoC6 and one HY2.0-4P cable from them.

By coincidence the pinout lines up exactly with pins 2-5 of the Mitsubishi CN105, which means all I had to do was trim one tiny bit of plastic off the connector to fit in CN105 leaving pin 1 (12V) empty, and it was ready to go.

----

## Edit 2025-07-28: better instructions and photos

Here are the links to the official M5Stack store for the items i used. You can also find them on AliExpress or other marketplaces.

NanoC6 dev board: https://shop.m5stack.com/products/m5stack-nanoc6-dev-kit
Unbuckled Grove Cable (20cm): https://shop.m5stack.com/products/4pin-buckled-grove-cable?variant=32050917081178

### Before installing
Flash your NanoC6 from ESPHome Web in a Chromium-based browser using the built-in USB-C port serial adapter.
Check that it correctly joins your Wifi network and you can view the logs from ESPHome. They'll be full of errors to begin, as there's no aircon connected yet!

### To install
1. Using flush-cutters or a craft knife, remove the plastic ridge sticking up from the connector body, adjacent to the black wire, circled in red on the photo.
![grove-4pin](https://github.com/user-attachments/assets/07dfa5a4-e958-49e9-8005-a762c03c2825)
2. Plug the Grove cable into the aircon control board with the remaining ridge beside the white wire fitting into the slot in the CN105 connector, closest to the edge of the connector (in my indoor unit, this is physically at the top). Basically, it should fit easily this way, and not fit properly in any other position, if you cut the right ridge.
![IMG_4835](https://github.com/user-attachments/assets/7fda5790-d8ca-498c-bc44-9997a78ca961)
![IMG_4837](https://github.com/user-attachments/assets/94fcbfca-99cb-45e6-b15c-9c6d21032e41)
There's a little gap below the black wire, where the extra 12V pin is left unconnected.
3. Plug your NanoC6 into the other end of the cable, and tuck it away into a slot in the aircon chassis, away from exposed metal. I used this convenient nook on my unit, and some double-sided foam tape to keep it in position.
<img width="1649" height="1424" alt="image" src="https://github.com/user-attachments/assets/a31537ec-b01f-4a5a-a2f6-6d7b8617c41a" />

Also to clarify, one of the reasons I'm recommending the NanoC6 board is it has Zener diodes on the data lines, which protects them from the different operating voltage (5V in aircon vs 3.3V on the ESP32 module). It's a bit of a bodge, but works well enough.

----

My post: https://cathode.church/@s0/113509209574322642
![image](https://github.com/user-attachments/assets/6b8732c9-99ab-4d89-885b-be10b8c2efe2)

My ESPHome yaml:
````yaml
substitutions:
  deviceName: "Study AC"
  deviceId: studyac

packages:
  wifi: !include _wifi.yaml

esphome:
  name: $deviceId
  platformio_options:
    board_build.flash_mode: dio
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"

esp32:
  board: esp32-c6-devkitc-1   # Actually M5Stack NanoC6
  variant: esp32c6
  flash_size: 4MB
  framework:
    version: "5.3.1" 
    platform_version: "6.9.0" 
    type: esp-idf

# Enable logging
logger:
  hardware_uart: uart0


uart:
  id: AC_UART
  baud_rate: 2400
  tx_pin: 1
  rx_pin: 2

# External component reference
external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

# Climate entity configuration
climate:
  - platform: cn105
    id: $deviceId
    name: $deviceName
    uart_id: AC_UART
    update_interval: 3s        # update interval can be adjusted after a first run and logs monitoring 
````

**Comment by elreydetodo** [comment]
I'm planning to make the same mod to my heat pump soon. I'd already bought an [AtomS3 Lite](https://shop.m5stack.com/products/atoms3-lite-esp32s3-dev-kit) to run it, and some cn105 cables on Ali Express I was planning to splice.

Is [this](https://shop.m5stack.com/products/4pin-buckled-grove-cable) the cable you started with? I had trouble figuring out some of their terminology when picking stuff to buy, so didn't end up getting any spare cables. If I understand this better, I think [this](https://shop.m5stack.com/products/grove2dupont-conversion-cable-20cm-5pairs) might be better in my case because the cn105's I bought have female pin heads on the end of them.

For connecting the cn105 connector, where did you get that connector? How do you crimp it? I'm not very familiar with the different types of connectors that exist, where to get them, or how to crimp them. Pointers would be appreciated.

**Reply by cortices** [reply]
Yep, that's the cable. The pin header *will not* work, because CN105's pin pitch is 2mm, so 2.54mm Dupont pins cannot be installed and work (also the pins are too short).

As I described, I didn't buy or crimp any connector. Reread my explanation -- I just clipped one plastic alignment guide off the M5stack cable and inserted it directly into CN105.

**Reply by mc510** [reply]
Doesn't the HY2.0 Grove connector have 2.0mm pitch, and the CN105 2.54mm? Kinda confused about how you were able to get the Grove connector onto the CM105 pins given the pitch mismatch. Does it just force on partway while bending the pins a bit?

**Reply by cortices** [reply]
@mc510 no, it’s a 2mm pitch, as described in my post. At least in all the models I’ve seen.

**Comment by disruptivepatternmaterial** [comment]
I would only use m5 for these things. They JUST WORK, I too use the M5Stack NanoC6 because I have the hope one day to move it off an IP stack to simply my life :) 

I also have programmed the led on these little things to tell me what's happening...they flash a little when they cannot find HA, etc... and in my case I exposed the button to the outside so I can reset them just in case.

**Comment by joslinmk** [comment]
Here are detailed instructions for doing this

https://www.reddit.com/r/heatpumps/s/EhUDaZmBzb

**Reply by cortices** [reply]
I appreciate you have done something similar, but these instructions are for a different process, with a different MCU module, different cables, etc. Please post in your own thread instead to avoid confusion.

**Comment by ams2990** [comment]
I appreciate you sharing this writeup, I was able to replicate the setup without issue.

One question, how did you decide on [`esp32-c6-devkitc-1`](https://docs.platformio.org/en/latest/boards/espressif32/esp32-c6-devkitc-1.html)? It looks like [`esp32-c6-devkitm-1`](https://docs.platformio.org/en/latest/boards/espressif32/esp32-c6-devkitm-1.html) is similar except it has 4MB of RAM, which matches the NanoC6.

**Comment by jimmy-zhening-luo** [comment]
Hi, firstly, which cable did you use? I don't see any [cables sold by M5Stack](https://shop.m5stack.com/pages/search-results-page?q=Cable%20HY2.0-4P) labeled `HY2.0-4P` nor specified as four-pin with 2mm pitch.

Secondly and finally, is this the device you used? [M5Stack NanoC6 Dev Kit](https://shop.m5stack.com/products/m5stack-nanoc6-dev-kit?variant=44674391277825)

Excited to try this out with my MSZ-GL09 units and ESPHome on Home Assistant. Thank you for sharing this great find.

**Reply by cortices** [reply]
it's just their "Grove cable": https://shop.m5stack.com/products/4pin-buckled-grove-cable
HY2.0-4P is just the specification model for the Grove connectors.
And yes, that's exactly the NanoC6 Dev Kit I used. good luck!

**Reply by jimmy-zhening-luo** [reply]
> it's just their "Grove cable": https://shop.m5stack.com/products/4pin-buckled-grove-cable HY2.0-4P is just the specification model for the Grove connectors. And yes, that's exactly the NanoC6 Dev Kit I used. good luck!

@cortices , thank you, that's the one I got! I even sized it to the 20 cm variant based on your photo. Thank you for sharing the YAML in your original post, too.

**Reply by jimmy-zhening-luo** [reply]
I can now use __Apple Home__ to __set temperature `°F`, heating/cooling mode, fan speed,__ and __vane position,__ with __remote temperature sensing,__ on __Mitsubishi `MSZ-GL`__ ductless mini-split heat-pump indoor air conditioning units.

This is all thanks to exactly the following people:

- @cortices
- @DarkDimius
- @jscatena88
- @ams2990
- [u/raytek75](https://www.reddit.com/user/raytek75/)
- _The original gangsters: @SwiCago, @geoffdavis, and @echavet, and finally @chrdavis for exposing the Pacific Northwest to this grand idea._

I am sharing my setup to help others who, like myself, are somewhat technical but have __zero experience__ with any of the things below until recently forced into this by the clown-show __Mitsubishi Comfort__, a feat of engineering in that V2 manages to make the virtually-unusuable V1, _literally_-unusuable and has stolen hundreds of hours of your prime working years!

> [!TIP]
> More keyword salad of dumb technologies: `Thread, Matter, Home Assistant, ESPHome*`

_*ESPHome is awesome actually._

# Environment

## HVAC

### Heat Pump

```
MXZ-3C24NA
```

### Indoor Units

```markdown
- MSZ-GL06NA-U1
- MSZ-GL06NA-U2
- MSZ-GL09NA-U1
```

## Smart Home

### Apple HomeKit

- Apple TV 4K Wi-Fi __+ Ethernet__
- HomePod (2nd generation)
- HomePod mini

### Home Assistant

Raspberry Pi 5

## Network

### Wi-Fi
The controllers connect to __Wi-Fi__ with repeatedly-successful wireless (OTA) updates and failover handling, but I will soon explore using Thread, too.

ESP32 micro-controllers can at best connect via __`Wi-Fi 6`__ to a __2.4 GHz network__ (channels 1 through 14, or channels 1 through 11 in North America).

### Matter
The remote temperature sensors connect to __Matter__ with poor update performance but solid reliability in normal operation.

As an implementation detail, I was able to connect the remote temperature sensors using __`Matter over Thread`.__

#### Matter Controllers

- Apple HomeKit
- Home Assistant

#### Thread border routers

- Apple HomeKit hubs
- ... smart devices that act as Thread border routers (e.g. Eve Energy smart outlets)

# Instructions

## Buy

### Controller
3 × M5Stack NanoC6 ([buy](https://shop.m5stack.com/products/m5stack-nanoc6-dev-kit?variant=44674391277825) | [documentation](https://docs.m5stack.com/en/core/M5NanoC6))

### Circuit
3 × M5Stack 4-pin buckled Grove cable ([buy](https://shop.m5stack.com/products/4pin-buckled-grove-cable?variant=32050917081178))

### _Optional:_ Remote Temperature Sensor

3 × Eve Weather ([buy](https://www.amazon.com/dp/B0D81BVH6P))

## Build

### Control Circuit

1. Plug any end of the 4-pin buckled Grove cable into the M5Stack NanoC6 controller.
1. Examine the other (unplugged) end of the cable, and note the ridges on the exterior housing.
1. On a flat surface, position the cable so the unplugged end is pointing away from your body, and the ridges are facing up towards the ceiling. In this orientation, from your perspective, the black (`Ground`) wire should be the leftmost wire.
1. Examine the unplugged end of the cable, and note the ridge on the left side of the housing, closest to the black wire.
1. CUT ✂️ (❗) that ridge off with a pair of scissors or a utility knife or most things sharp! It does not need to be a perfect cut, a few microns remaining is fine.

> [!IMPORTANT]
> If you have OCD, just give up on this project, you can stop reading now.

### ESPHome Control Software

1. Figure out how to install and use the ESPHome add-on on Home Assistant. ___(Not a trivial task!)___
1. FIgure out how to copy these YAMLs to `~/config/esphome/` on your Home Assistant. ___(Not trivial lol!)___

> [!CAUTION]
> This compiles using ESPHome Builder 2025.7.5.
>
> At time of writing, esp-idf version 5.4.2 has some weird bug that causes newly flashed controllers to never successfully communicate with the heat pump _for __some__ units_ and randomly not others (even of the same model!).
>
> Some folks claim that reverting to esp-idf 5.4.1 fixes the problem, but I had the same problem with 5.4.1. Only reverting all the way back to 5.3.2 fixed the problem for me.
>
> However, at least for me, esp-idf 5.3.2 won't even compile on ESPHome 2025.8.
>
> Since nobody owes anybody any money, I can't guarantee in open-source land that this bug will ever be fixed, nor that new insane bugs won't arise throughout the lifespan of your Mitsubishi heat pump.
>
> Therefore, I can only in good conscience recommend using ESPHome Builder 2025.7.5 with esp-idf 5.3.2 and pio 53.03.13. Hopefully nobody rugpulls any other dependency.
>
> @khenderick has wisely preserved older ESPHome Builder versions [here](https://github.com/khenderick/esphome-legacy-addons) and included instructions for installing it instead of the official ESPHome add-on onto Home Assistant. Good luck everyone!
>
> If ESPHome Builder 2025.7.5 doesn't even work for you, consider going further back to ESPHome Builder 2025.6.3 (with the same esp-idf and pio versions), which some people have reported as working when 2025.7 did not.

#### `secrets.yaml`

```yaml
api_key:
ota_password:
# Tip: create a blank ESPHome controller using the ESPHome add-on web UI, then copy the plaintext api encryption key and ota password from the generated file into secrets.yaml instead. It is fine both functionally and securiticationally to use the same secret values for all your controllers.

wifi_ssid: # your Wi-Fi (2.4 GHz) network name
wifi_password: # your Wi-Fi password

```

#### `.ac.yml`

```yaml
defaults:
  version:
    minimum_esphome_builder: 2025.7.5
    esp: 5.3.2
    arduino: 53.03.13
  control_loop: 1.5s
  denoise_thermostat: 10ms
  remote_temperature: sensor.climate_${zone}_temperature
  remote_temperature_denoise: 10ms
  remote_temperature_heartbeat: 15s
  remote_temperature_timeout: 2h
  timeout_wifi: 5min

esphome:
  name: ac$zone
  friendly_name: ${zone|title} AC
  area: ${zone|title}
  min_version: ${version.minimum_esphome_builder}

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf
    version: ${version.esp}
    platform_version: ${version.arduino}

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: 1
  rx_pin: 2

api: { encryption: { key: !secret api_key } }

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: $timeout_wifi
  power_save_mode: NONE
  fast_connect: true

external_components: [{ source: github://echavet/MitsubishiCN105ESPHome }]

climate:
  - platform: cn105
    id: hp
    name: Climate
    visual:
      min_temperature: 16
      max_temperature: 31
    fahrenheit_compatibility: true
    update_interval: $control_loop
    debounce_delay: $denoise_thermostat
    remote_temperature_timeout: $remote_temperature_timeout
    supports:
      swing_mode:
        - 'OFF'
        - VERTICAL
        # If your unit supports horizontal vane control, uncomment the following two lines:
        # - HORIZONTAL
        # - BOTH
    vertical_vane_select:
      name: Vane
      icon: mdi:format-list-group
    compressor_frequency_sensor: { name: Compressor Frequency }
    stage_sensor:
      name: Stage
      icon: mdi:wind-power
    sub_mode_sensor:
      name: Sub Mode
      icon: mdi:cogs
      entity_category: diagnostic
    auto_sub_mode_sensor:
      name: Sub Mode Auto
      icon: mdi:cog-clockwise
      entity_category: diagnostic

sensor:
  - platform: homeassistant
    entity_id: $remote_temperature
    name: Remote Temperature Reading
    icon: mdi:thermometer-bluetooth
    internal: false
    device_class: temperature
    state_class: measurement
    unit_of_measurement: °C
    filters:
      - throttle: $remote_temperature_denoise
      - heartbeat: $remote_temperature_heartbeat
      - lambda: return (x - 32) * (5.0/9.0);
      - clamp:
          min_value: 1
          max_value: 40
          ignore_out_of_range: true
      - filter_out:
          - nan
          - 0
    on_value:
      then:
        - lambda: id(hp).set_remote_temperature(x);
        - logger.log:
            level: INFO
            args: [x]
            format: 'Remote temperature: %.1f °C'
  - platform: uptime
    name: Uptime
    icon: mdi:timer-play-outline

button:
  - platform: restart
    name: Restart
    icon: mdi:power

time: [{ platform: homeassistant }]

logger: { level: INFO }

```

#### One config per unit _(i.e., zone)_

##### `acguest.yaml`

```yaml
packages:
  - !include
      file: .ac.yml
      vars:
        zone: guest
        remote_temperature: # Home Assistant entity_id of remote temperature sensor for this zone

```

##### `acliving.yaml`

```yaml
packages:
  - !include
      file: .ac.yml
      vars:
        zone: living
        remote_temperature: # Home Assistant entity_id of remote temperature sensor for this zone

```

##### `acmaster.yaml`

```yaml
packages:
  - !include
      file: .ac.yml
      vars:
        zone: master
        remote_temperature: # Home Assistant entity_id of remote temperature sensor for this zone

```

## Install

### _Optional:_ Set up your remote temperature sensors

1. Add your Eve Weather sensors to Apple HomeKit (which now becomes its owner from a Matter of perspective ;)).
1. Try to update them for 2 to 3 days until you finally get them onto firmware version `3.5.0` instead. Crazy that doesn't happen out of the box haha!
1. Figure out how to now also add the Eve Weather sensors to your Home Assistant's Matter controller so that you can expose those sensors (the very ones you named in the YAML above, sorry this is a bit out of order).

### Flash the controller

1. Figure out how to flash the M5Stack NanoC6 controller for each zone's unit with that zone's YAML configuration.
1. Figure out how to verify that the controller is up and running and connected to Wi-Fi, minus being actually connected to the heatpump yet.

### Attach the controller to the indoor unit

1. Tear open your Mitsubishi indoor unit, and find the CN105 connector.
1. Bring your M5Stack NanoC6 controller over here.
1. Realize to your horror that the CN105 connector has 5 pins, but your Grove cable has 4-pins (it's in the name!), and realize what @cortices was talking about wiht all that "Pin 1" nonsense lmao.
1. Consult your Indoor Unit's installer manual's wiring diagram and board layout, and find that it does not contain information that is helpful to you unless you are an electronics afficionado.
1. Take a look at your physical CN105 connector attached to the indoor unit's control board, and note the pinout. Learn to read the pinout.
1. Find that the pinout is actually obstructed and you can't see either end of the pin numbers hahaha.
1. Get a genius idee to go get your actual Mitsubishi wireless adapter that you had plugged in previously (if you did). Awesome you'll just peel back some of the rubber and find where the black wire (which universally means ground!) is.
1. Ohhh hahaha, the crack engineers at Mitsubishi have the following wires in the bundle: purple, green, yellow, orange, and blue! Ahahah that's awesome.
1. Hold up the cable you cut earlier, with the ridge facing up and cable pointing away from your body as before. You can roughly tell how the cable is supposed to fit into the CN105 connector.
1. How did I know to cut the black side earlier btw? Had to do some research to infer that what @cortices's instructions must be to cut the side of the pin closest to the black wire, because that's the ground wire, and to the right of that should be the 5V wire. DO more research to find out that on the CN105 connector, the black wire would be Pin 2, and 5V would be Pin 3, as Pin 1 is the 15V wire.
1. OK logically with the ridge cut above the black wire which is Pin 1, it only fits in this dumb CN105 connector one way, so I should just plug it in with the non-cut ridge closest to the edge of the CN105. Don't try this at home.
1. Plug the M5Stack NanoC6 controller into the CN105 connector.
1. Don't die or destroy your AC Unit.
1. Check out this amazing completion that GitHub Copilot wrote for me:

<img width="1920" height="1128" alt="Screenshot 2025-07-21 171021" src="https://github.com/user-attachments/assets/376f9823-4f4d-41c3-9930-1293ed464f77" />

### Test end-to-end

1. Control the temperature using the web portal for that controller.
1. Control the temperature using the `climate` entity in Home Assitant for that controller.
1. Expose the `climate` entity to Apple HomeKit (figure this out yourself, this is acutally the only easy part of everything that just happened).

#### Fahrenheit enjoyers and Home Assistant peons, read this!

> [!TIP]
> Here's how to get rid of decimals and half-steps in your temperature controls if you're stuck controlling your using the Home Assistant `climate` control.

@ams2990's Fahrenheit fix makes Fahrenheit a lot more usable (usable at all), but there was one final kink to be worked out. I have tired every combination of how to supply the range (including supplying using unit-ful strings like 61°F instead of 16) and how to supply the steps — each combination breaks the HA–ESPHome–CN109 pipeline in a unique way. Sometimes actually preventing the correct half-step Celsius setting. Basically, supplying any values in any unit (or lack thereof, implicitly Celsius) makes your AC behave incorrectly, despite the warning on the label saying everything is purely visual. (I mean, it is, in the sense that my car's gearshift is purely visual, in that it is not).

I have cracked the nut though. Basically:

1. In your ESP device's climate, only configure the range, don't touch the temperature steps.
1. Turn on @ams2990's Fahrenheit fix.
1. Optionally set your debounce to 200ms like I have, it makes more sense than 100ms anyway, it's like when we nerf electric vehicles to make them go slower so our brain doesn't explode -- this big honking AC _should_ take 200ms + rand(update_interval) to spin up a new set point, 100ms is way too fast and makes your brain feel like something tenuous is around the corner, your AC ready to collapse like a stack of Mitsubishi bricks at any moment again after your traumatic 2 summers of Kumo madness.
1. Then, in your configuration.yaml, add a customization for these units (or for entire climate domain if these are your only climate entities):

```yaml
homeassistant:
  customize_domain:
    climate:
      target_temp_step: 1

```

After the above, everything works perfectly and correctly and UI-delightfully for Fahrenheit users (sensible people who agree that a Fahrenheit is obviously a more useful measurement for everyday life than a Decicelcius).

# Congratulations!

You can now control your Mitsubishi heat pump at all!

# Links

- [This hardware setup](https://github.com/echavet/MitsubishiCN105ESPHome/discussions/183)
- [This YAML basically](https://github.com/echavet/MitsubishiCN105ESPHome/discussions/340)
- [This tangentially related useful 101 guide that someone also posted above](https://www.reddit.com/r/heatpumps/comments/19axppy/how_to_configure_a_mitsubishi_heat_pump_with_home/)
- Stuff to buy:
    - [Controller](https://shop.m5stack.com/products/m5stack-nanoc6-dev-kit?variant=44674391277825)
    - [Cable](https://shop.m5stack.com/products/4pin-buckled-grove-cable?variant=32050917081178)
    - [Remote temperature sensor](https://www.amazon.com/dp/B0D81BVH6P)
