### DISCUSSION TITLE
How do I correctly set temperature from HA actions?

### DISCUSSION THREAD

**Discussion by tmchow** [echavet/MitsubishiCN105ESPHome#184] [Q&A] [answered]
My configuration YAML is this relevant section:

```
substitutions:
  name: ruby-room-climate
  friendly_name: Ruby Room Climate
  remote_temp_sensor: sensor.ruby_room_temperature

esphome:
  name: ruby-room-climate-controller
  friendly_name: Ruby Room Climate Controller

- platform: homeassistant
    name: "Remote Temperature Sensor"
    entity_id: ${remote_temp_sensor}
    internal: false
    disabled_by_default: true
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"
    filters:
    # Uncomment this line to convert F to C on incoming temperature
      - lambda: return (x - 32) * (5.0/9.0);
      - clamp: # Limits values to range accepted by Mitsubishi units
          min_value: 1
          max_value: 40
          ignore_out_of_range: true
      - throttle: 30s
    on_value:
      then:
        - logger.log:
            level: INFO
            format: "Remote temperature received from HA: %.1f C"
            args: [ 'x' ]
        - lambda: 'id(ruby_room_climate).set_remote_temperature(x);'
 ```

However, when i call the `set_remote_temperature` action from Home Assistant, if I pass in say `72` (meaning 72F), my device recognizes it as 32F which is wrong.

![Arc 2024-11-19 13 40 56](https://github.com/user-attachments/assets/3cb4df39-5a85-42e5-a554-bfa627884c5f)

Can you tell me how this is supposed to work? I'm working on another automation and trying to figure out how to use `set_remote_temperature`

**Comment by phidauex** [comment]
In this example, you don't need to send the action at all - simply updating the state of `sensor.ruby_room_temperature` in HomeAssistant will send the new value to the ESPHome device, which will run the filters (convert to C, check range, throttle too-fast updates), then send to the heatpump's internal service call.

If you want to force an update, you could use an action to update the sensor value, `homeassistant.update_entity`, but most people wouldn't need to do this - the sensor will push the value on its next natural update.

If you want to expose an action to HA for manual updating (like, from something other than a sensor), then the older-fashioned way to do this would be to put this api section back in. It has a similar convert lambda in it. I used this method along with an automation for over a year, but recently moved to the newer example, with no automation, and it works much better, honestly, with fewer moving parts to maintain.

```yaml
# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
  services:
    - service: set_remote_temperature
      variables:
        temperature: float
      then:
# Select between the C version and the F version
#        - lambda: 'id(hp).set_remote_temperature(temperature);'
        - lambda: 'id(hp).set_remote_temperature((temperature - 32.0) * (5.0 / 9.0));'
    - service: use_internal_temperature
      then:
        - lambda: 'id(hp).set_remote_temperature(0);'
```

**Reply by tmchow** [reply]
Thanks @phidauex . The reason I went down this path is this convo in another discussion where I think I have issue with remote temp sensor not changing values so values are ignored then it triggers a timeout:

Ultimately this other thread has the author creating an automation that every 20 mins ensures that the sensor reading is sent so the timeout of 30 mins never occurs.

https://github.com/echavet/MitsubishiCN105ESPHome/discussions/176#discussioncomment-11286857

Given this which approach do you recommend for the automation to set the temperature manually?

**Comment by phidauex** [comment]
Oh, that's right, didn't recognize the same name. ;) On that topic I think there is something else going on with the underlying hardware or settings, I don't think a workaround like the automation firing manually every 20 minutes should really be needed, though as a short-term workaround I suppose it is fine.

In that case then the api section is what you'd need. For a year and a half or so I had an automation that would trigger on a change in numeric state of the temp sensor OR every 5 minutes. The condition was that the state of the sensor was numeric (not unknown or unavailable). The action was the set_remote_temp action. It worked fine, but required me to maintain 5 automations. The sensor method ends up being cleaner.

**Reply by tmchow** [reply]
> Oh, that's right, didn't recognize the same name. ;) On that topic I think there is something else going on with the underlying hardware or settings, I don't think a workaround like the automation firing manually every 20 minutes should really be needed, though as a short-term workaround I suppose it is fine.
> 
> In that case then the api section is what you'd need. For a year and a half or so I had an automation that would trigger on a change in numeric state of the temp sensor OR every 5 minutes. The condition was that the state of the sensor was numeric (not unknown or unavailable). The action was the set_remote_temp action. It worked fine, but required me to maintain 5 automations. The sensor method ends up being cleaner.

In my config I actually already have the `api` section but I realize i'm not doing a units F/C conversion here like yours.

```
api:
  encryption:
    key: !secret api_key
  services:
    - service: set_remote_temperature
      variables:
        temperature: float
      then:
        - lambda: 'id(ruby_room_climate).set_remote_temperature(temperature);'
    - service: use_internal_temperature
      then:
        - lambda: 'id(ruby_room_climate).set_remote_temperature(0);'
```

I do have this section where I am doing a conversion so tryign to figure out if I need to do the conversion as well in the api section:

```
- platform: homeassistant
    name: "Remote Temperature Sensor"
    entity_id: ${remote_temp_sensor}
    internal: false
    disabled_by_default: true
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"
    filters:
    # Uncomment this line to convert F to C on incoming temperature
      - lambda: return (x - 32) * (5.0/9.0);
      - clamp: # Limits values to range accepted by Mitsubishi units
          min_value: 1
          max_value: 40
          ignore_out_of_range: true
      - throttle: 30s
    on_value:
      then:
        - logger.log:
            level: INFO
            format: "Remote temperature received from HA: %.1f C"
            args: [ 'x' ]
        - lambda: 'id(ruby_room_climate).set_remote_temperature(x);'
```

Also related to your comment about this not being ideal. My understanding from the other thread is that there appears to be a bug that @homegreen discussed here: https://github.com/echavet/MitsubishiCN105ESPHome/discussions/176#discussioncomment-11192031

Specifically:

> The sensor updates when there was no change were being filtered by HA (as is normal HA behavior)
> The ESPHome integration, in the code that handles sending updates to ESPHome devices that register a homeassistant sensor, was also filtering when there was no change (https://github.com/home-assistant/core/blob/e4aaaf10c32e271aeddf5f4f2c68538a3b8ed10b/homeassistant/components/esphome/manager.py#L294-L299).

So unless i'm mistaken, if I just update the sensor value, since the value is the same, don't I still hit the same issue?
