### DISCUSSION TITLE
M5 Stamp S3 Config

### DISCUSSION THREAD

**Discussion by Zackptg5** [echavet/MitsubishiCN105ESPHome#220] [Q&A]
Hi all, I've been trying to get this setup with the m5Stamp s3 which the readme said was tested but I can't find any mention of working configs on here.  I have the MSZ-FS12NA with CP105 header
I have it setup on the 5V side where I set GPIO13 to tx to GPIO 15 to receive
![image](https://github.com/user-attachments/assets/441516d1-1568-49e1-878d-92d01a2d4163)

However it appears to not be connected
```
[11:35:17][E][CN105:032]: --> Heatpump did not reply: NOT CONNECTED <--
[11:35:17][I][CN105:033]: Trying to connect again...
[11:35:27][W][CN105:177]: Heatpump has not replied for 40 s
[11:35:37][I][CN105:178]: We think Heatpump is not connected anymore..
[11:35:37][I][CN105:006]: setupUART() with baudrate  2400 
```

Here's my config:
```
substitutions:
  name: m5stamp-s3-39c4d8
  friendly_name: M5Stamp S3

esphome:
  name: m5stamp-s3-39c4d8
  friendly_name: M5StampS3
  min_version: 2024.11.0
  name_add_mac_suffix: false

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

esp32:
#  board: esp32-s3-devkitc-1
  board: m5stack-stamps3
  framework:
    type: esp-idf

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO13 #black wire
  rx_pin: GPIO15 #red wire

# Climate entity configuration
climate:
  - platform: cn105
    id: hp
    name: "LivingRoom HeatPump"
    update_interval: 4s        # update interval can be adjusted after a first run and logs monitoring 

# Default logging level
logger:
  level: INFO

# Enable Home Assistant API
api: 
  encryption:
    key: ###############################

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

Anything I have setup wrong? Thanks

**Comment by echavet** [comment]
Hello @Zackptg5 

Why did you chose the GPIO13 and 15?
It looks like these are not for the UART. Am I wrong ?
I would have used G43 and G44 as it appears to be for TXD and RXD.

**Reply by Zackptg5** [reply]
Location mainly, the 5v and ground are right in a row with those ports. My understanding was that any gpio port could be used for esp32 devices, is that incorrect?
I also didn't know if there was any difference in the GPIO ports on the 3V vs 5V side

**Reply by Zackptg5** [reply]
Tried moving tx/rx pins to g43 and g44 but with same results

**Reply by Zackptg5** [reply]
@echavet I turned on debug and it appears that a packet gets written and nothing returns. However I'm not sure how to check if the write action was successful:
```
[13:49:55][D][CN105:084]: writing packet...
[13:49:55][D][WRITE:170]: FC 5A 01 30 02 CA 01 A8 
[13:49:59][W][CN105:177]: Heatpump has not replied for 64 s
[13:49:59][I][CN105:178]: We think Heatpump is not connected anymore..
[13:49:59][D][CN105:157]: reconnectUART()
[13:49:59][D][CN105:146]: disconnectUART()
```

**Reply by echavet** [reply]
Yes this means the uart connection is not established.
Well you're right. With ESP32 You can use any gpio thanks to remapping. 
I didn't know it.

**Reply by Zackptg5** [reply]
Update on this, tried a different esp32 board and it's working fine. I did find this: https://community.platformio.org/t/m5dial-no-serial-output-m5stamp-s3-board/37801/3
To see if it was a uart issue related to that but also didn't change anything. Can the stamp be removed as a compatible device from the readme since nobody seems to have it working yet?

**Reply by osmoossi** [reply]
It's an old discussion but StampS3A does work. I used the provided Grove header that plugs into 5V, GND, GPIO13 and GPIO15. I just plugged the Grove cable straight from the AC unit to the MCU header but I'll add a level shifter when it arrives, just to be safe. Your config looks identical except the IO pin names?


The relevant part of my config is:
```
esp32:
  board: m5stack-stamps3
  framework:
    type: esp-idf

uart:
  id: AC_UART
  baud_rate: 2400
  tx_pin: 15
  rx_pin: 13
```
