### DISCUSSION TITLE
Fan CFM mapping

### DISCUSSION THREAD

**Discussion by phidauex** [echavet/MitsubishiCN105ESPHome#228] [Ideas]
I'm working on a little project to map the expected fan CFM value to the STAGE sensor in order to get a reasonable guess of the actual running CFM of a ductless unit. I'm going to capture my notes here to see if anything useful comes of it.

Testing first on an MSZ-GL18NA (pretty common indoor unit), here is the value mapping I'm seeing:

| Remote Setting | Climate Fan Setting | Stage Sensor | CFM |
| -----------        | ------------             | ------------    | ----  |
| "Quiet ears"      | quiet                         | DIFFUSE       | 297? |
| One Bar     | low                         | LOW       | 297? |
| none                 |  low                       | GENTLE       | 385 |
| Two Bars     | medium                         | MEDIUM       | 469 |
| Three Bars      | middle                         | MODERATE       | 565 |
| Four Bars      | high                         | HIGH       | 646 |

Of note here is that GENTLE and LOW seem ambiguous. When running in "auto" fan mode, I see both show up, with GENTLE seeming to be a higher output mode. However, if I use the remote I can only get LOW, and if I use the climate fan_mode of low then I get GENTLE.

The submittal for this unit gives 5 values for heating CFMs, but it isn't clear how they map to the apparently 6 distinct modes my unit will take on. Maybe "DIFFUSE" doesn't count because it can't be used while in heating mode (my unit will let me set "quiet", but will force the fan stage to LOW):
<img width="862" alt="image" src="https://github.com/user-attachments/assets/2eedb990-d419-4a40-bd05-4e77e71bc206" />

This is a mostly-functional lookup table - you have to define `model` in your substitutions, save the yaml below to a file at `esphome/common/fanspeeds.yaml` and add as a package with:

```yaml
packages:
  fanspeeds: !include common/fanspeeds.yaml
```

Fan speed lookups:
```yaml
sensor:
  - platform: template
    id: cfm_lookup
    internal: true
    lambda: |-
      json::parse_json(id(fanspeed_json).state, [](JsonObject root) -> bool {
          if (root[id(model).state]) {
            id(fan_cfm).publish_state(root[id(model).state][id(stage).state]);
            return true;
          }
          else {
            ESP_LOGD(TAG,"Unsupported model - can't return fan CFM");
            return false;
          }
      });
      return 0;
    update_interval: 5s
  - platform: template
    name: "Fan CFM"
    id: fan_cfm
    unit_of_measurement: "ft³/min"
    icon: "mdi:weather-windy"
    device_class: "volume_flow_rate"
    state_class: "measurement"
    accuracy_decimals: 0
    disabled_by_default: true
    filters:
      - delta: 1

text:
  - platform: template
    id: model
    internal: true
    optimistic: true
    mode: text
    initial_value: ${model}
  - platform: template
    id: fanspeed_json
    internal: true
    optimistic: true
    mode: text
    initial_value: >
      {
      "MSZ-GL12NA": {
          "IDLE": 0,
          "DIFFUSE": 145,
          "LOW": 145,
          "GENTLE": 170,
          "MEDIUM": 237,
          "MODERATE": 321,
          "HIGH": 406
      },
      "MSZ-GL15NA": {
          "IDLE": 0,
          "DIFFUSE": 205,
          "LOW": 205,
          "GENTLE": 247,
          "MEDIUM": 304,
          "MODERATE": 367,
          "HIGH": 463
      },
      "MSZ-GL18NA": {
          "IDLE": 0,
          "DIFFUSE": 297,
          "LOW": 297,
          "GENTLE": 385,
          "MEDIUM": 469,
          "MODERATE": 565,
          "HIGH": 646
      }
      }
```

This creates a text sensor with the contents set to a JSON string of models (just the three I own), and their mapping from STAGE to CFM, and a text sensor with your model number. Every 5 seconds, the template looks up the model and CFM value, and updates the Fan CFM sensor. It is filtered with a `delta` filter, meaning that while it is internally updating every 5 seconds, it will only send a value to HA when the value actually changes (more than 1, in this case).

Me playing with my fan speeds to try to figure out what is going on:
<img width="961" alt="image" src="https://github.com/user-attachments/assets/ab223c68-5db7-471e-82fa-e4ad6c457e09" />

Eventual hope would be to make a big JSON with all the common models, and possibly include it directly in this component so your CFMs would be populated if you had a supported model. Right now just playing around with the data.

**Comment by phidauex** [comment]
A little update here, I used an absurdly tiny Xiao ESP32S3 to connect to Dallas DS18B20 waterproof temp sensors, and the hardware UART for CN105. It was a tight fit on the board but fits fine. The board has poor Wifi performance for some reason so I'm hesitating to actually recommend it yet, though I have it working now.

I threaded the sensor cables through the unit so one sits on top of the intake grate, and one is threaded into the middle of the outlet grate. I like these sensors because they respond very quickly, and the smooth waterproof package doesn't easily get gummed up with dust or dirt.

With two intake sensors and my CFM sensor, I can calculate the heating power. I calculate it in kW, and then convert to BTU/hr because I'm a yankee and we just like causing problems.

I'm grabbing air density from my weather station, but picking a local average would be totally reasonable. Do check by altitude however, at sea level density is around 1.22 kg/m^3, but at my 5300ft elevation it is only 1.03 kg/m^3. I'd be 20% off if I used a generic number!

```yaml
sensor:
  - platform: dallas_temp
    address: 0x8b00000003eba528
    name: "Intake Temperature"
    id: intake_temp
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    update_interval: 2s
    filters:
      throttle_average: 6s
  - platform: dallas_temp
    address: 0x8c00000003136528
    name: "Outlet Temperature"
    id: outlet_temp
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    update_interval: 2s
    filters:
      throttle_average: 6s
  - platform: template
    name: "Delta T"
    id: delta_t
    lambda: |-
      // Initialize variables
      // airflow rate in m^3/sec, converted from CFM
      float flow = id(fan_cfm).state * 0.000471947;
      // Specific capacity of air at STC, in kJ/kg*K
      float capacity = 1.005;
      // DeltaT in degrees K
      float delta_t = (id(outlet_temp).state - id(intake_temp).state);
      // Air density in kg/m^3. 1.225 at sea level.
      float density = id(air_density).state;
      float power = 0;
      // Calculate the heating or cooling power, in kW
      power = delta_t * flow * density * capacity;
      // Convert to BTU/hr for yankees
      power = power * 3142;
      // Update the thermal_power sensor and return the deltaT
      id(thermal_power).publish_state(power);
      return delta_t;
    update_interval: 6s
    state_class: "measurement"
  - platform: template
    name: "Thermal Power"
    id: thermal_power
    unit_of_measurement: "BTU/hr"
    state_class: "measurement"
    update_interval: never
    filters:
    - exponential_moving_average:
        alpha: 0.1
        send_every: 4
  - platform: homeassistant
    name: Air Density
    id: air_density
    entity_id: sensor.st_00086672_air_density
    internal: true
```

This gives some useful values:
<img width="1365" alt="image" src="https://github.com/user-attachments/assets/60267fc6-616e-47bf-a064-f4af041e81a0" />

Interesting that intake temperature drops noticeably during call for heat as the fan starts pulling fresher interior air.

<img width="1365" alt="image" src="https://github.com/user-attachments/assets/4dce943b-7102-4da5-8d4c-fd530c4e7b6f" />

Thermal power ranges are pretty realistic based on the max outputs of the unit. Hitting a delta T of 22 to 24 C, which feels good as well though I haven't confirmed the specs.
