### DISCUSSION TITLE
Got A Mitsubishi MSZ-GL-15NA working!

### DISCUSSION THREAD

**Discussion by dandashl1973** [echavet/MitsubishiCN105ESPHome#251] [Show and tell]
The Canadian model, Mitsubishi MSZ-GL-15NA.  With an Atom S3 Lite.  This project Amazing solution!  Thanks to all who built and maintain it.  

Took me a few tries to sort it all out.  Thought I'd post a couple of pitfalls that tripped me up:

-The most important  'modification' when using the Atom S3 Lite is that the GPIO pins are different, 1&2 in this case.  I overlooked that when following other examples.  

-The ESPHome Integration in Home Assistant and the ESPHome Builder are separate things.

-The Base64 passwords for the Home Assistant API and the OTA Update in the yaml file tripped me up.  I kept searching for where I had to make them "match" something.  You don't.  You just generate a unique Base64 password and plunk it into the YAML file.  I assume that the ESPHome Builder & Home Assistant magically figure out both sides of this password exchange when they compile the image for the ESP32 board.  

-Set the OTA Password and make sure it works before permanently installing the Atom in the A/C unit and closing it all back up. :). (Seems obvious after the fact).  

![572459BF-27DC-40B7-9825-91E7D681D636_1_105_c](https://github.com/user-attachments/assets/36cbd808-1e44-4291-8127-53eda7999431)

![092FA1A2-0842-4946-8F0E-E00C1BA40E07_1_105_c](https://github.com/user-attachments/assets/04e3e545-80f3-41e0-8113-44e791dfe5fe)

![A3CC7CB1-B25A-4167-BF14-FCC2593497F8_1_105_c](https://github.com/user-attachments/assets/35c60536-ce71-4568-883e-4cb6c1de01c8)

Here is my yaml file for this AC unit:

```
substitutions:
  name: guest-ac
  friendly_name: Guest House AC

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-s3-devkitc-1
  #board: esp32doit-devkit-v1
  framework:
    #type: arduino
    type: esp-idf
    version: latest

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO1
  rx_pin: GPIO2

# Default logging level
logger:
  level: INFO  

# Enable Home Assistant API
api:
  encryption:
    key: "<Snip>" # needs to be your key

ota:
  platform: esphome
  password: "<Snip>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "GarageMitsubishi"
    password: "<Snip>"

captive_portal:

# Enable Web server.
web_server:
  port: 80

# External component reference
external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

# Climate entity configuration
climate:
  - platform: cn105
    id: hp
    name: ${friendly_name}
    icon: mdi:heat-pump
    visual:
      min_temperature: 15
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
    compressor_frequency_sensor:
        name: ${name} Compressor Frequency
    vertical_vane_select:
      name: ${name} Vertical Vane
    #horizontal_vane_select:
    #  name: ${name} Horizontal Vane
    remote_temperature_timeout: 30min
    debounce_delay : 500ms
    update_interval: 4s
  
# diagnostics
text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP
    ssid:
      name: SSID

  - platform: version
    name: Version
    hide_timestamp: true
    disabled_by_default: false
    icon: mdi:new-box
    entity_category: diagnostic

sensor:
  - platform: uptime
    name: "Uptime"
    disabled_by_default: false
    force_update: false
    unit_of_measurement: s
    icon: mdi:timer-outline
    accuracy_decimals: 0
    device_class: duration
    state_class: total_increasing
    entity_category: diagnostic
    update_interval: 60s

  - platform: internal_temperature
    name: Internal Esp temperature
    entity_category: diagnostic
```
