### DISCUSSION TITLE
Confirmed working: MSZ-AP35VGD2 + M5Stamp Pico

### DISCUSSION THREAD

**Discussion by sjwright** [echavet/MitsubishiCN105ESPHome#254] [General]
The AC head is MSZ-AP35VGD2 as supplied in Australia.

I used the M5Stamp Pico. For this project, I think you couldn't ask for a better microcontroller. You're barely paying any premium for excellent build quality and incredible miniaturisation, good wifi antenna, and it even has the four pins neatly on the short edge. There is no USB interface on the board but the DIY kit includes a USB programmer. I then bought their 5-pack, as I have four ACs to control.

https://shop.m5stack.com/products/m5stamp-pico-diy-kit
https://shop.m5stack.com/products/m5stamp-pico-5pcs

Because the Pico is so small, I was able to encase the whole thing in heat shink for an extremely safe install and tidy appearance, if anyone went poking around. My deployment has been installed and working for over 6 months.

Here's my yaml fragment. 

```
external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

esp32:
  board: pico32

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: 33 #red
  rx_pin: 32 #black

climate:
  - platform: cn105
    name: ${entity_prefix}
    icon: mdi:heat-pump
    visual:
      min_temperature: 15
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
    compressor_frequency_sensor:
      name: ${entity_prefix} Compressor Frequency
    outside_air_temperature_sensor:
      name: ${entity_prefix} Outside Air Temperature
    vertical_vane_select:
      name: ${entity_prefix} Vertical Vane
    horizontal_vane_select:
      name: ${entity_prefix} Horizontal Vane
    remote_temperature_timeout: 30min
    debounce_delay: 500ms
    update_interval: 2s
```

I purchased this pre-made cable in the 5-pin variety and wired it directly to the Pico:
https://www.aliexpress.com/item/1005002904897793.html

My wiring :
- Red —> 33 (TX)
- Black —> 32 (RX)
- Yellow —> 5V
- Green —> GND

But don't assume anything. There's no reason for the wire colours to remain consistent.

**Comment by boc-the-git** [comment]
Thanks for sharing the details @sjwright. I'll probably take the same approach for my MSZ-AP25VGD.
Do you have any progress shots of your build, including the final installation?

**Comment by alanviles** [comment]
For anyone wanting to build, this is what worked for me.

I purchased m5stamp Pico diy kit and pre-made 5-pin cable.

My cable colours were the same as above but you should check and use the pin numbers if they are different.

<table>
<tr> 
 <td> Pin 
 <td> Colour
 <td> CN105 Function
 <td> PICO Pin
<tr>
 <td> 1
 <td> Blue
 <td> +12V
 <td> No Connect
<tr>
 <td> 2
 <td> Green
 <td> Ground
 <td> GND (Ground) (G)
<tr>
 <td> 3
 <td> Yellow
 <td> +5V
 <td> 5V
<tr>
 <td> 4
 <td> Black
 <td> Tx
 <td> 32
<tr>
 <td> 5
 <td> Red
 <td> Rx
 <td> 33
</table>

I soldered the male pins to GND, 5V, 32, 33 and female pins to 3V3, G1, G3, EN, G0, and GND.
When trying to flash with the included USB to serial no LED's lit and there was no voltage across the output pins, so I used a different usb to serial adapter.
 
<img width="2646" height="1257" alt="IMG_5823 2" src="https://github.com/user-attachments/assets/7667ede8-5334-4b73-88d5-ccecc7df2651" />


I connected  the following pins:

<table>
<tr>
 <td> USB to serial PIN
 <td> PICO Pin
<tr>
 <td> GND
 <td> GND
<tr>
 <td> CTS
 <td> No Connect
<tr>
 <td> 5V
 <td> 5V
<tr>
 <td> TXD
 <td> G3 (RXD)
<tr>
 <td> RXD
 <td> G1 (TXD)
<tr>
 <td> DTR
 <td> No Connect
</table>
On the Pico make sure to short G0 to GND to enable boot mode so that you can upload ESP Home binary.

With ESP Home flashed I disconnected the usb to serial adapter and connected the CN105 Cable, removing the plastic pin separator so that the connector DuPont pins could securely connect. Then I covered the Pico in electrical tape (I didn't have large enough heat shrink) and the connector in heat shrink.
<img width="3024" height="4032" alt="IMG_5812 2" src="https://github.com/user-attachments/assets/555d1351-3528-4969-981a-a3b1629864ec" />

<img width="3024" height="4032" alt="IMG_5813 2" src="https://github.com/user-attachments/assets/24250245-5254-4350-82af-c5375ce3ec4f" />

To install I turned off the breaker for the heat pump and removed the front cover of MSZ-AP35VGD2.

<img width="4032" height="3024" alt="IMG_5820" src="https://github.com/user-attachments/assets/42681461-a18f-4369-9b5b-dd043b081c97" />
There are 5 screws to remove with a PH2 bit, the bottom two are covered with a screw cover. DO NOT remove the screw with the red X it contains the mains power and does not need to be removed to access the CN105 connector. 

Once the font plastic cover is removed the control board has a screw securing the cover. After removing the screw the control board cover can be removed by pushing the cover to the right to release a latch and then pulling.
<img width="3024" height="4032" alt="IMG_5817" src="https://github.com/user-attachments/assets/ca1b5fe0-4c27-40d7-813a-6aa00c6b5543" />
The Pico and adapter can be installed:
<img width="3024" height="4032" alt="IMG_5818 2" src="https://github.com/user-attachments/assets/474dc80e-d1d3-4f31-b682-a4031bcda00b" />

I found that it would not connect originally so I removed debug from being sent to the heat pump and the folowing code worked for me 
My YAML:

```yaml
esphome:
  name: heat-pump
  friendly_name: Heat Pump
  
esp32:
  board: pico32
  framework:
    type: esp-idf

logger:
  baud_rate: 0
  level: DEBUG

api:
  encryption:
    key: "***********************************************"

ota:
  - platform: esphome
    password: !secret heat_pump__ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: HP Fallback Hotspot
    password: **********
captive_portal:
  
external_components:
  - source: github://echavet/MitsubishiCN105ESPHome
  
uart:
  id: HP_UART
  baud_rate: 2400
  data_bits: 8
  parity: EVEN
  stop_bits: 1
  tx_pin: 33 #red
  rx_pin: 32 #black
substitutions:
  entity_prefix: Heat Pump
climate:
  - platform: cn105
    name: ${entity_prefix}
    icon: mdi:heat-pump
    visual:
      min_temperature: 15
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
    outside_air_temperature_sensor:
      name: ${entity_prefix} Outside Air Temperature
    vertical_vane_select:
      name: ${entity_prefix} Vertical Vane
    horizontal_vane_select:
      name: ${entity_prefix} Horizontal Vane
    input_power_sensor:
      name: ${entity_prefix} Input Power
      disabled_by_default: true
    kwh_sensor:
      name: ${entity_prefix} Energy
      disabled_by_default: true
    remote_temperature_timeout: 30min
    debounce_delay: 500ms
    update_interval: 2s
```
