### DISCUSSION TITLE
questions regarding the use of an external temperature sensor

### DISCUSSION THREAD

**Discussion by ScottZwettler** [echavet/MitsubishiCN105ESPHome#257] [Q&A] [answered]
Attached is the config, yaml that I am using for my Mitsubishi heat pump.
I'm using a Shelly H&T sensor for external temperature measurement, and am using what I've gleaned is the
recommended approach for updating temperature in the unit.  (The requisite code is in the sensor section and NOT in the api section)

[downstairs-heatpump.txt](https://github.com/user-attachments/files/19391333/downstairs-heatpump.txt)

For my setup I am using Fahrenheit units so I'm a bit confused by a couple of lines in the sensor section.
Should my unit_of_measurement be "°F" instead of "°C"
And should by min_value and max_value be something different than 1 and 40 respectively?

________________
Or, is everything in this config done internally in units of Celsius, but because my Shelly sensor is setup in units of Fahrenheit, 
I do indeed need to uncomment the lambda line to convert F to C on the incoming temperature? 

Also, and most importantly, I don't see the INFO log message of "Remote temperature received from HA: %.1f C"
and the subsequent setting of temperature set point.

Thanks for your help!

**Comment by phidauex** [comment, marked as answer]
This component, and the Mitsubishi unit itself, only speak Celcius, so leave all the internal units of measure as C in your configuration, such as the min and max temp values. Your HA instance will convert it to display in F if your system-wide settings call for that, so you'll see F, even though it is C in the background.

For your remote temperature sensor, the component wants C, so leave the unit of measurement as C, and make sure that the lambda line in the filters section is uncommented, like below:

```yaml
sensor:
  - platform: homeassistant
    name: "Remote Temperature Sensor"
    entity_id: ${remote_temp_sensor}
    internal: false
    disabled_by_default: true
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"
    filters:
    # Uncomment this line to convert F to C on incoming temperature
      - lambda: return (x - 32) * (5.0/9.0);
      - clamp: # Limits values to range accepted by Mitsubishi units
          min_value: 1
          max_value: 40
          ignore_out_of_range: true
      - throttle: 30s
    on_value:
      then:
        - logger.log:
            level: INFO
            format: "Remote temperature received from HA: %.1f C"
            args: [ 'x' ]
        - lambda: 'id(hp).set_remote_temperature(x);'
```

The way you should read the `filters`, from top to bottom is, "when a new value comes in, convert it from F to C, then clamp to a min of 1 and a max of 40, then only change state if it is has been more than 30s from the last value". Then the `on_value` is read as "when a new valid value gets through the filters, then send a log entry and run the set_remote_temperature function to update the heatpump.

Make sure `entity_id` is set to the full HA id of your temperature entity, either in the sensor, or at the top of your configuration under `substitutions`.

EDIT: Glancing at your config, I think the only thing you need to do is uncomment the lambda line in the sensor that does the conversion. I suspect that what is happening now is that your sensor is sending a value in F, like "68", it isn't being converted, so the `clamp` filter rejects it (68C would be an invalid temperature value to send to the heatpump!). Give that a try first.
