### DISCUSSION TITLE
Confirmed to work with the ESP32 ESP32-S3 Development Board

### DISCUSSION THREAD

**Discussion by lrehmann** [echavet/MitsubishiCN105ESPHome#270] [General]
Confirmed to work with the ESP32 ESP32-S3 Development Board, [cheapo from amazon](https://www.amazon.com/gp/product/B0DG8L7MQ9).
somehow accidentally swapped the 12v and ground and didn't end up frying the HVAC unit (esp still turned on!), unsure if the ESP is okay though, started working with a new one after the blunder.  

Connected to pins 15/16 for TX/RX. 

![IMG_0354](https://github.com/user-attachments/assets/07f76f84-fd52-4127-804a-86d688b6c366)

![IMG_3485 2](https://github.com/user-attachments/assets/2e8c1c0e-14dd-49c4-859a-c942cbe9fe64)
![IMG_3483 2](https://github.com/user-attachments/assets/f56bbdd2-79a7-438a-956f-b7d863a21bfc)

Please forgive the wire colors
Black - Unused, 12v
Red - Ground
White - 5v
Orange - Pin 16 - TXD1
Yellow - Pin 15 - RXD1

```
esphome:
  name: basementbedroomhvac
  friendly_name: Basement Bedroom HVAC
  on_boot:
    priority: -100
    then:
      - light.turn_on:
          id: status_led
          red: 100%
          green: 100%
          blue: 0%

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

api:
  encryption:
    key: "xxxxxxx"

ota:
  platform: esphome
  password: "yyyyyyyy"

wifi:
  ssid: "wwwwiiifffiii"
  password: "zzzzzzzz"
  ap:
    ssid: "BasementBedroomHVAC"
    password: "zzzzzzzz"

captive_portal:

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO16
  rx_pin: GPIO15

climate:
  - platform: cn105
    id: hp
    name: "Basement Bedroom HVAC"
    update_interval: 2s
    icon: mdi:heat-pump
    visual:
      min_temperature: 10 # Adjust to your unit's min temp. SmartSet units can go to 10C for heating
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.5
    # Timeout and communication settings
    remote_temperature_timeout: 30min
    debounce_delay : 100ms
    # Various optional sensors, not all sensors are supported by all heatpumps
    compressor_frequency_sensor:
      name: Compressor Frequency
      entity_category: diagnostic
      disabled_by_default: true
    outside_air_temperature_sensor:
      name: Outside Air Temp
      disabled_by_default: true
    vertical_vane_select:
      name: Vertical Vane
      disabled_by_default: false
    horizontal_vane_select:
      name: Horizontal Vane
      disabled_by_default: true
    isee_sensor:
      name: ISEE Sensor
      disabled_by_default: true
    stage_sensor:
      name: Stage
      entity_category: diagnostic
      disabled_by_default: true
    sub_mode_sensor:
      name: Sub Mode
      entity_category: diagnostic
      disabled_by_default: true
    auto_sub_mode_sensor:
      name: Auto Sub Mode
      entity_category: diagnostic
      disabled_by_default: true
    input_power_sensor:
      name: Input Power
      disabled_by_default: true
    kwh_sensor:
      name: Energy Usage
      disabled_by_default: true
    runtime_hours_sensor:
      name: Runtime Hours
      entity_category: diagnostic
      disabled_by_default: true


sensor:
  - platform: uptime
    name: Uptime

output:
  - platform: ledc
    pin: GPIO48
    id: red_led
  - platform: ledc
    pin: GPIO47
    id: green_led
  - platform: ledc
    pin: GPIO21
    id: blue_led

light:
  - platform: rgb
    name: "Status LED"
    red: red_led
    green: green_led
    blue: blue_led
    id: status_led
    default_transition_length: 0s
    

logger:
#  hardware_uart: UART1 # Uncomment on ESP8266 devices
  level: INFO
  logs:
    EVT_SETS : INFO
    WIFI : INFO
    MQTT : INFO
    WRITE_SETTINGS : INFO
    SETTINGS : INFO
    STATUS : INFO
    CN105Climate: WARN
    CN105: INFO
    climate: WARN
    sensor: WARN
    chkSum : INFO
    WRITE : WARN
    READ : WARN
    Header: INFO
    Decoder : INFO
    CONTROL_WANTED_SETTINGS: INFO

```
