### DISCUSSION TITLE
Any working setups with Airzone CN105 and ESP32?

### DISCUSSION THREAD

**Discussion by mgulick** [echavet/MitsubishiCN105ESPHome#273] [Show and tell]
I've been digging through posts over here and on the SwiCago repo to try to figure out which hardware configuration will work best for me.  I have two indoor ducted units (SVZ-KP18NA and SVZ-KP24NA, with a MXZ-SM42NAMHZ outside).  These are relatively new (about 2 years old).  These currently have the WF-2 wifi module and MHK-2 thermostat modules attached.  I need to keep these for a couple of reasons:

1) Since the air handlers are in the attic, I need a physical thermostat with a temperature sensor for each zone
2) I have a PAC-WHS01HC-E in my basement, which talks to the indoor units over wifi and integrates with my baseboard hot water boiler for supplemental/backup heat (which is necessary in the winter where I live)
3) I need to use the Kumo Cloud app to manage the installer settings for backup heat crossover temps, and I also use it to manage the schedule (although I'd like to switch to home assistant scheduling instead if this proves to be reliable)

I've been using the https://github.com/dlarrick/hass-kumo/ integration for 2 years, and as great as it has been, it's not reliable enough that I would trust it for scheduling (the units are very frequently unavailable/unknown in Home Assistant, and often ignore commands to change the set point).

Since I need the WF-2 and MHK-2 modules, I will need an Airzone splitter, and everything I've read says that people have problems getting these to work with ESP32 modules.  I've got a few ESP8266's in HA, but I also find these to be a little unreliable in terms of WiFi, and a little slow/resource limited in terms of ESPHome features.  So I'd really like to use an ESP32.  Has anyone been able to make this work?

A couple of thoughts I had on things I might try:

1) Maybe the unreliability is caused by the fact that the CN105 UART is 5V logic, but the ESP32 is 3.3V.  I was going to try using a level shifter in-between to see if that works.
2) Maybe the unreliability is caused by insufficient power over the 5V rail, so I was considering trying a 12V -> 5V (or 3.3V) buck converter.

I have the Airzone CN105's on order, but I'm trying to figure out what other parts to order to give this a try.  I've been holding off switching over to the Mitsubishi Comfort app because it apparently breaks the hass-kumo integration, which means my thermostats are stuck on my winter schedule until I can figure this out.

**Comment by mgulick** [comment]
I've tried a few different boards in a few different configurations, with mixed results.  For background, I have:
* MXZ-SM42NAMHZ Outdoor Unit
* SVZ-KP18NA Ducted Air Handler
* SVZ-KP24NA Ducted Air Handler
Each air handler has a WF-2 and MHK-2 daisy-chained to the CN105 port.

I also have the PAC-WHS01HC-E Kumo Station in my basement controlling backup heat.

**Bottom Line:** The Airzone CN105 doesn't seem to work at all with the ESP32's 3.3V signaling.  There was no communication whatsoever.  The WF-2 seems a little more tolerant of 3.3V signaling, but could never complete a communication cycle with the ESP32.  The ESP-01 with the 5V adapter, and ESP32 with level shifters both seem to have flawless communication with the heat pump through the Airzone CN105 splitter.

---

# Configurations tried:

## M5Stack Atom S3 Lite (did not work)

My first attempt was the Atom S3 Lite, which only partially worked.  It didn't worked at all when I had it laid out like:

```
Airzone Port 1: Heat Pump
Airzone Port 2: Atom S3 Lite
Airzone Port 3: WF-2 -> MHK2
```
It did partially work when I changed it to:
```
Airzone Port 1: Heat Pump
Airzone Port 2: MHK2
Airzone Port 3: WF-2 -> Atom S3 Lite
```

However the esp32 couldn't fully communicate with the heat pump.  It would never complete all stages of the communication "cycle".  He was an example of the debug logs:
```
[01:21:47][D][CN105:308]: sending a request for settings packet (0x02)
[01:21:47][I][CYCLE:039]: 1: Cycle start
[01:21:47][D][CYCLE:311]: 2a: Sending settings request (0x02)
[01:21:47][D][CN105:323]: creating Info packet
[01:21:47][D][CN105:084]: writing packet...
[01:21:47][D][CYCLE:321]: 2b: Receiving settings response
[01:21:47][D][Decoder:178]: [0x02 is settings]
[01:21:47][D][Decoder:186]: [Power : ON]
[01:21:47][D][Decoder:187]: [iSee  : 0]
[01:21:47][D][Decoder:188]: [Mode  : HEAT]
[01:21:47][D][Decoder:200]: [Temp °C: 17.000000]
[01:21:47][D][Decoder:203]: [Fan: 3]
[01:21:47][D][Decoder:206]: [Vane: AUTO]
[01:21:47][W][lookup:206]: wideVane reading caution: value 0 not found, returning value at index 0
[01:21:47][D][Decoder:211]: [wideVane: ←← (adj:0)]
[01:21:47][D][SETTINGS:105]: [current]-> [power: ON, target °C: 17.0, mode: HEAT, fan: 3, vane: AUTO, wvane: ←←]
[01:21:47][D][SETTINGS:105]: [received]-> [power: ON, target °C: 17.0, mode: HEAT, fan: 3, vane: AUTO, wvane: ←←]
[01:21:47][D][EVT_SETS:062]: [wanted]-> [power: -, target °C: -1.0, mode: -, fan: -, vane: -, wvane: -, hasChanged ? ->  NO, hasBeenSent ? ->  NO]
[01:21:47][D][SETTINGS:089]: [climate]-> [mode: HEAT, target °C: 17.0, fan: MIDDLE, swing: OFF]
[01:21:47][D][CYCLE:324]: 3a: Sending room °C request (0x03)
[01:21:47][D][CN105:323]: creating Info packet
[01:21:47][D][CN105:084]: writing packet...
[01:21:48][D][CYCLE:330]: 3b: Receiving room °C response
[01:21:48][D][Decoder:258]: [Room °C: 22.000000]
[01:21:48][D][Decoder:259]: [OAT  °C: 20.000000]
[01:21:48][I][STATUS:130]: [received]-> [room C°: 22.0, operating: NO , compressor freq: nan Hz]
[01:21:48][I][STATUS:130]: [current]-> [room C°: 22.0, operating: NO , compressor freq: nan Hz]
[01:21:48][D][CN105:218]: setting action to -> 4
[01:21:48][D][CN105:291]: Climate mode is: 3
[01:21:48][D][CN105:292]: Climate action is: 4
[01:21:48][D][CYCLE:333]: 4a: Sending status request (0x06)
[01:21:48][D][CN105:323]: creating Info packet
[01:21:48][D][CN105:084]: writing packet...
[01:22:08][W][CN105:009]: Cycle timeout, reseting cycle...
[01:22:08][I][CYCLE:052]: 6: Cycle ended in 21.0 seconds (with timeout?: YES)
```

This would just repeat forever.  While this did show current temperature, set point, and let me change the temperature, it didn't have the heating/cooling status and wouldn't show the "stages".

## ESP-01 with 5V adapter board

* [ESP-01S board](https://www.amazon.com/dp/B00O34AGSU)
* [5V adapter board](https://www.amazon.com/dp/B09C8CV885)

The ESP-01 with the 5V adapter board worked perfectly.  It was in the configuration:
```
Airzone Port 1: Heat Pump
Airzone Port 2: ESP-01
Airzone Port 3: WF-2 -> MHK-2
```

I did have one problem.  Of my two separate air handlers, one of them worked for about 5 days, but then completely lost communication with the ESP-01 as well as the thermostats.  The Airzone LED were basically steady on, alternating red and green, instead of only briefly flashing on.  [Here's a video](https://imgur.com/a/afrpiBB) (The video doesn't show the ESP-01 because I had disconnected it right before taking the video to see if that fixed it, which it didn't).  I might blame this on a bad connection, as I just had everything dangling in the air by the cables, not secured at all.  I have since made some mounts for everything and re-connected it, and it has been stable for 2 days so far.  The other air handler has been fine with no issues.

## ESP32-S3
* [Seeed Xiao ESP32-S3](https://www.amazon.com/dp/B0DJ6NQFKX)
* [Bidirectional Level Shifters](https://www.amazon.com/HiLetgo-Channels-Converter-Bi-Directional-3-3V-5V/dp/B07F7W91LC)

Since the ESP-01 was successful, I thought it was likely the 3.3V level that was the problem.  I bought a pack of the Seed Xiao ESP32-S3 mini boards.  I already had some bi-directional level shifters.  I soldered up a little board with some pin headers using a sparkfun solderable breadboard, and 3d-printed an enclosure.  I've had this connected for a few days, and it seems to be working.

![PXL_20250511_132620312](https://github.com/user-attachments/assets/8558d123-af81-45d8-b5c4-9b149eaae637)

![Image](https://github.com/user-attachments/assets/8579c10a-e184-4c7d-8670-2643dec743e2)

![test_mitsu_esp32_xiao_5v_bb](https://github.com/user-attachments/assets/600706d6-1153-498a-b3c7-8e01e69b4448)

![Image](https://github.com/user-attachments/assets/b811b9e2-ef70-4931-838a-bc5935a03246)

When prototyping at my desk, I used a USB-FTDI adapter that has selectable 3.3V and 5V levels, so I would flash the ESP32, connect it to the breadboard with the level shifters, and hook up the pins to the USB-FTDI at 5V level.  I could then read /dev/ttyUSB0 at 2400 baud and see if I was getting data transmitted from the adapter.  I could see that data was being received by the USB-FTDI, so I had decent confidence it would work.

# What works and what doesn't

Both the ESP-01 and the ESP32 seem perfectly capable of doing the job.  I didn't notice any issues with WiFi connectivity or performance between the two.  I suppose the more important question is will one survive longer in my attic with 140 degF temps in the summer time.

I haven't played around with this for too long.  What works:
* Climate functionality (temps, mode, fan speed)
* Outside Air Temp
* Stage (I've seen IDLE, LOW, GENTLE, MODERATE)
* Sub Mode (I've seen NORMAL, PREHEAT, STANDBY)
* Auto Sub Mode (this is always AUTO_OFF -- not sure if it will ever change)

What doesn't work:
* Compressor Frequency
* Input Power
* KWH Sensor
* Runtime Hours
* Swing Mode (this is not applicable since I have ducted units, but it shows up in Home Assistant as a toggle that does nothing.  I couldn't find a way to turn it off)
* Fan Speed Mismatch
  * The thermostat has 3 speeds plus auto.  When changing the fan speed on the thermostat, I get
    * Auto: maps to Auto in HA
    * Low: maps to Low in HA
    * Medium: maps to Medium in HA
    * High: maps to Middle in HA
  * Changing the fan speed in home assistant:
    * Auto: maps to auto on thermostat
    * Low: maps to low on thermostat
    * Medium: maps to medium on thermostat
    * High: maps to high on thermostat
    * Middle: maps to high on thermostat
    * Quiet: maps to low on thermostat
  * I keep one of my zones on high fan in the winter, and it is a little odd that this shows up in home assistant as 'Middle'.  Not sure why or what it would take to fix it.  I can get used to it though.

Here is my configuration (for the ESP32-S3):

```yaml
substitutions:
  name: esp32-xiao-s3-mitsuhp-fl1
  friendly_name: ESPHome Xiao S3 HP FL1

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 8MB
  framework:
    type: esp-idf

# Enable Home Assistant API
api:
  encryption:
    key: "abcdefgh"

ota:
  - platform: esphome
    password: "abcdefg"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Xiao-S3-Mitsuhp-Fl2"
    password: "abcdef"

captive_portal:

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Enable Web server.
web_server:
  port: 80

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 120s

# Create a button to restart the unit from HomeAssistant. Rarely needed, but can be handy.
button:
  - platform: restart
    name: "Restart ${friendly_name}"

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO43
  rx_pin: GPIO44

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

# Enable logging
logger:
  hardware_uart: UART1
  level: INFO
  logs:
    EVT_SETS : INFO
    WIFI : INFO
    MQTT : INFO
    WRITE_SETTINGS : INFO
    SETTINGS : INFO
    STATUS : INFO
    CN105Climate: WARN
    CN105: INFO
    climate: WARN
    sensor: WARN
    chkSum : INFO
    WRITE : WARN
    READ : WARN
    Header: INFO
    Decoder : INFO
    CONTROL_WANTED_SETTINGS: INFO
#  level: DEBUG
#  logs:
#    EVT_SETS : DEBUG
#    WIFI : INFO
#    MQTT : INFO
#    WRITE_SETTINGS : DEBUG
#    SETTINGS : DEBUG
#    STATUS : INFO
#    CN105Climate: WARN
#    CN105: DEBUG
#    climate: WARN
#    sensor: WARN
#    chkSum : INFO
#    WRITE : WARN
#    READ : WARN
#    Header: INFO
#    Decoder : DEBUG
#    CONTROL_WANTED_SETTINGS: DEBUG

climate:
  - platform: cn105
    id: hp
    name: "${friendly_name}"
    icon: mdi:heat-pump
    visual:
      min_temperature: 10
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 1
    # Timeout and communication settings
    # remote_temperature_timeout: 30min
    update_interval: 10s
    debounce_delay : 500ms
    # Various optional sensors, not all sensors are supported by all heatpumps
    # Seems not supported
    compressor_frequency_sensor:
      name: ${name} Compressor Frequency
      entity_category: diagnostic
      disabled_by_default: true
    outside_air_temperature_sensor:
      name: Outside Air Temp
      disabled_by_default: false
    # N/A
    vertical_vane_select:
      name: Vertical Vane
      disabled_by_default: true
    # N/A
    horizontal_vane_select:
      name: Horizontal Vane
      disabled_by_default: true
    # N/A
    isee_sensor:
      name: ISEE Sensor
      disabled_by_default: true
    stage_sensor:
      name: Stage
      entity_category: diagnostic
      disabled_by_default: false
    sub_mode_sensor:
      name: Sub Mode
      entity_category: diagnostic
      disabled_by_default: false
    auto_sub_mode_sensor:
      name: Auto Sub Mode
      entity_category: diagnostic
      disabled_by_default: false
    # Seems not supported
    input_power_sensor:
      name: Input Power
      disabled_by_default: true
    # Seems not supported
    kwh_sensor:
      name: Energy Usage
      disabled_by_default: true
    # Seems not supported
    runtime_hours_sensor:
      name: Runtime Hours
      entity_category: diagnostic
      disabled_by_default: true
```

**Reply by cameronr** [reply]
I'm about to give this a shot and would love your latest thoughts after running things for a bit. Would you recommend the ESP32-S3 or ESP-01 for someone starting from scratch?

**Reply by mgulick** [reply]
Yes, I've been using the ESP32-S3 version for a few weeks and I'm still happy with it.  A few updates and observations:

* After seeing the ESP-01 become "unavailable" a few times, I switched both to the ESP32-S3.  I think the external antenna on the Xiao board helps with reception a little bit.

* My thermostats have stopped updating the set-point temperature on their display when I update them through HA/ESPHome.  I also have the home assistant 'hass-kumo' integration, which talks to the WF-2 Wifi adapters, and that shows the updated temperatures/settings, so the new set point is definitely getting set, its just that the display on the thermostats aren't updating for some reason.  Other than pulling the batteries from one of the thermostats, I haven't tried to fix this since I primarily use schedules and not the thermostats directly.  I'm 90% sure they would still work to update the temperature if I manually adjust one of them.
* When switching between heat and cool, it's not clear where the new set-point temperature is coming from.  E.g. if I have the heat set to 65 and switch to cool mode, the new set point may become 65 or 66, which causes the AC to turn on right away.  Also, occasionally when switching modes, e.g. heat to cool, the device will go into cool mode, then a few seconds later switch to fan mode, and then back to cool mode after 5 or 10 seconds.  I'm not sure if this interaction is happening because of a conflict between Kumo Cloud, the physical thermostats, or maybe the auto-standby setting for the two zones.  Again, this fixes itself after a few seconds, so it hasn't really been a big annoyance.  I changed the update interval from 10 seconds to 4 seconds, to see if it might help with this, but I can't really say for sure whether it has made a difference.
* I've had a few instances where the device has become unavailable, or frequently flip-flops the unavailability state, and when I go look at it physically the Airzone CN105 adapter is in a bad state (the lights are red and flashing green every few seconds, instead of being off and flashing red/green on every few seconds).  I can reset it by unplugging the Airzone's CN105 input from the heat pump for a few second and plugging it back in.  This has happened twice, with about a week between occurrences.  Since this only ever happens to one of them, I've bought another Airzone CN105 adapter to try (if/when this occurs again).  However it's now been stable for over a week, so I'm keeping my fingers crossed.
* I added a `supports` section into the YAML configuration, which configures only the supported fan modes (auto, low, medium, high).  Since I'm using 'high' instead of 'middle' (which the thermostat reports when manually setting the fan speed via the thermostat), when I set the fan speed manually via the thermostat (or kumo cloud), the ESPHome's fan speed is unset (I think it shows as unknown, or blank).  Since I have been using ESPHome to set the fan speed, I don't consider this a big deal.  Expand the bottom of this post to see the updated YAML config.
* I've posted the 3D-printed enclosure on Printables: https://www.printables.com/model/1313879-sparkfun-redboard-enclosure-for-esphome-cn105

I've also been using the home assistant scheduler card to set up schedules using home assistant instead of kumo cloud.  Here's a screenshot of the dashboard:
![Screenshot_20250531_131715](https://github.com/user-attachments/assets/69da6ff3-13f5-4f67-a2a6-8c39cad2b71c)
I set up weekday and weekend schedules for both heat and cool (using the 'scheme' method in the scheduler card).  I also made helper entities of type 'Group', one for 'Heat Schedule' and one for 'Cool Schedule', and put the corresponding scheduler entities into each group.  This lets me easily turn on and off the heat schedule and cool schedule.

<details>
  <summary>
Updated YAML
  </summary>

```yaml
substitutions:
  name: esp32-xiao-s3-mitsuhp-fl1
  friendly_name: ESPHome Xiao S3 HP FL1

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 8MB
  framework:
    type: esp-idf

# Enable Home Assistant API
api:
  encryption:
    key: "<KEY>"

ota:
  - platform: esphome
    password: "<PASSWORD>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Xiao-S3-Mitsuhp-Fl1"
    password: "<PASSWORD>"

captive_portal:

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Enable Web server.
web_server:
  port: 80
  version: 3
  # Disable OTA since this is unauthenticated
  ota: false
  local: true

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 120s
  
  - platform: internal_temperature
    name: "Internal Temperature"

# Create a button to restart the unit from HomeAssistant. Rarely needed, but can be handy.
button:
  - platform: restart
    name: "Restart ${friendly_name}"

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO43
  rx_pin: GPIO44

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

# Enable logging
logger:
  hardware_uart: UART1
  level: INFO
  logs:
    EVT_SETS : INFO
    WIFI : INFO
    MQTT : INFO
    WRITE_SETTINGS : INFO
    SETTINGS : INFO
    STATUS : INFO
    CN105Climate: WARN
    CN105: INFO
    climate: WARN
    sensor: WARN
    chkSum : INFO
    WRITE : WARN
    READ : WARN
    Header: INFO
    Decoder : INFO
    CONTROL_WANTED_SETTINGS: INFO
#  level: DEBUG
#  logs:
#    EVT_SETS : DEBUG
#    WIFI : INFO
#    MQTT : INFO
#    WRITE_SETTINGS : DEBUG
#    SETTINGS : DEBUG
#    STATUS : INFO
#    CN105Climate: WARN
#    CN105: DEBUG
#    climate: WARN
#    sensor: WARN
#    chkSum : INFO
#    WRITE : WARN
#    READ : WARN
#    Header: INFO
#    Decoder : DEBUG
#    CONTROL_WANTED_SETTINGS: DEBUG

climate:
  - platform: cn105
    id: hp
    name: "${friendly_name}"
    icon: mdi:heat-pump
    visual:
      min_temperature: 10
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 1
    # Timeout and communication settings
    # remote_temperature_timeout: 30min
    # update interval default is 2s
    # update_interval: 10s
    update_interval: 4s
    # debounce delay default is 100ms
    debounce_delay : 200ms
    # Various optional sensors, not all sensors are supported by all heatpumps
    # Supported:
    outside_air_temperature_sensor:
      name: Outside Air Temp
      disabled_by_default: false
    stage_sensor:
      name: Stage
      entity_category: diagnostic
      disabled_by_default: false
    sub_mode_sensor:
      name: Sub Mode
      entity_category: diagnostic
      disabled_by_default: false
    auto_sub_mode_sensor:
      name: Auto Sub Mode
      entity_category: diagnostic
      disabled_by_default: false
    # Not supported or N/A on SVZ ducted units:
    compressor_frequency_sensor:
      name: ${name} Compressor Frequency
      entity_category: diagnostic
      disabled_by_default: true
    vertical_vane_select:
      name: Vertical Vane
      disabled_by_default: true
    horizontal_vane_select:
      name: Horizontal Vane
      disabled_by_default: true
    isee_sensor:
      name: ISEE Sensor
      disabled_by_default: true
    input_power_sensor:
      name: Input Power
      disabled_by_default: true
    kwh_sensor:
      name: Energy Usage
      disabled_by_default: true
    runtime_hours_sensor:
      name: Runtime Hours
      entity_category: diagnostic
      disabled_by_default: true
    supports:
      # mode: [AUTO, COOL, HEAT, DRY, FAN_ONLY]
      #
      # Note: When the thermostat sets the fan to high, this shows up as
      # 'MIDDLE'.  Since we are excluding 'MIDDLE', when the thermostat sets the
      # fan to high, it will not show up as a known value in home assistant.
      fan_mode: [AUTO, LOW, MEDIUM, HIGH]
      swing_mode: []

```
</details>

**Reply by cameronr** [reply]
Wow, super detailed and very helpful!

Fwiw, I've had the same temperature set point suddenly being low (e.g. 65F) when switching from heat to cool (or even fan to cool) with the hacs-kumo integration.

**Comment by ChrisLanks** [comment]
I have also gotten this too work. I have two esp8266s. I had to cut the trace for the Rx to the resistor to get data to work. I have 3 wall msg-gl06na units and 1 PEAD attic until.  using the esp8266 with no level converter works. Once I introduce that one to the airzone, it fails. I took the another and added the level converter, and jumped the 5v. It works with the airzone! 

This is my setup:
```
Airzone port 1: CN105 from minisplit
Airzone port 2: esp8266 with no level converter (fails)
Airzone port 3: esp8266 with lever converter works!
```
Tomorrow I am going to try to get in my attic to have this set up: 
```
Airzone port 1: CN105 from minisplit
Airzone port 2: esp8266 with level converter
Airzone port 3: MHK-2
```

Here are some pictures of my test. 



![20250514_235612](https://github.com/user-attachments/assets/74663754-ff04-4479-bca4-b16d6258fcf8)
![20250514_235521](https://github.com/user-attachments/assets/9f8faa36-eecf-4ff1-90b8-0cfa5ae29b5a)
![20250514_235446](https://github.com/user-attachments/assets/15eee20f-916b-4daf-bd42-89483ab33f42)
![20250514_224900](https://github.com/user-attachments/assets/c3d2ba0f-5666-4297-a997-2bcd332c6a92)
![20250514_224855](https://github.com/user-attachments/assets/3f3d8e3f-095e-40d6-a8d5-fcb1c0a3ea39)

Update: I needed the 3.3 v from the esp8266 to power the level shifter. It wouldn't work consistently without it. 

Update 2: I used this on my PEAD ducted unit in my attic. It works perfectly without WF-2.   So my configuration works as this:
```
Airzone port 1: CN105 from PEAD minisplit
Airzone port 2: MHK-2
Airzone port 3:  esp8266 with level converter
```

**Comment by jharris4** [comment]
Thanks so much for taking the time to post about this! Thanks to this discussion, I finally have my Mitsubishi heat pump controlled via an air zone splitter with an esp32 instead of an esp8266.

I just had to buy the logic level converter and wire it up as shown above to a spare esp32 I had lying around. It worked on the second try (after classic tx/rx mixup on the uart cables for the first try lol)

I'll share my configuration for a generic esp32 in case it helps someone else:

```
substitutions:
  name: esp32-mitsubishi
  friendly_name: ESP32 Mitsubishi

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable Home Assistant API
api:
  encryption:
    key: "api_encryption_key"

ota:
  - platform: esphome
    password: "ota_password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Mitsubishi"
    password: "wifi_ap_password"

captive_portal:

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Enable Web server.
web_server:
  port: 80

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 120s

# Create a button to restart the unit from HomeAssistant. Rarely needed, but can be handy.
button:
  - platform: restart
    name: "Restart ${friendly_name}"

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO17
  rx_pin: GPIO16

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome@v1.4.1
  # - source: github://echavet/MitsubishiCN105ESPHome

# Enable logging
logger:
  hardware_uart: UART1
  level: INFO
  logs:
    EVT_SETS : INFO
    WIFI : INFO
    MQTT : INFO
    WRITE_SETTINGS : INFO
    SETTINGS : INFO
    STATUS : INFO
    CN105Climate: WARN
    CN105: INFO
    climate: WARN
    sensor: WARN
    chkSum : INFO
    WRITE : WARN
    READ : WARN
    Header: INFO
    Decoder : INFO
    CONTROL_WANTED_SETTINGS: INFO
#  level: DEBUG
#  logs:
#    EVT_SETS : DEBUG
#    WIFI : INFO
#    MQTT : INFO
#    WRITE_SETTINGS : DEBUG
#    SETTINGS : DEBUG
#    STATUS : INFO
#    CN105Climate: WARN
#    CN105: DEBUG
#    climate: WARN
#    sensor: WARN
#    chkSum : INFO
#    WRITE : WARN
#    READ : WARN
#    Header: INFO
#    Decoder : DEBUG
#    CONTROL_WANTED_SETTINGS: DEBUG

climate:
  - platform: cn105
    id: hp
    name: "${friendly_name}"
    icon: mdi:heat-pump
    visual:
      min_temperature: 15
      max_temperature: 30
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1
    # remote_temperature_timeout: 30min
    # update_interval: 4s
    update_interval: 10s
    debounce_delay : 500ms
    compressor_frequency_sensor:
      name: ${name} Compressor Frequency
    outside_air_temperature_sensor:
      name: Outside Air Temp
    vertical_vane_select:
      name: ${name} Vertical Vane
      disabled_by_default: true
    horizontal_vane_select:
       name: ${name} Horizontal Vane
       disabled_by_default: true
    isee_sensor:
      name: ${name} ISEE Sensor
      disabled_by_default: true
    stage_sensor:
      name: Stage Sensor
    sub_mode_sensor:
      name: Sub Mode Sensor
    auto_sub_mode_sensor:
      name: Auto Sub Mode Sensor
    input_power_sensor:
      name: Input Power
      disabled_by_default: true
    kwh_sensor:
      name: Energy Usage
      disabled_by_default: true
    runtime_hours_sensor:
      name: Runtime Hours
      entity_category: diagnostic
      disabled_by_default: true
```
