### DISCUSSION TITLE
Heat pump heating beyond target

### DISCUSSION THREAD

**Discussion by CopperSubstrate** [echavet/MitsubishiCN105ESPHome#274] [Q&A]
Our home has many Mitsubishi heat pumps. I've installed the integration on all of them, replacing the prior integration. 
	
Recently as it has become cold I've noticed an issue. Our largest unit, a Mitsubishi MSZ-GL18NA-U1 (the only unit which has vertical and horizontal swing modes), will sometimes continue to heat past the heat target set in the integration, and the integration will report that it's not heating. Logs show the heat climbing past the target but do not show the unit as actively heating.

**Comment by phidauex** [comment]
Hmm, that is odd. It could be intended operation, I've noticed they do have some hysteresis and will sometimes overshoot a bit in order to run a longer cycle. It could also be bleedover if you have multiple heads on the same outdoor unit - if other units are still heating, then hot refrigerant is still run through the "off" head, in order to keep oil from pooling. This can cause them to put out some heat even if the unit is trying to be off.

What do the LEDs on the front say when it is doing this?

<img width="371" alt="image" src="https://github.com/user-attachments/assets/3a4ac529-eee0-43f1-bfe8-e90caecf3d3e" />

**Comment by CopperSubstrate** [comment]
> Hmm, that is odd. It could be intended operation, I've noticed they do have some hysteresis and will sometimes overshoot a bit in order to run a longer cycle. It could also be bleedover if you have multiple heads on the same outdoor unit - if other units are still heating, then hot refrigerant is still run through the "off" head, in order to keep oil from pooling. This can cause them to put out some heat even if the unit is trying to be off.
> 
> What do the LEDs on the front say when it is doing this?
> 
> <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/49047/395882175-3a4ac529-eee0-43f1-bfe8-e90caecf3d3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTE0MDYsIm5iZiI6MTczNDMxMTEwNiwicGF0aCI6Ii80OTA0Ny8zOTU4ODIxNzUtM2E0YWM1MjktZWVlMC00M2YxLWJmZTgtZTkwY2FlY2YzZDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAxMDUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmODAwNWFkZTI3MDJlNWQwMTNlNGY5OWFjZTMyOWFmMDY5YTQwOGRkODU2NjQ5NmUyZGY3NTJiODA4ZjkyYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.63btSHjgwF85N2DbpvRZCnrS8ecOufO5uv_vP0-OAPo">

It was the usual light pattern - only the top light on and solid.

**Comment by CopperSubstrate** [comment]
I'm seeing this issue again with a different unit. This one definitely has both lights illuminated.

**Comment by CopperSubstrate** [comment]
I've now had this issue with two of my Mitsubishi units of different models:

- Temperature is below target. Unit is turned on by the integration.
- Temperature target is reached. The unit should stop heating and is marked as not heating in the logs, but it still heats.
- We discover later that a room set to something like 66 degrees F is actually at 72 degrees. We turn the unit off manually.

While this intergration has been superior in every other way to the gysmo38 integration, I did not have this issue with that integration despite using the same units and same ESP8266s. It definitely wasn't an issue when using the remotes.

**Comment by CopperSubstrate** [comment]
> Hmm, that is odd. It could be intended operation, I've noticed they do have some hysteresis and will sometimes overshoot a bit in order to run a longer cycle. It could also be bleedover if you have multiple heads on the same outdoor unit - if other units are still heating, then hot refrigerant is still run through the "off" head, in order to keep oil from pooling. This can cause them to put out some heat even if the unit is trying to be off.
> 
> What do the LEDs on the front say when it is doing this?
> 
> <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/49047/395882175-3a4ac529-eee0-43f1-bfe8-e90caecf3d3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNDEwNjIsIm5iZiI6MTczNjM0MDc2MiwicGF0aCI6Ii80OTA0Ny8zOTU4ODIxNzUtM2E0YWM1MjktZWVlMC00M2YxLWJmZTgtZTkwY2FlY2YzZDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA4VDEyNTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MGNhZjkwMWFjMGMzMWIxODBiYTJmYzI4ZTEwMTZkNTdmMDZlMGUzZDE2MjZiNmI3MWE2M2IyNGZhNzY5ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ImvRHwvHG2bEY2XkjT7scQ2rDJg-3vaykWeMjdx3SOs">

I do not  think this is the intended operation as the variance between the set temp and actual temp has been as high as seven degrees.

I think this qualifies as a bug rather than a question.

**Comment by phidauex** [comment]
The reason I was a little uncertain is that it sounds a lot like bleedover temperature overshoot, which is most likely to happen deep in the heating season. However if both lights are illuminated then that is suspicious. I'm wondering if inconsistent communications with the indoor unit are causing updates to get missed, meaning the indoor unit thinks the room temperature is lower than it is.

Can you share you configuration YAML file, and load up the History tab in HA and add both your heatpump climate entity and your remote temperature sensor entity, as below.

This example shows a heatpump control operating normally - the air temp sensors are updating frequently, the "current temp" value that the HP has is always in line with the measurement (rounded to the 0.5C), and heating correctly cuts off and restarts above and below the setpoint.

![image](https://github.com/user-attachments/assets/734359d5-bece-4e26-90c7-13dafbafd16c)

This one shows a minor problem, my temp sensor here doesn't update as quickly, so there are times when the remote temperature sensor timeout (30min) is triggered, and the unit reverts to its internal temperature up by the ceiling and stops heating. After a while the remote temp sensor updates and it drops back to the room average again.

![image](https://github.com/user-attachments/assets/53fb3a92-f8f1-4287-9cba-c47e6d6469fd)

**Comment by CopperSubstrate** [comment]
Sure. Here's one of the graphs of such an incident. As you can see, the Nursery is set to 65 degrees. The room was unoccupied and so we didn't know anything was amiss. It was around 7 PM that we noticed that the heat was on and that the temperature in the room had raised way beyond the target - at that point I shifted the unit from "heat" to "off."
<img width="1199" alt="image" src="https://github.com/user-attachments/assets/99110cf4-f342-4e91-83d3-296dec4dce95" />

The YAML for this unit is here: [Nursery YAML.txt](https://github.com/user-attachments/files/18370317/Nursery.YAML.txt)

**Comment by phidauex** [comment]
Interesting - the remote temperature is being updated correctly, and the unit is reporting the correct setpoint temperature. Is there another indoor unit connected to this same outdoor unit? If so, can you show what it was doing during this time as well? Any chance of a power meter reading?

**Comment by CopperSubstrate** [comment]
I have an Emporia Vue hooked up to the breaker box downstairs, but the measurements I get are only by condenser - so I do have measurements but only for the entire floor - that consists of three pumps - one other was on during the period and the other was off. Picture attached - I'm not sure I can make much sense of the significance here myself, except that it 

<img width="1722" alt="image" src="https://github.com/user-attachments/assets/f668629e-a005-4f2d-b29a-a05623383100" />

**Comment by CopperSubstrate** [comment]
<img width="1719" alt="image" src="https://github.com/user-attachments/assets/5c5dbec1-3fec-45c3-8842-990ef2c6dcbe" />
Here's a much messier diagram showing both units' data with the power use.

**Comment by phidauex** [comment]
Are Nursery and Bedroom on the same outdoor unit (Condensor 1)? Something definitely seems off because Bedroom is calling for heat nearly all day, but its reported current temperature is almost dead flat. Then at 12:15 and again at 7:00, the measured temperature in that room spikes, the unit turns off, and it rapidly cools as expected, but then goes flat again.

I'm also noticing that while the Bedroom unit claims to be calling for heat, the outdoor unit is off quite a lot, you'd expect to see the outdoor unit running and modulating as long as the indoor unit is calling for heat.

What remote temperature sensor is Bedroom looking at, and does it show clean output?

**Comment by echavet** [comment]
Hey,
Are you un this same situation?

https://hvac-talk.com/vbb/threads/2263095-Mitsubishi-MSZ-FS-Heating-Temperature-Overshoot

**Comment by CopperSubstrate** [comment]
> Are Nursery and Bedroom on the same outdoor unit (Condensor 1)? Something definitely seems off because Bedroom is calling for heat nearly all day, but its reported current temperature is almost dead flat. Then at 12:15 and again at 7:00, the measured temperature in that room spikes, the unit turns off, and it rapidly cools as expected, but then goes flat again.
> 
> I'm also noticing that while the Bedroom unit claims to be calling for heat, the outdoor unit is off quite a lot, you'd expect to see the outdoor unit running and modulating as long as the indoor unit is calling for heat.
> 
> What remote temperature sensor is Bedroom looking at, and does it show clean output?

They're on the same outdoor unit. Interesting point about the bedroom. I assume it was on but the fan mode was on "quiet" and the doors were open so heating was minimal, but so far I don't see a way to see historical fan settings. 

The bedroom sensor is a Centralite 3310-G and is accurate, albeit it's on the far side of the room from the heat pump. 

This did make me think of something as I noticed this same issue today with the Attic into, which shares an outdoor unit with the Guest pump. While the Attic unit was listed as off (on heat, actual temp > target temp), the guest unit *was* on and calling for heat. The Attic heat seemed to stop when I turned the Guest unit off. 

This is just one example so I'll have to keep testing, but you've got me thinking about how this could be related to interactions between pumps that share a unit.

**Comment by CopperSubstrate** [comment]
> Hey, Are you un this same situation?
> 
> https://hvac-talk.com/vbb/threads/2263095-Mitsubishi-MSZ-FS-Heating-Temperature-Overshoot

Opposite issue in some ways. Cooling is fine but the unit's own temperature readings are usually wildy higher than ambient temperatures, so you need to crank up the units to 76+ just to get the units to activate and heat to 66. 

The issue impacted different units to different extents. I was never able to fix it directly, so the main reason I jumped to this integration was that it allowed me to use remote temperature sensors (secondary reason: this integration is much more reactive than the old one).

**Comment by phidauex** [comment]
To see historical fan settings, you can enable the "Stage" setting, which seems to work on most indoor units. It shows the current actual fan speed of the unit, which can show if the fan is still running even if the unit is otherwise "off".

<img width="558" alt="image" src="https://github.com/user-attachments/assets/e20f9342-cfe5-4e7b-9e6e-f752822e41bb" />

In the case of Guest and Attic being on the same outdoor unit, what can happen is that if Guest is calling for heat, the outdoor unit will circulate hot refrigerant. To keep oil from pooling in the system, it will circulate hot coolant to Attic as well. Different outdoor units can throttle this excess coolant down more or less (units with branch boxes and Smart Multi can throttle further down), but they all let some through. If Guest and Attic have very different heat loads, then it can mean that when Guest is crankin', Attic is getting overheated. This happens more in colder conditions because Guest's runtime will be proportionally longer.

One thing that can make this worse, but that maybe could be addressed through automation, is the fan speed. If Attic is set to "heat", then the fan will never turn off, it will stay on Gentle in order to circulate air through the temp sensors so it knows if it should turn back on. This means the evaporator is getting heat, and the fan is running, so the heat is transferring to the room. People usually notice that if they turn the overheating unit to "off", then the louvers close, the fan shuts off, and the overshoot is mitigated. It might be possible to automate that behavior - say, if actual temp is 2 degrees over the setpoint, then turn the unit to "off". If actual temp is less than 2 degrees over setpoint, turn back to "heat".

**Comment by CopperSubstrate** [comment]
I'll have to enable the stage setting today and see if that adds more detail and see what hapened next time.

**Comment by CopperSubstrate** [comment]
I believe you're on to something here. The bedroom unit's assigned remote temperature sensor was mounted on a relatively cool wall - a poorly insulated area is behind it that has some plumbing. I moved it elsewhere and the bedroom's use now looks much "healthier" - it isn't always on. 

![Image](https://github.com/user-attachments/assets/aca2ad21-03b7-4e93-a4f0-5b99c9e818b0)

I've been testing and while I have still experienced this overshoot issue, it seems linked to another pump within the system actively heating - I've been able to sometimes stop the issue  in the attic by turning the guest unit off (its compressor "buddy.")

**Comment by CopperSubstrate** [comment]
<img width="920" alt="Image" src="https://github.com/user-attachments/assets/48104916-4322-4917-8ad3-1f7459b6c4ad" />

An insight here: I enabled the stage mode and it shows the fan mode switching to low and off nonstop while this issue is active.

**Comment by echavet** [comment]
hi guys,
Is this issue still considered a BUG, or is it a regulation issue to be attributed to the side effects of multisplit systems?

**Comment by CopperSubstrate** [comment]
Honestly I'm not sure - the Mitsubishi support line didn't give me much insight. So for now I think the answer is "probably?" but I'm not sure.

**Comment by phidauex** [comment]
Was doing some other reading and wanted to throw in a potential solution here (not related to this project). On the GL series indoor units, there is a jumper you can cut that causes the fan to stop running when the unit reaches setpoint. This is intended to be used alongside a remote-sensing thermostat like the MHK2, but it should work with this ESPHome solution as well.

The change isn't "permanent" as long as you are careful to snip the jumper in such a way that you could solder it back closed if you wanted, but it is a bit committing, so I wouldn't change it unless you were sure you were sticking with this (or another) remote sensing thermostat product.

Overview of the issue from Mitsubishi: http://s3.amazonaws.com/enter.mehvac.com/DAMRoot/Original/10009%5CApplication%20Note%201036%20ME%20-%20Applying%20MXZ-C%20Multi-Zone%20Systems%20-%2020190110.pdf

Instructions on cutting the jumper (page 10 for GL units): https://www.mylinkdrive.com/viewPdf?srcUrl=http://s3.amazonaws.com/enter.mehvac.com/DAMRoot/Original/10006%5CApplication%20Note%203048%20ME%20-%20How%20to%20turn%20off%20indoor%20unit%20fan%20when%20set%20point%20is%20met.pdf

EDIT: Converting this issue to a discussion since there is some good stuff in here that could be useful to someone else searching on the same topic.

**Comment by randalln** [comment]
I'm in the midst of switching from the Hubitat driver to this awesome implementation on HA and have a five-head setup, and I've always experienced the overshoot no matter how many other heads are active. My workaround in the HE driver was set the remote temp to +0.5C while the head was operating, then drop it back down -0.5C when it went idle. It's ugly, but it worked for me.
As an aside, I also have an app that fights the bleed over by turning the head off at a given threshold (arguably even uglier).

My goal is to contribute a setting of some kind to this project (but I have a steep learning curve).

**Reply by randalln** [reply]
The same approach is working for me with my "remote_temp" sensor.

```yaml
globals:
  - id: remote_temp_last_update
    type: uint32_t
    restore_value: no
    initial_value: '0'
  - id: remote_temp_raw
    type: float
    restore_value: no
    initial_value: '0.0'

sensor:
  # Import temperature from Home Assistant
  - platform: homeassistant
    name: "Remote Temperature Sensor ${location}"
    id: remote_temp
    entity_id: ${remote_temp_entity}
    internal: true  # Don't expose back to HA (already have original sensor)
    filters:
      # Uncomment the lambda line to convert F to C on incoming temperature
      - lambda: return (x - 32) * (5.0/9.0);
      - clamp: # Limits values to range accepted by Mitsubishi units
          min_value: 1
          max_value: 40
          ignore_out_of_range: true
      - throttle: ${remote_throttle}
    on_value:
      then:
        - lambda: |-
            // Store raw temperature
            id(remote_temp_raw) = x;
            id(remote_temp_last_update) = millis();
            
            // Get current HVAC action
            auto call = id(hp).make_call();
            auto mode = id(hp).mode;
            auto action = id(hp).action;
            
            float adjusted_temp = x;
            
            // Add 0.5°C when actively heating to prevent overshoot
            if (mode == climate::CLIMATE_MODE_HEAT && 
                action == climate::CLIMATE_ACTION_HEATING) {
              adjusted_temp = x + 0.5;
              ESP_LOGI("remote_temp", "Heating active - adding 0.5°C offset (%.1f°C -> %.1f°C)", x, adjusted_temp);
            } else if (action == climate::CLIMATE_ACTION_IDLE) {
              // Send unmodified value when idle
              ESP_LOGI("remote_temp", "Heat pump idle - using raw temp: %.1f°C", x);
            } else {
              ESP_LOGI("remote_temp", "Other state - using raw temp: %.1f°C", x);
            }
            
            id(hp).set_remote_temperature(adjusted_temp);
```
