### DISCUSSION TITLE
Enabling Bluetooth Proxy on ESP32 Dev board

### DISCUSSION THREAD

**Discussion by JaredK1** [echavet/MitsubishiCN105ESPHome#276] [Q&A] [answered]
Is anyone else running this project on an ESP32 dev board with Bluetooth Proxy enabled?

I am setup on 6 of my head units (MSZ-GL06NA, MSZ-GL09NA & MSZ-GL15NA). With remote temperature sensor enabled, I quickly found that my Hue motion sensors were not responsive enough as they updated temp values every 5 minutes. These also stopped reporting temperature changes once the heatpump approached the target temperature value, causing the remote timeout to occur. My search for a more frequently updating temp sensor landed me with either Xiaomi Thermometer LYWSD03MMC or an RTL sensor. Decided to try the LYWSD03MMC flashed with [pvvx custom firmware ](https://github.com/pvvx/ATC_MiThermometer) and thought it would be slick to have my ESP32 boards performing double duty. Since I have a head unit in most rooms in my house I could also enable Bermuda BLE Trilateration.

I did enable one of my boards with Bluetooth proxy for a week and didn’t notice much of any performance issues. The only thing I really saw in the logs was the cycle time going from 1.1-1.2 seconds to 1.3 seconds occasionally. The arduino framework seemed to run at 1.1 seconds while esp-idf Is 1.2 seconds. From what I’ve read in the other discussions and documentation this doesn’t seem like it would be a problem.

My main concern was with power draw from increased CPU load on the boards potentially damaging the head units circuitry over time. Maybe unfounded?

**Comment by rwarner** [comment]
I would also be curious in this concern. I too was hoping to pop some of these in around the house and was hoping to rely on the Philips Hue motion sensors for temperature values. Wouldn't have considered the value updating interval would be an issue.

Are you using the 5v line directly? Or doing the 3.3v with the voltage regulator stuff

**Comment by phidauex** [comment]
I have bluetooth proxy and a few temperature probes running on the tiny Xiao ESP32-S3, and haven't had any stability problems or heat issues. There is a folder with my example configuration in the main repo, I'm on the esp-idf framework, and the one "xiao-specific" tweak required is to set a manual wifi power. But generally I think you'd be fine running the proxy server. If you are concerned about performance or see a performance problem, the ESP32-S3 units have plenty of processing power.

**Comment by JaredK1** [comment, marked as answer]
@rwarner I decided to give it a go and updated all my boards to esp-idf and enabled BT Proxy. Been going for a few weeks now and had zero issues, Its been working great. I've now got BT signal coverage throughout my entire home hidden away inside my splits. 

I went with an ESP32 Dev NodeMCU V1.1 board and printed an enclosure to keep it tidy.

**Reply by rwarner** [reply]
Awesome, good to hear. Thanks for the update.

**Comment by echavet** [comment]
I also have bt-proxy enabled on one of my esp. 
Another ESP is sharing MitsubishiCN105ESPHome and [AwoX-BLE-mesh-hub](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub). 

```yaml
substitutions:
  name: "atom-s3"
  friendly_name: "M5Stack Atom S3 bt proxy + cn105"
  clim_name: Clim Sejour

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  #name_add_mac_suffix: true
  project:
    name: esphome.clim_and_nt_proxy
    version: "24.7.4.1"

debug:
  update_interval: 20s

# Enable logging
logger:
  #hardware_uart: USB_CDC
  baud_rate: 0
  level: INFO
  
esp32:
  board: esp32-s3-devkitc-1

  #board: m5stack-cores3
  #variant: ESP32S3
  framework:
    #type: arduino
    type: esp-idf
    version: recommended
  flash_size: 8MB

# mqtt, api, ota, wifi, captive, web, time
<<: !include atoms3/ha-integration-config.yaml

# display button and api status binary_sensor configuration
<<: !include atoms3/binary-sensor-config.yaml

# displays infos on atom screen
<<: !include atoms3/display_config.yaml
# configure esp bluetooth proxy
<<: !include atoms3/bt-proxy-config.yaml

# cn105 mitsubishi climate config
<<: !include atoms3/climate-config.yaml

```

bt-proxy-config.yaml
```bt-proxy-config.yaml
remote_transmitter:
  pin: GPIO4
  carrier_duty_percent: 50%

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true

bluetooth_proxy:
  active: true
```
