### DISCUSSION TITLE
Compile Error / MQTT failure

### DISCUSSION THREAD

**Discussion by fireball79** [echavet/MitsubishiCN105ESPHome#284] [Q&A] [answered]
Hi Guys,

i want to install this project on a wemos d1 min pro, but after creating several yaml files, i always get the compile error:

  Platform not found: 'climate.cn105'.

i use always this:

```
# External component reference
external_components:
  - source: github://echavet/MitsubishiCN105ESPHome
```

Any hints?
Thanks

**Comment by echavet** [comment]
> Hi Guys,
> 
> 
> 
> i want to install this project on a wemos d1 min pro, but after creating several yaml files, i always get the compile error:
> 
> 
> 
>   Platform not found: 'climate.cn105'.
> 
> 
> 
> i use always this:
> 
> 
> 
> ```
> 
> # External component reference
> 
> external_components:
> 
>   - source: github://echavet/MitsubishiCN105ESPHome
> 
> ```
> 
> 
> 
> Any hints?
> 
> Thanks

Hi @fireball79 
Please provide a complete yaml and a complete log of the error.
Thanks

**Reply by fireball79** [reply]
Hi,

this is the error:

```
D:\Hausautomatisierung\development\esphome>esphome run klimaanlage_test.yaml
INFO Reading configuration klimaanlage_test.yaml...
INFO Cloning https://github.com/echavet/MitsubishiCN105ESPHome@main
ERROR Unable to import component cn105.climate:
Traceback (most recent call last):
  File "C:\Users\rdomm\AppData\Local\Programs\Python\Python311\Lib\site-packages\esphome\loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rdomm\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Hausautomatisierung\development\esphome\.esphome\external_components\d98204d0\components\cn105\climate.py", line 3, in <module>
    from esphome.components.uptime.sensor import UptimeSecondsSensor
ImportError: cannot import name 'UptimeSecondsSensor' from 'esphome.components.uptime.sensor' (C:\Users\rdomm\AppData\Local\Programs\Python\Python311\Lib\site-packages\esphome\components\uptime\sensor.py)
Failed config

climate.cn105: [source klimaanlage_test.yaml:55]

  Platform not found: 'climate.cn105'.
  platform: cn105
  id: hp
  name: My Heat Pump
  update_interval: 5s
```



and here is my yaml file:

```
substitutions:
  name: esphome-klimaanlage
  friendly_name: ESPHome_Klimaanlage


esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini_pro
  # Boards tested: ESP-01S (ESP8266), Wemos D1 Mini (ESP8266); ESP32 Wifi-DevKit2

wifi:
  ssid: "xxxxxxxxxx"
  password: "xxxxxxxxxxxx"
  power_save_mode: high

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Klimaanlage-Fallback-Hotspot"
    password: "xxxxxxxx"

captive_portal:

# Enable Home Assistant API
api:

ota:
  password: "xxxxxxxx"

# Enable Web server.
web_server:
  port: 80

# Enable MQTT.
mqtt:
  broker: 192.168.178.100
  port: 1884
  discovery: false

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: 1
  rx_pin: 3


external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

# Climate entity configuration
climate:
  - platform: cn105
    name: "My Heat Pump"
    update_interval: 2s

# Default logging level
logger:
  hardware_uart: UART1 # Uncomment on ESP8266 devices
  level: INFO
```

i use a wemos d1 mini pro.

Also one question... i had one time a running build on the wemos with the version from [HERE](https://github.com/geoffdavis/esphome-mitsubishiheatpump) and now i have a running version from [HERE](https://github.com/gysmo38/mitsubishi2MQTT/releases).

But there is no connection to my inwall unit SLZ-M60FA. I have the CN105 (red) connector... pins are connected like in the description...
Do i need to adjust some setting?! UART? Baudrate?
I found here some debug feature, but i cant build this version.

Thanks

**Reply by fireball79** [reply]
i do a new try after reading [THIS ](https://github.com/echavet/MitsubishiCN105ESPHome/issues/85#issuecomment-2098867287) with the minimal config from the introduction... many options are invalid...

here some errors:
```
  [friendly_name] is an invalid option for [esphome]. Please check the indentation.
  [platform] is an invalid option for [ota]. Please check the indentation.
```

then i donwloaded the project and changed the external source to a local directory and now the cn105 is found...
```
external_components:
  - source: D:\Hausautomatisierung\development\esphome\Mitsubishi\components
```

after reducing more and more and the change of the external ressource i get only this error:

```
climate.cn105: [source .\test2.yaml:19]

  Unknown value 'QUIET', valid options are 'ON', 'OFF', 'AUTO', 'LOW', 'MEDIUM', 'HIGH', 'MIDDLE', 'FOCUS', 'DIFFUSE'.
  platform: cn105
  name: My Heat Pump
  update_interval: 2s
```


this is my test2.yaml now

```
esphome:
  name: heatpump-1

# For ESP8266 Devices
esp8266:
  board: d1_mini

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: 1
  rx_pin: 3

external_components:
  - source: D:\Hausautomatisierung\development\esphome\Mitsubishi\components

# Climate entity configuration
climate:
  - platform: cn105
    name: "My Heat Pump"
    update_interval: 2s

# Default logging level
logger:
  hardware_uart: UART1 # Uncomment on ESP8266 devices
  level: INFO

# Enable Home Assistant API
api:

ota:
  password: "eg0iche8"

wifi:
  ssid: "xxxxxxxx"
  password: "xxxxxxxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hotspot"
    password: "xxxxxxxxxx"

captive_portal:
```

**Reply by fireball79** [reply]
So a little success... i used a new wemos d1 min (not pro) installed [THIS ](https://github.com/gysmo38/mitsubishi2MQTT/releases) project and i configure my AC. 
So its working now, but i really want to use this project, to create my own settings.

**Reply by echavet** [reply]
> So a little success... i used a new wemos d1 min (not pro) installed [THIS ](https://github.com/gysmo38/mitsubishi2MQTT/releases) project and i configure my AC. 
> 
> So its working now, but i really want to use this project, to create my own settings.

Well you can fork the repository and put your own GitHub link in the source attribute, or you can clone it on your local drive and use the « local » type for external_component section.
Exemple:
‘‘‘yaml
external_components:
 - source:
     type: local
     path: ../components 

‘‘‘

**Reply by fireball79** [reply]
OK, i think the bug is in my environment... Now i setup a HomeAssistant System wirh ESPHomeCompiler, import the "Complete Configuration" changed step by step the config to my environment.

Build is running, flash is working and now i can use this code to manage my AC SLZ-M60FA.
Thanks

PS: My AC is not supporting 
- compressor_frequency_sensor
- horizontal_vane_select
- runtime_hours_sensor

so i commented this out, but in the logs there is still the warning:
`17:34:26	[W]	[lookup:206]  wideVane reading caution: value 0 not found, returning value at index 0`
I thought, if i dont use the sensors, there is not request for it... 

Thanks
René

**Reply by phidauex** [reply]
Sounds like you found the issue with the build environment, the invalid options errors you were getting seemed to be caused by the ESPhome version in the build environment being out of date.

As for the wideVane error, you can ignore that for now. The issue is that some units are responding with a value of 0 for the wideVane, which the component doesn't know how to interpret. Oddly different units seem to mean different things when 0 is returned, so we haven't been able to clearly map it. The error message is a nuisance for now, but it won't impact operation of your unit.

**Reply by fireball79** [reply]
Thanks for Feedback.
No some days the little Wemos runs fine. But now i have 2 last questions?!
1. Should the Debug/Logging which is inside of the Build deactivated? Its a lot and i have only the default ones from the example... with INFO, but MQ is flooded with it and it seems, the esp is restarting a lot of times, my uptime is only in seconds... should be run now for 2 days... and starts always new

this is uptime in MQTT:
![image](https://github.com/user-attachments/assets/cef761c6-d83f-4cfc-b63b-3ce8b083068a)


2. How can i manage with MQ the AV from my FHEM instance... i wrote to some topics, but nothing happend...

![image](https://github.com/user-attachments/assets/a298049b-6e50-4767-8906-9282250de58c)

Thanks

**Reply by fireball79** [reply]
little Update... 
If i use HA Plugin i can manage the AC. So it seems all functions are availble.
![image](https://github.com/user-attachments/assets/edbebc27-bb9d-4f0c-8473-c19f9b0e0f27)

But my system is based on FHEM and i cant manage via MQTT the AC. Also when i take a look to MQTT Explorer, i can see, which topics are written from HA plugin... 

So any hint, what can i do to manage the AC via MQTT?

Thanks

**Reply by echavet** [reply]
The best hint from far is to ask chatGPT, grok, Gemini or Claude for help!
MQTT topics are public and well known. So you should ask one LLM of your choice to guide you to control a climate component over MQTT.

**Reply by fireball79** [reply]
The question is, does this project supports MQTT?  I can see in MQTT Explorer it sends data to a MQTT server but is it possible to send data back?

Thanks

**Reply by echavet** [reply]
Yes of course it supports MQTT. But this is not a specific feature. MQTT is provided by ESPHome framework.
So you have tu enable it in your yaml configuration by configuring a client MQTT.


```yaml
mqtt:  
  broker: homeassistant.local
  username: username must be defined on the MQTT server side (mosquito)
  password: !secret mqtt_password
  discovery: true

```

**Reply by fireball79** [reply]
Hi,

yes thats my problem, i enabled it. Thats what i showed some post before. I can see everything in FHEM, in MQTT Explorer... i can read it.
Now i thought, i can use also the way back for change/manage the AC.

I found [here](https://github.com/gysmo38/mitsubishi2MQTT) in the gysmo38 project all the topics you can use for writing and sending the new parameters. But nothing happend. I thought its an feature, because all the projects based on the SwiCago/HeatPump library.

But if you there is no mechanism here in the project, then i can send what i want, i will never change something.

**Reply by echavet** [reply]
As I already told, the MQTT is provided through a generic ESPHome implementation.
This means the Climate component inherits MQTT feature from it.
Looking at other implementation like gysmo38 won't help.
Looking at the ESPHome project and the MQTT integration for home assistant will help. 
I can confirm you that this project is fully MQTT compliant. In both direction. My advice to ask support to chatGPT is still a good one !

**Reply by fireball79** [reply, marked as answer]
OK,
now i understand... sry... i read the docu from ESPHome and i found, that ESPHome is using a special protocol to communicate between HA and ESPHome Clients, if you are using the the API:
```
# Enable Home Assistant API
api:
```

If you want to use MQTT of course you need to activate this section, but additional with the discovery option = true:
```
# Enable MQTT.
mqtt:
  broker: 192.168.178.100
  port: 1884
  discovery: true
```

Then i got some MQ-Topics where i can write the settings and manage the AC via MQ!

Thanks
