### DISCUSSION TITLE
Ducted HP (SVZ-KP24NA), remote temperature sensor, and Celsius -> Fahrenheit

### DISCUSSION THREAD

**Discussion by glarizza** [echavet/MitsubishiCN105ESPHome#303] [Q&A] [answered]
Hi everybody, I've been using this code very successfully with a ductless heat pump and three head units (MSZ-GL12NA, and two MSZ-GL06NA), and decided to give it a try on the Ducted unit (SVZ-KP24NA) that services the main parts of my house. The ducted unit was previously connected to an MHK2 thermostat, but I disconnected it and connected my ESP32 board into the CN105 connection on the main board.

I'm using a remote temperature sensor from HA (I have HA set to Fahrenheit) with a lambda to convert F to C:

```yaml
sensor:
  - platform: homeassistant
    name: "Remote Temperature Sensor"
    entity_id: sensor.dining_room_temperature
    internal: false
    disabled_by_default: false

    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"
    filters:
    # Uncomment the lambda line to convert F to C on incoming temperature
      - lambda: return (x - 32) * (5.0/9.0);
      - clamp: # Limits values to range accepted by Mitsubishi units
          min_value: 1
          max_value: 40
          ignore_out_of_range: true
      - throttle: 30s
    on_value:
      then:
        - logger.log:
            level: INFO
            format: "Remote temperature received from HA: %.1f C"
            args: [ 'x' ]
        - lambda: 'id(mainhomeheatpump).set_remote_temperature(x);'
```

Everything starts okay in the logs, and the remote temperature value looks to get pulled from HA (the 24.5 Celsius value)

```

[19:38:46][I][STATUS:134]: [received]-> [room C°: 20.5, operating: NO , compressor freq: nan Hz]
[19:38:46][I][STATUS:134]: [current]-> [room C°: 0.0, operating: NO , compressor freq: nan Hz]
[19:38:46][I][STATUS:134]: [received]-> [room C°: 20.5, operating: NO , compressor freq: 0.0 Hz]
[19:38:46][I][STATUS:134]: [current]-> [room C°: 20.5, operating: NO , compressor freq: nan Hz]
[19:38:46][I][CYCLE:053]: 6: Cycle ended in 1.1 seconds (with timeout?:  NO)
[19:38:48][I][CYCLE:039]: 1: Cycle start
[19:38:49][W][lookup:206]: wideVane reading caution: value 0 not found, returning value at index 0
[19:38:49][I][STATUS:134]: [received]-> [room C°: 20.5, operating: NO , compressor freq: 0.0 Hz]
[19:38:49][I][STATUS:134]: [current]-> [room C°: 20.5, operating: NO , compressor freq: 0.0 Hz]
[19:38:49][I][CYCLE:053]: 6: Cycle ended in 0.9 seconds (with timeout?:  NO)
[19:38:51][I][CYCLE:039]: 1: Cycle start
[19:38:52][W][lookup:206]: wideVane reading caution: value 0 not found, returning value at index 0
[19:38:52][I][STATUS:134]: [received]-> [room C°: 24.5, operating: NO , compressor freq: 0.0 Hz]
[19:38:52][I][STATUS:134]: [current]-> [room C°: 20.5, operating: NO , compressor freq: 0.0 Hz]
[19:38:52][I][CYCLE:053]: 6: Cycle ended in 1.0 seconds (with timeout?:  NO)
[19:38:54][I][CYCLE:039]: 1: Cycle start
[19:38:55][W][lookup:206]: wideVane reading caution: value 0 not found, returning value at index 0
[19:38:55][I][STATUS:134]: [received]-> [room C°: 24.5, operating: YES, compressor freq: 0.0 Hz]
[19:38:55][I][STATUS:134]: [current]-> [room C°: 24.5, operating: NO , compressor freq: 0.0 Hz]
<...>
[19:39:56][I][STATUS:134]: [received]-> [room C°: 24.5, operating: NO , compressor freq: 0.0 Hz]
[19:39:56][I][STATUS:134]: [current]-> [room C°: 24.5, operating: YES, compressor freq: 0.0 Hz]
```

<img width="613" alt="Screenshot 2025-05-27 at 7 39 27 PM" src="https://github.com/user-attachments/assets/a3444b62-f9e5-41a0-84a3-f151a96bb08d" />

But every so often I'll get a stray 20.5 Celsius value that sets the current temp to 69 degrees Fahrenheit:

```
[19:39:57][I][CYCLE:053]: 6: Cycle ended in 1.0 seconds (with timeout?:  NO)
[19:39:59][I][CYCLE:039]: 1: Cycle start
[19:39:59][W][lookup:206]: wideVane reading caution: value 0 not found, returning value at index 0
[19:39:59][I][STATUS:134]: [received]-> [room C°: 20.5, operating: NO , compressor freq: 0.0 Hz]
[19:39:59][I][STATUS:134]: [current]-> [room C°: 24.5, operating: NO , compressor freq: 0.0 Hz]
```
<img width="613" alt="Screenshot 2025-05-27 at 7 40 04 PM" src="https://github.com/user-attachments/assets/58b3acd0-3781-4165-b92b-20e8e50a3b74" />

What I think is happening is that because the ductless unit is in my basement, and my basement is 20 Degrees C, I think that value is getting pulled from the internal temperature sensor from the ducted unit's main board. [This comment in a previous ducted heat pump thread](https://github.com/echavet/MitsubishiCN105ESPHome/discussions/105#discussioncomment-11456960) identifies the F to C to F conversion causing temperatures to be off by one degree, which makes sense because 20 degrees Celsius is 68 degrees Fahrenheit, and in my second picture you can see it's reflecting the current temp as 69 degrees instead of 68.  But I think my biggest problem is this internal -> remote temperature flapping? 

I did expose and enable the "Remote Temperature Sensor" in HA, and it consistently reports the same value as the actual temperature sensor, so I don't think that actually tells me much of anything with regard to what value is being used:

<img width="1268" alt="Screenshot 2025-05-27 at 8 02 02 PM" src="https://github.com/user-attachments/assets/d97312d0-80a5-43f4-be23-0df8864bd3da" />

I tried to play around with the throttle filter and a large `remote_temperature_timeout` value to see if I could stop it from getting a value from the internal sensor, but that didn't seem to work well. #290 will be super helpful for me to determine whether it is flipping back to the internal temperature source (like I suspect) or whether it's something else.

My question for the folks who DO run this code on a ducted unit is - have you seen this happen before, and was there anything you did to correct it?  I noticed in #105 that people were using a CN105 splitter to allow the MHK2 thermostat to function at the same time as the ESP board, and it looks like they used that thermostat as the temperature sensor instead of either the internal or a remote temperature sensor. Does that end up working well?  I'm gonna order one of those Airzone splitters to try it out, but thought I would ask the question here too. It looks like @bass-windu had some luck with this and a similar ducted unit, so I'm hoping they could chime in.

Thanks for any pointers you can offer! Gonna drop some of my YAML configuration if that might be helpful. This isn't complete, but does include the most important bit:

```yaml

external_components:
  - source:
      type: git
      url: https://github.com/echavet/MitsubishiCN105ESPHome
      ref: v1.4.1

sensor:
  - platform: homeassistant
    name: "Remote Temperature Sensor"
    entity_id: sensor.living_room_temperature
    internal: false
    disabled_by_default: false
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"
    filters:
    # Uncomment the lambda line to convert F to C on incoming temperature
      - lambda: return (x - 32) * (5.0/9.0);
      - clamp: # Limits values to range accepted by Mitsubishi units
          min_value: 1
          max_value: 40
          ignore_out_of_range: true
      - throttle: 30s
    on_value:
      then:
        - logger.log:
            level: INFO
            format: "Remote temperature received from HA: %.1f C"
            args: [ 'x' ]
        - lambda: 'id(mainhomeheatpump).set_remote_temperature(x);'
  - platform: uptime
    name: Uptime
  # WiFi Signal sensor.
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 120s

climate:
  - platform: cn105
    id: mainhomeheatpump
    name: "Main Home Heat Pump"
    update_interval: 2s # update interval can be adjusted after a first run and logs monitoring
    icon: mdi:heat-pump
    visual:
      temperature_step:
        target_temperature: 1
        current_temperature: 0.5
    # Timeout and communication settings
    remote_temperature_timeout: 60min
    # Various optional sensors, not all sensors are supported by all heatpumps
    compressor_frequency_sensor:
      name: Compressor Frequency
      entity_category: diagnostic
      disabled_by_default: false
    outside_air_temperature_sensor:
      name: Outside Air Temp
      disabled_by_default: false
    isee_sensor:
      name: ISEE Sensor
      disabled_by_default: false
    stage_sensor:
      name: Stage
      entity_category: diagnostic
      disabled_by_default: false
    sub_mode_sensor:
      name: Sub Mode
      entity_category: diagnostic
      disabled_by_default: false
    auto_sub_mode_sensor:
      name: Auto Sub Mode
      entity_category: diagnostic
      disabled_by_default: false
    input_power_sensor:
      name: Input Power
      disabled_by_default: false
    kwh_sensor:
      name: Energy Usage
      disabled_by_default: false
    runtime_hours_sensor:
      name: Runtime Hours
      entity_category: diagnostic
      disabled_by_default: false
```

Log data from one of the attempts: 

[logs_mainhomeheatpump_run-4.txt](https://github.com/user-attachments/files/20473689/logs_mainhomeheatpump_run-4.txt)

**Comment by disruptivepatternmaterial** [comment]
Ok perhaps a dumb question - have you tried power cycling the entire system at the breaker? I have seen this before with ductless units and power cycling made it go away.

I am aware this is the IT joke of "have you tried turning it off and on again?" but it is a joke because sometimes it works :)

**Comment by glarizza** [comment]
Not a dumb question at all! I'm an ops engineer, and the "Windows fix" should have been what I started with :)  I flipped the breaker at the panel and restarted everything. It started off great, getting the remote temperature value, but then over time flipped back to what I presume is the internal temp:

[Reboot.txt](https://github.com/user-attachments/files/20474318/Reboot.txt)

**Reply by disruptivepatternmaterial** [reply]
DRAT! I have not been paying that close attention to this project because of other demands, but I'd say crank up the logging and grab some of it when it is happening and share it. We normally need the exact byte strings to see what's up. I am making a WILD guess that the ducted does not pick the external over the internal in the same way. I see something like this in the docs, or I think I do. But honestly someone who has a ducted unit might know more. Is there a way to disconnect the temp sensor on the ducted unit? Is it a plug you can wiggle out to test? A quick google...it looks like the below. I'd be curious to see what happened when you do this.

![image](https://github.com/user-attachments/assets/aec21c2a-8674-4d1a-b1ca-86ec12b62fb2)

**Reply by glarizza** [reply]
Ahh yeah, I should have bumped the logs and sent those earlier.  I ended up setting it like recommended in the docs:

```yaml
logger:
  level: DEBUG
  logs:
    EVT_SETS : DEBUG
    WIFI : INFO
    MQTT : INFO
    WRITE_SETTINGS : DEBUG
    SETTINGS : DEBUG
    STATUS : INFO
    CN105Climate: WARN
    CN105: DEBUG
    climate: WARN
    sensor: WARN
    chkSum : INFO
    WRITE : WARN
    READ : WARN
    Header: INFO
    Decoder : DEBUG
    CONTROL_WANTED_SETTINGS: DEBUG
```

So here's what my ducted unit's main board looks like:

![IMG_5469](https://github.com/user-attachments/assets/820dd677-459e-4c7e-aae6-5bcc902cf72f)

I'll have to pull up the schematic to see where the temperature sensor might be connected because I didn't see anything resembling your pic in the cabling.  There's a black cable in the bottom left corner of the screen that feeds up inside the duct behind it, so I suspect that might be it, but I need to research it a bit more.

Here's the logs:

[logs_mainhomeheatpump_run-5.txt](https://github.com/user-attachments/files/20474673/logs_mainhomeheatpump_run-5.txt)

Timestamps to note:

* 21:14:37 - This is when the HA Logbook registers that the heat pump has changed to "Cool". It was always in cool mode, but I'm assuming this means it's starting the cooling process
* 21:14:49 - This is when the current temperature goes from 75 degrees F (the remote temp) to 70 degrees F (some...other temp).

**Reply by ransur0t** [reply]
Hi folks!  I've recently had a Mitsubishi ducted H2i system installed and have been continuing to research ESPHome integrations for my air handler unit SVZ-AP18NL, specifically how to design the hardware integration to allow use of the MHK2 tstat and an M5Stack Atom S3 Lite ... landed on this thread and figured I would take a look at board schematics for @glarizza's unit SVZ-KP24NA.

From my findings pulling the service manual from https://www.mitsubishipro.com/products/SVZ-KP24NA, looks like these are the board connectors of relevance to this discussion:

CN20
TH1 INTAKE AIR TEMP. THERMISTOR

CN44
TH2 PIPE TEMP. THERMISTOR/LIQUID
TH5 COND./EVA.TEMP. THERMISTOR

From pouring through the installer settings and function codes for the MHK2 controller, you may want to look at function code 2 - Room temperature sensing location:
1 - Average temperature reading of all indoor units
2 - Sense temperature at the indoor unit
3 - Sense temperature at the controller (default if using CN105 controller)

**Comment by glarizza** [comment]
Yesterday I picked up an Airzone CN105 WiFi Splitter and an ESP-01 that I flashed with most of the functional settings from the configuration I was using with the ESP32 I described in my original question. I plugged the splitter into the CN105 connector on the main board of the air handler, and then plugged the MHK2 and the ESP-01 into the other two ports on the splitter. I also disabled the remote temperature sensor configuration that was giving me problems above. The result is similar to #105 - the MHK2 is providing the remote temperature and the ESP-01 is feeding data to Home Assistant. It works the way that I had hoped the ESP32 + HA remote temperature sensor would have. So I'm gonna roll with this setup for now, but I'd love to be able to get rid of the splitter in the future. I'll keep track of what's happening in the repo, and I'm down to test out any suggestions or code changes that might target this issue.

**Comment by disruptivepatternmaterial** [comment]
So interesting we are seeing commercial products come to market. I have been pondering your questions here and looking over all the logs I see from the data dumps I did way way way back and I just am not sure what could be happening...but one thing: this protocol does have room for variants (or not sure what the word might be) because it is also used for hot water heaters and other devices that Mitsu makes. It is just a semi-informed guess that might be what we are coming up against here. That splitter is not dumb from what I understand and it is likely understanding this variant-ness and adjusting accordingly.

I am not sure what is going on with the code...somehow I need to know what the "real" output of the splitter is. If you have a LA or a serial logger you can put on it. To backtrack here that is how I figure this out a 7 or 8 years ago: I sniffed what the kumo adapter was doing. That think has to be putting the temp in another slot that I am not aware of...

**Reply by glarizza** [reply]
The functional difference is that with the splitter in place and both the MHK2 Thermostat and ESP-01 being connected to CN105, the MHK2 can provide the remote temperature like it always does, and I can disable the remote temperature sensor code that was causing me the problems I described in the original question. It gives me the best of both worlds. But if there is a bug with this ducted air handler and whatever code in the repo is providing remote temperature support for it, I'm no longer seeing it because we're no longer following that code path. The main difference here being that this isn't a wall-mounted mini split unit, it's a ducted air handler in my basement.

**Reply by glarizza** [reply]
Oh, forgot to reply - I don't have a logic analyzer or serial logger :(  I'll check with some folks and see if I can get my hands on one, it would be good to capture some data and plumb some of the missing sensors!

**Comment by disruptivepatternmaterial** [comment]
OK so looked at your logs - I think I am the one who gave those pieces of data their names and wrote some of the code, not sure of it has been changed and the names are frankly stupid but the best I could come up with...what I am seeing there appears to be normal. 

Except that error about wide vane. Do you have that? Again dumb question - have you tried to remove that in the yaml? Maybe that is the bug...the unit is rejecting the update because the wide vane isnt there? I guess I can try to set that on my units that do not have it and see what happens.

    horizontal_vane_select:
      name: Horizontal Vane Orientation

this is in my units that have it, and not in the ones that do not have it.

**Reply by glarizza** [reply]
Yeah, I don't have either vane specified in my config:

```
# Climate entity configuration
climate:
  - platform: cn105
    id: mainhomeheatpump
    name: "Main Home Heat Pump"
    update_interval: 2s # update interval can be adjusted after a first run and logs monitoring
    icon: mdi:heat-pump
    visual:
      temperature_step:
        target_temperature: 1
        current_temperature: 0.5
    # Timeout and communication settings
    remote_temperature_timeout: 30min
    # Various optional sensors, not all sensors are supported by all heatpumps
    compressor_frequency_sensor:
      name: Compressor Frequency
      entity_category: diagnostic
      disabled_by_default: false
    outside_air_temperature_sensor:
      name: Outside Air Temp
      disabled_by_default: false
    isee_sensor:
      name: ISEE Sensor
      disabled_by_default: false
    stage_sensor:
      name: Stage
      entity_category: diagnostic
      disabled_by_default: false
    sub_mode_sensor:
      name: Sub Mode
      entity_category: diagnostic
      disabled_by_default: false
    auto_sub_mode_sensor:
      name: Auto Sub Mode
      entity_category: diagnostic
      disabled_by_default: false
    input_power_sensor:
      name: Input Power
      disabled_by_default: false
    kwh_sensor:
      name: Energy Usage
      disabled_by_default: false
    runtime_hours_sensor:
      name: Runtime Hours
      entity_category: diagnostic
      disabled_by_default: false
```

I don't mind the log spam cause it's not breaking anything. But like I said above this isn't a wall mounted mini-split, it's a ducted air handler (SVZ-KP24NA) that doesn't have any vanes. So I imagine there's differences in the code and the way it's interacting with the code in this repo. When I had the ESP32 connected, I also didn't get any useful information (like energy usage metrics) in the prometheus metrics like I do with my wall mounted mini-splits (MZ-gl12na). So I imagine there's a fair bit of difference between those two models.
