### ISSUE TITLE
Merge upstream?

### ISSUE THREAD

**Issue by paravoid** [echavet/MitsubishiCN105ESPHome#100]
I think it'd be useful for the long-term maintenace of the component, to submit it for inclusion in the main ESPHome repository.

There are currently multiple components for the same functionality in the wild (see geoffdavis/esphome-mitsubishiheatpump#131). I believe all them forks of geoffdavis' work, but with various small or larger changes from it. This one seems to be the most promising: the most recently active, stable, uses ESPHome's UART, and has the fewest dependencies.

From experience, I can say that the landscape is confusing for someone that is just starting to look at connecting their devices: lots of forks that are hard to compare with each other, subtly different configuration snippets for each, French error messages, hardware incompatibilies (see my comment in #85), documentation that is lacking including the necessary hardware. If you contrast it with e.g. the equivalent Midea code, where it's upstream and super straightforward: https://esphome.io/components/climate/midea.html

I think doing the last 10% of work on this fork to clean it up (incl. the aforementioned French messages 😀), write an esphome-docs snippet, and submit it, would do wonders. I realize you're a volunteer and I'm asking you to do a bunch of extra work -- I'm saying this with a lot of respect for your work and appreciation for all the work you've done already! I'm willing to help if possible.

**Comment by echavet** [comment]
I will test it as soon as it is available. The project seems to support communication with a thermostat.

**Comment by Sammy1Am** [comment]
Hello there!

Someone mentioned this project over on the PR and I stopped by and saw this issue.

> From a first look, it doesn't look to be based on this code at all.

Indeed, I started from scratch on mitsubishi_uart back at the beginning of 2023, so it's a separate attempt to provide support in ESPHome.  Of course I was able to leverage the knowledge from the other projects, but wanted to collect all the protocol knowledge in one place and tried to gather it into a wiki (which @KazWolfe has massively expanded and [organized here](https://muart-group.github.io/developer/packet-reference) ).

I don't know how long the ESPHome PR process will take (this is my first one), so you're always welcome to test it out sooner using `external_components`.

```yaml
external_components:
  - source: github://muart-group/esphome@dev
    components: [ mitsubishi_uart ]

uart:
  - id: hp_uart
    baud_rate: 2400  # Note: May be 9600 on some systems!
    parity: EVEN
    rx_pin:
      number: GPIO3
    tx_pin:
      number: GPIO1

mitsubishi_uart:
  heatpump_uart: hp_uart
```

I'm happy to answer any questions (you can always open issues over on the project page too of course).

I haven't had a chance to dig very deep, but it looks like this project has at least a couple features not yet in mitsubishi_uart, so hopefully those can also be rolled into ESPHome eventually as well.
