### ISSUE TITLE
Add example for external temp sensors

### ISSUE THREAD

**Issue by Bascht74** [echavet/MitsubishiCN105ESPHome#11]
Maybe you could add an example for external temp sensors. 

If you like, you could use my code: 

```
sensor:
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:XX:XX:XX"
    temperature:
      name: Thermometer
      id: temperature
      device_class: temperature
      state_class: measurement
      filters:
        throttle_average: 90s
      on_value:
        then:
          - lambda: 'id(use_your_name).set_remote_temperature(x);'
```
