### ISSUE TITLE
Support for wide vane mode on frontend

### ISSUE THREAD

**Issue by Quarks-1** [echavet/MitsubishiCN105ESPHome#115]
I have an MLZ-KP18NA2 ductless system which has the vane settings of 1-5 vertical, vertical swing, and wide vane.  Wide vane is when the internal horizontal vane will swing left and right or stay stationary, but it cannot be selected which angle you want.  Would it be possible to add this as a setting? Currently it is only controllable through the remote for me even if I choose 'both' or 'horizontal' swing modes on the esp device. Thanks!

**Comment by echavet** [comment]
Hey @Quarks-1,
My heatpumps do not support the widevane. 
So I cannot test this feature.

I'm surprised you're are the first person to face this issue.

Could you be more specific please ? I'm not sure to understand well. What is the combination of settings you can set with IR and not with the esp?

Could you also provide your complete yaml?

What I understand is that you would like to activate the horizontal swing with a specific angle, but you can't?

Are you using these attributes in the climate section?

```yaml
climate:
  vertical_vane_select:
    name: vertical vane orientation       
  horizontal_vane_select:
    name: horizontal vane Orientation
```

If so, did you notice the device in HA then provides separate select UI to set these options?
I know it's weird to have to use separate UI select components, but I didn't find a way to integrate the features in the UI climate component.
