### ISSUE TITLE
Duplicate value in diagnostic example

### ISSUE THREAD

**Issue by eikowagenknecht** [echavet/MitsubishiCN105ESPHome#120]
From the README. These two sensors will always show the same:

```yaml
  - platform: template
    name: "dg_uart_connected"
    entity_category: DIAGNOSTIC
    lambda: |-
      return (bool) id(hp).isUARTConnected_;
    update_interval: 30s
  - platform: template
    name: "dg_hp_connected"
    entity_category: DIAGNOSTIC
    lambda: |-
      return (bool) id(hp).isUARTConnected_; 
    update_interval: 30s
```

It seems the second should be something other than ...isUARTConnected?
