### ISSUE TITLE
Wrong Current temperature reported.

### ISSUE THREAD

**Issue by Pierre-33** [echavet/MitsubishiCN105ESPHome#121]
Hi
I'm using an external sensor for temperature monitoring like in your example:

```yaml
sensor:
  - platform: homeassistant
    name: "Temperature Sensor From Home Assistant"
    entity_id: sensor.clim_salon_temperature_sensor
    on_value:
      then:
        - lambda: 'id(hp).set_remote_temperature(x);'
```

This seems to work as the temperature display in Home Assistant for my heatpump is the same as the one of my sensor (26°), but as soon as a I turn on the heatpump, the temperature drop to 25° (my external sensor stay at 26°), and a few seconds after I turn off the heatpump it get back to 26.

I used the same setup with the original geoffdavis component that worked like a charm, but maybe yours need a slightly different setup?

**Comment by Pierre-33** [comment]
Here is the complete Yaml

```yaml
esphome:
  name: clim-bureau
  friendly_name: Clim Bureau

esp8266:
  board: esp01_1m

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: 1
  rx_pin: 3

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: xxx

ota:
  platform: esphome
  password: xxx

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Clim-Bureau Fallback Hotspot"
    password: xxx

captive_portal:

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

climate:
  - platform: cn105
    id: hp
    name: None
    update_interval: 4s
    compressor_frequency_sensor:
      name: Compressor Frequency
    vertical_vane_select:
      name: Vertical Vane
    horizontal_vane_select:
      name: Horizontal Vane
    #remote_temperature_timeout: 60min
    debounce_delay : 500ms

sensor:
  - platform: homeassistant
    name: "Temperature Sensor From Home Assistant"
    id: current_temp
    internal: true
    entity_id: sensor.clim_bureau_temperature_sensor
    on_value:
      then:
        - lambda: 'id(hp).set_remote_temperature(x);'

button:
  - platform: restart
    name: "Restart"
    
```

I say the topic about logger granularity in the documentation but I don't know which part would be relevant in debug and I'm affraid activating everything could be overwhelming. Any particular component you want in debug?
