### ISSUE TITLE
Reporting 0C/32F current temperature

### ISSUE THREAD

**Issue by tmchow** [echavet/MitsubishiCN105ESPHome#140]
without remote temperature sensor configuration, my unit is reporting a current temp of 0 degrees celcius for some reason.

Screenshot from the web server:
![image](https://github.com/user-attachments/assets/aa813f43-cf42-4d9c-94b3-af6498688959)

(In HA since it’s reporting in Fahrenheit it says it’s 32F). I expected this to work right out of the box so confused why it’s not.

My config:

```
substitutions:
  name: my-room-climate
  friendly_name: My Room Climate

esphome:
  name: ${name}
  friendly_name: ${friendly_name} 

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: latest

light:
  - platform: esp32_rmt_led_strip
    name: Led
    id: led
    internal: true
    rgb_order: GRB
    pin: 35
    num_leds: 4
    rmt_channel: 1
    chipset: ws2812
    restore_mode: ALWAYS_ON

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO2
  rx_pin: GPIO1

# Default logging level
logger:
  level: INFO

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

api:
  encryption:
    key: !secret esp_encryption_key
  services:
    - service: reboot
      then:
        - logger.log: "Reboot in progress..."
        - lambda: |-
            ESP.restart();
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "My-Room-Atom-S3-Lite"
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Create a button to restart the unit from HomeAssistant. Rarely needed, but can be handy.
button:
  - platform: restart
    name: "Restart ${friendly_name}"

# Climate entity configuration
climate:
  - platform: cn105
    name: "My Room Climate"
    icon: mdi:heat-pump
    compressor_frequency_sensor:
      name: ${name} Compressor Frequency
    vertical_vane_select:
      name: ${name} Vertical Vane
    horizontal_vane_select:
      name: ${name} Horizontal Vane
    debounce_delay : 500ms
    update_interval: 4s  # update interval can be ajusted after a first run and logs monitoring* 

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP
    ssid:
      name: SSID
    bssid:
      name: BSSID

  - platform: version
    name: Version
    hide_timestamp: true
    disabled_by_default: false
    icon: mdi:new-box
    entity_category: diagnostic

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: "Uptime"
    disabled_by_default: false
    force_update: false
    unit_of_measurement: s
    icon: mdi:timer-outline
    accuracy_decimals: 0
    device_class: duration
    state_class: total_increasing
    entity_category: diagnostic
    update_interval: 60s

  - platform: internal_temperature
    name: Internal Esp temperature
    entity_category: diagnostic

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: Signaal dB
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: Signaal %
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: " %"
    entity_category: diagnostic
    device_class: ""

switch:
  - platform: template
    id: eps32_s3_led_switch
    name: Led switch #${led_switch}
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON 
    lambda: return id(eps32_s3_led_switch).state;
    turn_on_action:
      - light.turn_on:
          id: led
          brightness: !lambda |-
            // output value must be in range 0 - 1.0
            return id(led_brightness).state / 100.0;
    turn_off_action:
      - light.turn_off:
          id: led


number:
    ## Set led brightness
  - platform: template
    id: led_brightness
    name: Led brightness #${led_brightness}
    icon: mdi:toggle-switch-variant
    mode: slider
    entity_category: config
    optimistic: true
    min_value: 0
    max_value: 100
    step: 10
    initial_value: 70
    restore_value: yes
    unit_of_measurement: "%"
    on_value:
      then:
        - if:
            condition:
              - light.is_on: led
            then:
              - light.turn_on:
                id: led
                brightness: !lambda |-
                  // output value must be in range 0 - 1.0
                  return id(led_brightness).state / 100.0;
```
