### ISSUE TITLE
Fan speeds in wrong/weird order

### ISSUE THREAD

**Issue by supermarkert** [echavet/MitsubishiCN105ESPHome#146]
I have a Mitsubishi MSY unit and everything works, but notice odd visual behavior of the Climate component that gets built in Home Assistant. The unit appears to support 6 fan modes:
- Auto
- Quiet
- 1 (low)
- 2 (medium)
- 3 (middle)
- 4 (high)

However, when I add a climate component to Home Assistant, the order is always:
- Auto
- 1 (low)
- 2 (medium)
- 4 (high)  **<----**
- 3 (middle)  **<----**
- Quiet

I don't mind the Quiet placement, but 3 & 4 are definitely out of place. I see the same behavior whether I use the official Thermostat card or use a 3rd party "Simple Thermostat" card.
![image](https://github.com/user-attachments/assets/8957ab77-e244-475f-85f9-ffb95011bc72)
![image](https://github.com/user-attachments/assets/130eb6c5-d8e5-4b1e-8a9d-ec6b4802ea3e)

Is there any way to re-order the fan speeds so they at least show 1-4 properly? Preferably, Quiet should be before 1 (low).

**Comment by phidauex** [comment]
I've dug into this one a bit and ran into a dead end. The issue appears to be with how ESPHome enumerates the fan modes. In this component the default fan modes are defined here (I don't think the order matters here): https://github.com/echavet/MitsubishiCN105ESPHome/blob/89e75b4eb4e0232a90f374bbb6410d7990566427/components/cn105/climate.py#L45

You can also specify other fan modes in your climate component definition.

But when ESPhome sends that over to HomeAssistant, it uses its own order, which is defined here: https://esphome.io/api/namespaceesphome_1_1climate#adb5ca2756a8991cedb030edebb3028dc

![image](https://github.com/user-attachments/assets/11ec585b-93fe-424a-8314-0ea96ac3115f)

You can see the order here matches what you are seeing in HA.

My workaround for my MSZ-GLxxNA units is to just drop the "middle" speed from my list. Honestly if I don't want auto fan speed, it is probably because I want minimum or maximum, so it doesn't add much value to me to select "middle" or "medium", so dropping one from the list is a small sacrifice.

```yaml
      fan:
        _name: Fan
        auto:
          name: null
          icon: mdi:fan-auto
        low:
          name: null
          icon: mdi:fan-speed-1
        medium:
          name: null
          icon: mdi:fan-speed-2
        high:
          name: null
          icon: mdi:fan-speed-3
        middle: false
        quiet:
          name: null
          icon: mdi:volume-mute
```
