### ISSUE TITLE
Getting a lot of log messages since the last update

### ISSUE THREAD

**Issue by Bascht74** [echavet/MitsubishiCN105ESPHome#15]
```
[00:09:02][I][app:102]: ESPHome version 2023.12.9 compiled on Jan 30 2024, 00:05:23
[00:09:03][W][lookup:172]: Attention valeur 0 non trouvée, on retourne la valeur au rang 0
[00:09:04][W][lookup:172]: Attention valeur 0 non trouvée, on retourne la valeur au rang 0
[00:09:05][W][lookup:172]: Attention valeur 0 non trouvée, on retourne la valeur au rang 0
```

I will check, if that device doesn't support the horizontal vane...
If that is true, maybe the value "0" could do a log output "not supported"... :-)

**Comment by Bascht74** [comment]
I removed the horizontal vane:

```
...
    update_interval: 1s  
#    compressor_frequency_sensor:
#      name: Compressor frequency (clim Sejour) 
#      internal: true   
    vertical_vane_select:
      name: Verticale Luftstromrichtung
#    horizontal_vane_select:
#      name: Horizontal Vane
    remote_temperature_timeout: 30min  
```

But still getting the log output. 
Is there a way to find out where it comes from?

**Comment by echavet** [comment]
Thanks. I'll have a look today.
But you are right it comes from one of these maps values binding functions.
But I don't know which one yet. Hope I'll be able to reproduce.
Are you sure it is the temperature one ?
However I'll first add some logs.

**Comment by Bascht74** [comment]
Yes, that is the case:

```
[23:49:31][W][lookup:172]: wideVane reading caution: value 0 not found, returning value at index 0
[23:49:32][W][lookup:172]: wideVane reading caution: value 0 not found, returning value at index 0
```

**Comment by Bascht74** [comment]
It isn’t possible to chance the setting, reverting back to 0x00…

**Comment by Bascht74** [comment]
I commented out the horizontal vane select for that device:

```
climate:
  - platform: cn105
    id: hp
    name: "${friendly_name}"
    supports:
      mode: ["HEAT_COOL", "DRY", "COOL", "HEAT", "FAN_ONLY"]
      fan_mode: ["AUTO", "DIFFUSE", "LOW", "MEDIUM", "MIDDLE", "HIGH"]
      swing_mode: ["OFF", "VERTICAL", "HORIZONTAL", "BOTH"]
    visual:
      min_temperature: 18
      max_temperature: 27
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
    update_interval: 1s  
#    compressor_frequency_sensor:
#      name: Compressor frequency (clim Sejour) 
#      internal: true   
    vertical_vane_select:
      name: Verticale Luftstromrichtung
#    horizontal_vane_select:
#      name: Horizontal Vane
    remote_temperature_timeout: 30min  
```

No entity is showing up in HA, but the component still does the lookup.

Would it be a good idea to discard lookups for sensors not created or do you want to leave it that way?
If you want to leave it that way, maybe it might the good to change the log level for that error to verbose?
