### ISSUE TITLE
Horizontal vane state doesn't show up after ESP reboots

### ISSUE THREAD

**Issue by sebi5361** [echavet/MitsubishiCN105ESPHome#152]
As can be seen on the below picture, the horizontal vane state doesn't show up after the ESP reboots:
![2024-08-24 21-32-28](https://github.com/user-attachments/assets/f6c3cfd4-88b6-47be-8e62-09e554c95a60)
...whereas the vertical vane state is shown properly.
I believe it is a (minor) bug as the configuration for both vanes is similar:
```yaml
    vertical_vane_select:
      name: ${friendly_node_name} Vertical Vane
    horizontal_vane_select:
      name: ${friendly_node_name} Horizontal Vane
```
