### ISSUE TITLE
Cycle timeout, reseting cycle... MSZ-FS06NA and MSZ-FS15NA

### ISSUE THREAD

**Issue by totempole** [echavet/MitsubishiCN105ESPHome#167]
Hello.. First off thank you for maintaining this. Your implementation has saved me from the poor quality that Kumo Cloud is.

Attached is the DEBUG log output from my board where I'm getting a cycle timeout. I did look at another issue  with the same error but that was marked fixed (which I cannot seem to find anymore).

ESP-Home: 2024.9.2
Board: ESP8266 ESP-01S
Mitsubishi  Indoor Model: MSZFS15NA and MSZFS06NA
Mitsubishi Outdoor Model: MXZ3C0NA
 All fan speeds, vane settings and modes have worked so far and with minimal delay if any. The only issue is the cycle timeout I see in the logs. I've tried changing the update_interval but that hasn't made any difference. I've attached the debug log below  to see if it's something peculiar to my model.

I've also tried with the d1_mini as the board model and recompiled it but that didn't change the cycle timeout behavior

If you need anything else please let me know

[logs_guest-room_logs (2).txt](https://github.com/user-attachments/files/17300759/logs_guest-room_logs.2.txt)
[guest-room (1).yaml.txt](https://github.com/user-attachments/files/17300916/guest-room.1.yaml.txt)

**Comment by echavet** [comment]
> Hello.. First off thank you for maintaining this. Your implementation has saved me from the poor quality that Kumo Cloud is.
> 
> 
> 
> Attached is the DEBUG log output from my board where I'm getting a cycle timeout. I did look at another issue  with the same error but that was marked fixed (which I cannot seem to find anymore).
> 
> 
> 
> ESP-Home: 2024.9.2
> 
> Board: ESP8266 ESP-01S
> 
> Mitsubishi  Indoor Model: MSZFS15NA and MSZFS06NA
> 
> Mitsubishi Outdoor Model: MXZ3C0NA
> 
>  All fan speeds, vane settings and modes have worked so far and with minimal delay if any. The only issue is the cycle timeout I see in the logs. I've tried changing the update_interval but that hasn't made any difference. I've attached the debug log below  to see if it's something peculiar to my model.
> 
> 
> 
> I've also tried with the d1_mini as the board model and recompiled it but that didn't change the cycle timeout behavior
> 
> 
> 
> If you need anything else please let me know
> 
> 
> 
> [logs_guest-room_logs (2).txt](https://github.com/user-attachments/files/17300759/logs_guest-room_logs.2.txt)
> 
> [guest-room (1).yaml.txt](https://github.com/user-attachments/files/17300916/guest-room.1.yaml.txt)
> 
> 
> 
> 
> 
> 

Hello @totempole 

Thank you for your message
Reading your logs I'd say the cycle timeout is too short. Probably because your ship is slow and your logs are verbose.
What you could try is
- Either to turn off the logs or configure them less verbose
- Or increase the update interval in your yaml because timeout is processed in ms this way:
(2 * update_interval) + 1000;

**Comment by echavet** [comment]
Ok
Another thing:
There was an added feature that is not fully supported bye all units.
In this case, unit can't reply. So when this situation occurred 3 or 4 times, the request is cancelled and not sent anymore.
This means you get 3, 4 or 5 attempts (I don't remember) with a cycle timeout. But then it should work fine.
You can check that by looking at the diagnose sensors in home assistant. One of them deals with the cycles. It should be more detailed information.

**Comment by echavet** [comment]
sure what is the error message?

**Comment by echavet** [comment]
Well you have found the issue!!
You did not define the climate id.
It should be defined as "guest-room".

**Comment by phidauex** [comment]
> /config/esphome/guest-room.yaml: In lambda function:
> /config/esphome/guest-room.yaml:78:24: error: 'guest' was not declared in this scope
> 78 | return (bool) id(guest-room).isUARTConnected_;
> | ^~~~~
> /config/esphome/guest-room.yaml:78:30: error: 'room' was not declared in this scope
> 78 | return (bool) id(guest-room).isUARTConnected_;

Here is your problem - dashes aren't supported in "id" names (I think in this case the C++ lambda is interpreting guest-room as "guest minus room". I'd rename your id as `guestroom` or `guest_room`. That should let it compile.

**Comment by phidauex** [comment]
Hmm, lets try this another way - try this configuration, it is my working config for a D1 mini, ESP8266, with a few details changed to match your example YAML. One note is that you don't need to spend much time thinking about the `id` of the component, that is only used internally to that ESPHome device, so `hp` as the id will work just fine in all cases, even if you have multiple heat pumps.

```yaml
substitutions:
  name: guest-room
  friendly_name: Guest Room Heatpump

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  
esp8266:
  board: esp01_1m

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome
    refresh: 0s

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: 1
  rx_pin: 3

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} ESP"
    password: "JJTG9QXWw2sv"

captive_portal:

# Enable logging
logger:
  hardware_uart: UART1
  level: INFO
  logs:
    EVT_SETS : INFO
    WIFI : INFO
    MQTT : INFO
    WRITE_SETTINGS : INFO
    SETTINGS : INFO
    STATUS : INFO
    CN105Climate: WARN
    CN105: INFO
    climate: WARN
    sensor: WARN
    chkSum : INFO
    WRITE : WARN
    READ : WARN
    Header: INFO
    Decoder : INFO
    CONTROL_WANTED_SETTINGS: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "6NIizdHdHwNKYYt/fwXL+3aJSdzSN8uGSIG8UVbB3I0="
  services:
    - service: set_remote_temperature
      variables:
        temperature: float
      then:
# Select between the C version and the F version
#        - lambda: 'id(hp).set_remote_temperature(temperature);'
        - lambda: 'id(hp).set_remote_temperature((temperature - 32.0) * (5.0 / 9.0));'
    - service: use_internal_temperature
      then:
        - lambda: 'id(hp).set_remote_temperature(0);'

ota:
  platform: esphome
  password: "b4369c1e82497c65433911a7e62b9488"

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: IP
    ssid:
      name: SSID
    bssid:
      name: BSSID

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 120s

# Create a button to restart the unit from HomeAssistant. Rarely needed, but can be handy.
button:
  - platform: restart
    name: "Restart ${friendly_name}"

climate:
  - platform: cn105
    id: hp
    name: "${friendly_name}"
    icon: mdi:heat-pump
    visual:
      min_temperature: 15
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.5
#    compressor_frequency_sensor:
#      name: ${name} Compressor Frequency
    outside_air_temperature_sensor:
      name: Outside Air Temp
    vertical_vane_select:
      name: Vertical Vane
#    horizontal_vane_select:
#      name: ${name} Horizontal Vane
#    isee_sensor:
#      name: ${name} ISEE Sensor
    remote_temperature_timeout: 30min
    update_interval: 2s
    debounce_delay : 100ms
#    stage_sensor:
#      name: Stage Sensor
#    sub_mode_sensor:
#      name: Sub Mode Sensor
#    auto_sub_mode_sensor:
#      name: Auto Sub Mode Sensor
```
