### ISSUE TITLE
Fan mode is not valid

### ISSUE THREAD

**Issue by flybrys** [echavet/MitsubishiCN105ESPHome#196]
Recently updated the esphome code and now this error is showing in the HA logs:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:287
integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 6:31:35 AM (2 occurrences)
Last logged: 6:32:09 AM

[140610517122016] Fan mode is not valid. Valid fan modes are: auto, low, medium, high, middle, quiet

Nothing specifically says its from this integration but its the only device I have that has those modes.

Functionally, I can't see anything wrong (yet)

**Comment by jamer007** [comment]
I had those errors at some point too when trying to change the fan mode (STAGE) into HA, my issue was I was using my smartphone and my keyboard auto-capitalized my text, I was ending with Middle instead of middle, High instead of high. The mode text is case-sensitive in HA. I hope this helps you.

**Comment by phidauex** [comment]
Hi @flybrys - Did the suggestion to confirm capitalization help? Since we haven't heard back on this one I'm going to close for now. If you've done additional troubleshooting and continue to get the error, feel free to add more information and reopen.

**Comment by flybrys** [comment]
Hi @phidauex and @jamer007 sorry I've been away for Christmas and couldn't check.

Where exactly am I looking for capitalisation? I haven't changed anything that required me to type in the fan modes manually so I'm not quite sure. The error just started appearing one day.

**Comment by phidauex** [comment]
Can you post your `climate:` section of your configuration YAML? Do you have `fan_mode:` specified anywhere in there?

**Comment by flybrys** [comment]
I don't have` fan_mode:` anywhere in the file. Here is the `climate:` section:

```
climate:
  - platform: cn105
    id: hp
    name: "${friendly_name}"
    icon: mdi:heat-pump
    update_interval: 2s        # update interval can be ajusted after a first run and logs monitoring* 
    debounce_delay: 500ms
    visual:
      min_temperature: 15
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
    remote_temperature_timeout: 30min
    outside_air_temperature_sensor:
      name: Outside Air Temp
    compressor_frequency_sensor:
      name: ${friendly_name} Compressor Frequency
    vertical_vane_select:
      name: ${friendly_name} Vertical Vane
    horizontal_vane_select:
      name: ${friendly_name} Horizontal Vane
    stage_sensor:
      name: Stage
      entity_category: diagnostic
    sub_mode_sensor:
      name: Sub Mode
      entity_category: diagnostic
    auto_sub_mode_sensor:
      name: Auto Sub Mode
      entity_category: diagnostic
    input_power_sensor:
      name: Input Power
    kwh_sensor:
      name: Energy Usage
    runtime_hours_sensor:
      name: Runtime Hours
      entity_category: diagnostic
      disabled_by_default: true 
```

**Comment by flybrys** [comment]
Could we please reopen this?
Recompiled from scratch and it still pops up. I can't be too sure if it is coincidental but it appeared a bit later this time and the only thing I did was change the fan mode to auto

**Comment by jamer007** [comment]
Hi again,
Here a good example in the HA ui:
![Image](https://github.com/user-attachments/assets/df3756a3-81bf-43b1-a317-9c90cb9458e6)

And now a bad one:
![Image](https://github.com/user-attachments/assets/25d62889-1343-40b6-8fc0-c45041b44326)

**Comment by flybrys** [comment]
> Hi again, Here a good example in the HA ui

Thanks for the reply, but I'm not using any automations (yet). The error shows up with just the device installed

**Comment by echavet** [comment]
Hi,
I know it sucks but I need more info to be able to diagnose the issue.
You can set the logging level to DEBUG for cn105.

```yaml
logger:
  baud_rate: 0
  level: DEBUG
  logs:
    ...
    CN105: DEBUG
    ...
```

try to follow the logs from the "ESPHome Builder" addon and to provide me more info on the pb you're facing.
thanks
