### ISSUE TITLE
Energy consumption

### ISSUE THREAD

**Issue by andrazek** [echavet/MitsubishiCN105ESPHome#197]
Is it possible to add sensors for energy consumption? My unit (AP25VG) supports this feature, as it's available through MELCloud. I assume the implementation would be similar to the one for the Ecodan Heat Pump: https://github.com/gekkekoe/esphome-ecodan-hp/

**Comment by duhow** [comment]
It is already available if you define it in config:

```yaml
climate:
  - platform: cn105
    kwh_sensor:
      name: Energy Usage
```
