### ISSUE TITLE
Feature request: Night mode

### ISSUE THREAD

**Issue by siljelb** [echavet/MitsubishiCN105ESPHome#208]
First of all, thank you for this excellent project!

My MSZ-LN35VG2W is working great with the basic functionality, but it also has a "night mode" which makes the outdoor unit quieter. I'd love to be able to set this automatically from HA instead of having to do it manually. Is this feasible to implement? Whether as a fan mode or maybe as a separate switch?

**Comment by echavet** [comment]
Sure it's possible through an automation:
It would look something like this:

'''
action: climate.set_fan_mode
data:
  fan_mode: QUIET
target:
  entity_id: climate.esp32_hp_clim_sejour
'''

**Comment by echavet** [comment]
But I did not test

**Comment by siljelb** [comment]
The "night mode" apparently isn't a fan mode as such, but a separate parameter of some sort. I've just tested specifically, and none of the states or parameters currently visible in HA change when I turn on and off night mode:
## Night mode off
![20241231_184305](https://github.com/user-attachments/assets/2f995f23-fc53-4a9a-9c7f-49e8c94dff11)
```yaml
hvac_modes:
  - "off"
  - cool
  - heat
  - fan_only
  - dry
  - auto
min_temp: 10
max_temp: 31
target_temp_step: 1
fan_modes:
  - auto
  - low
  - medium
  - high
  - middle
  - quiet
swing_modes:
  - "off"
  - both
  - vertical
  - horizontal
icon: mdi:heat-pump
friendly_name: Varmepumpe
supported_features: 425
current_temperature: 21.5
temperature: 21
fan_mode: auto
hvac_action: heating
swing_mode: "off"
```

## Night mode on
![20241231_184652(1)](https://github.com/user-attachments/assets/a2a6bfe4-5227-4122-ab62-38dd516c4281)
```yaml
hvac_modes:
  - "off"
  - cool
  - heat
  - fan_only
  - dry
  - auto
min_temp: 10
max_temp: 31
target_temp_step: 1
fan_modes:
  - auto
  - low
  - medium
  - high
  - middle
  - quiet
swing_modes:
  - "off"
  - both
  - vertical
  - horizontal
icon: mdi:heat-pump
friendly_name: Varmepumpe
supported_features: 425
current_temperature: 21.5
temperature: 21
fan_mode: auto
hvac_action: heating
swing_mode: "off"
```
