### ISSUE TITLE
Feature request: Add the "Smart Set" function (heat 10 degrees setpoint)

### ISSUE THREAD

**Issue by jfdrolet11** [echavet/MitsubishiCN105ESPHome#221]
My unit has the “Smart Set” function. This function allows the unit to be set in heat mode at 10 degrees. This is handy when you're away from home for a long time. 

I've tried to do a script in Home Assistant, but it doesn't work. It doesn't take the 10 degrees setpoint, it sets the heating to 16. 

Is-it possible to add a button for this function in ESPHome?

**Comment by phidauex** [comment]
This would be handy, but I think we'd need to capture the serial command that enables the feature. A few people have gone about doing that work, but I'm not the expert on it.

**Comment by rkboni** [comment]
AFAIR based on discussions in https://github.com/geoffdavis/esphome-mitsubishiheatpump, there really isn't a serial command that does this, the remote just sends the individual mode / temp / ... requests as a bundle.  I've faked this on my devices by just setting the temp range to start at 10 degC and manually adjusting it to that point:

```
climate:
  - platform: cn105
    name: "${friendly_name}"
    id: hp
    icon: mdi:heat-pump
    visual:
      min_temperature: 10
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
```
