### ISSUE TITLE
Separate Sensor Entity for Unit Temperature

### ISSUE THREAD

**Issue by nsvrana** [echavet/MitsubishiCN105ESPHome#232]
Currently, it looks like this only reports the current temperature (when not using an external sensor) as part of the "climate" entity in home assistant. Is there a way to have this also expose a temperature sensor which includes the current temperature as read by the unit itself?

**Comment by echavet** [comment]
Hi you try something like this (with your climate component id):
```yaml
sensor:
  - platform: template
    name: "Mitsubishi Indoor Temperature"
    id: indoor_temperature
    lambda: |-
      return id(mitsubishi_climate).current_temperature;
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
```
