### ISSUE TITLE
OTA Build for ESP32-C3 no longer works with ESPHome 2025.2.2

### ISSUE THREAD

**Issue by KeiranCantilina** [echavet/MitsubishiCN105ESPHome#248]
I've been having great success using this integration since October of 2024, but yesterday I was suddenly unable to install OTA updates to new devices because the compilation process fails with "fatal error: esphome/components/uptime/sensor/uptime_seconds_sensor.h: No such file or directory".

I've also tried compiling on Windows 10 using ESPhome on Python 3.10 via the command line, and I get the exact same issue.
Here's the log output from ESPHome Builder:

```
INFO ESPHome 2025.2.2
INFO Reading configuration /config/esphome/esphome-web-1f3948.yaml...
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.5.1
INFO Compiling app...
Processing esphome-web-1f3948 (board: lolin_c3_mini; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32.git#51.03.07)
--------------------------------------------------------------------------------
Platform Manager: Installing git+https://github.com/pioarduino/platform-espressif32.git#51.03.07
INFO Installing git+https://github.com/pioarduino/platform-espressif32.git#51.03.07
git version 2.39.5
Cloning into '/data/cache/platformio/cache/tmp/pkg-installing-vp2vhif2'...
Note: switching to 'ec17486ffa451374e108b72be07e9c8fa83338e8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Platform Manager: espressif32@51.3.6+sha.ec17486 has been installed!
INFO espressif32@51.3.6+sha.ec17486 has been installed!
Tool Manager: Installing https://github.com/pioarduino/esp-idf/releases/download/v5.1.5/esp-idf-v5.1.5.zip
INFO Installing https://github.com/pioarduino/esp-idf/releases/download/v5.1.5/esp-idf-v5.1.5.zip
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: framework-espidf@3.50105.0 has been installed!
INFO framework-espidf@3.50105.0 has been installed!
Tool Manager: Installing espressif/toolchain-riscv32-esp @ 12.2.0+20230208
INFO Installing espressif/toolchain-riscv32-esp @ 12.2.0+20230208
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: toolchain-riscv32-esp@12.2.0+20230208 has been installed!
INFO toolchain-riscv32-esp@12.2.0+20230208 has been installed!
Tool Manager: Installing espressif/tool-xtensa-esp-elf-gdb @ ~12.1.0
INFO Installing espressif/tool-xtensa-esp-elf-gdb @ ~12.1.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: tool-xtensa-esp-elf-gdb@12.1.0+20221002 has been installed!
INFO tool-xtensa-esp-elf-gdb@12.1.0+20221002 has been installed!
Tool Manager: Installing espressif/tool-riscv32-esp-elf-gdb @ ~12.1.0
INFO Installing espressif/tool-riscv32-esp-elf-gdb @ ~12.1.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: tool-riscv32-esp-elf-gdb@12.1.0+20221002 has been installed!
INFO tool-riscv32-esp-elf-gdb@12.1.0+20221002 has been installed!
Tool Manager: Installing https://github.com/pioarduino/esptool/releases/download/v4.8.1.1/esptool.zip
INFO Installing https://github.com/pioarduino/esptool/releases/download/v4.8.1.1/esptool.zip
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Tool Manager: tool-esptoolpy@4.8.1 has been installed!
INFO tool-esptoolpy@4.8.1 has been installed!
Tool Manager: Installing tasmota/tool-mklittlefs @ ^3.2.0
INFO Installing tasmota/tool-mklittlefs @ ^3.2.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Tool Manager: tool-mklittlefs@3.2.0 has been installed!
INFO tool-mklittlefs@3.2.0 has been installed!
Tool Manager: Installing platformio/tool-cmake @ ~3.21.0
INFO Installing platformio/tool-cmake @ ~3.21.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: tool-cmake@3.21.3 has been installed!
INFO tool-cmake@3.21.3 has been installed!
Tool Manager: Installing platformio/tool-ninja @ ^1.7.0
INFO Installing platformio/tool-ninja @ ^1.7.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Tool Manager: tool-ninja@1.10.2 has been installed!
INFO tool-ninja@1.10.2 has been installed!
Tool Manager: Installing espressif/toolchain-esp32ulp @ 2.35.0-20220830
INFO Installing espressif/toolchain-esp32ulp @ 2.35.0-20220830
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Tool Manager: toolchain-esp32ulp@2.35.0-20220830 has been installed!
INFO toolchain-esp32ulp@2.35.0-20220830 has been installed!
Library Manager: Installing esphome/noise-c @ 0.1.6
INFO Installing esphome/noise-c @ 0.1.6
Unpacking  [####################################]  100%
Library Manager: noise-c@0.1.6 has been installed!
INFO noise-c@0.1.6 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/libsodium @ 1.10018.4
INFO Installing esphome/libsodium @ 1.10018.4
Unpacking  [####################################]  100%
Library Manager: libsodium@1.10018.4 has been installed!
INFO libsodium@1.10018.4 has been installed!
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.50105.0 (5.1.5) 
 - tool-cmake @ 3.21.3 
 - tool-esptoolpy @ 4.8.1 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.10.2 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 12.2.0+20230208
Creating a new virtual environment for IDF Python dependencies
Installing ESP-IDF's Python dependencies
Collecting wheel>=0.35.1
  Downloading wheel-0.45.1-py3-none-any.whl (72 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 1.1 MB/s eta 0:00:00
Collecting urllib3<2
  Downloading urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.2/144.2 kB 3.5 MB/s eta 0:00:00
Collecting cryptography~=41.0.1
  Downloading cryptography-41.0.7-cp37-abi3-manylinux_2_28_aarch64.whl (4.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 19.8 MB/s eta 0:00:00
Collecting future>=0.18.3
  Downloading future-1.0.0-py3-none-any.whl (491 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.3/491.3 kB 18.5 MB/s eta 0:00:00
Collecting pyparsing<4,>=3.1.0
  Downloading pyparsing-3.2.1-py3-none-any.whl (107 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.7/107.7 kB 11.6 MB/s eta 0:00:00
Collecting kconfiglib~=14.1.0
  Downloading kconfiglib-14.1.0-py2.py3-none-any.whl (145 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.9/145.9 kB 13.4 MB/s eta 0:00:00
Collecting idf-component-manager~=2.0.1
  Downloading idf_component_manager-2.0.4-py3-none-any.whl (151 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.3/151.3 kB 14.9 MB/s eta 0:00:00
Collecting esp-idf-kconfig<2.0.0,>=1.4.2
  Downloading esp_idf_kconfig-1.5.0-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.9/44.9 kB 9.7 MB/s eta 0:00:00
Collecting cffi>=1.12
  Downloading cffi-1.17.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (469 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.2/469.2 kB 22.7 MB/s eta 0:00:00
Collecting click
  Downloading click-8.1.8-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 kB 8.9 MB/s eta 0:00:00
Collecting colorama
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting pyyaml
  Downloading PyYAML-6.0.2-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (736 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 736.8/736.8 kB 22.8 MB/s eta 0:00:00
Collecting requests
  Downloading requests-2.32.3-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 12.3 MB/s eta 0:00:00
Collecting requests-file
  Downloading requests_file-2.1.0-py2.py3-none-any.whl (4.2 kB)
Collecting requests-toolbelt
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 23.8 MB/s eta 0:00:00
Collecting tqdm
  Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 12.5 MB/s eta 0:00:00
Collecting jsonref
  Downloading jsonref-1.1.0-py3-none-any.whl (9.4 kB)
Collecting pydantic
  Downloading pydantic-2.10.6-py3-none-any.whl (431 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 431.7/431.7 kB 19.9 MB/s eta 0:00:00
Collecting pydantic-core
  Downloading pydantic_core-2.31.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 24.3 MB/s eta 0:00:00
Collecting pydantic-settings
  Downloading pydantic_settings-2.8.1-py3-none-any.whl (30 kB)
Collecting typing-extensions
  Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting pycparser
  Downloading pycparser-2.22-py3-none-any.whl (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.6/117.6 kB 13.3 MB/s eta 0:00:00
Collecting annotated-types>=0.6.0
  Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Collecting pydantic-core
  Downloading pydantic_core-2.27.2-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 23.9 MB/s eta 0:00:00
Collecting python-dotenv>=0.21.0
  Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.4.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (139 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.5/139.5 kB 16.4 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.10-py3-none-any.whl (70 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 16.8 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2025.1.31-py3-none-any.whl (166 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.4/166.4 kB 16.2 MB/s eta 0:00:00
Installing collected packages: wheel, urllib3, typing-extensions, tqdm, pyyaml, python-dotenv, pyparsing, pycparser, kconfiglib, jsonref, idna, future, colorama, click, charset-normalizer, certifi, annotated-types, requests, pydantic-core, esp-idf-kconfig, cffi, requests-toolbelt, requests-file, pydantic, cryptography, pydantic-settings, idf-component-manager
Successfully installed annotated-types-0.7.0 certifi-2025.1.31 cffi-1.17.1 charset-normalizer-3.4.1 click-8.1.8 colorama-0.4.6 cryptography-41.0.7 esp-idf-kconfig-1.5.0 future-1.0.0 idf-component-manager-2.0.4 idna-3.10 jsonref-1.1.0 kconfiglib-14.1.0 pycparser-2.22 pydantic-2.10.6 pydantic-core-2.27.2 pydantic-settings-2.8.1 pyparsing-3.2.1 python-dotenv-1.0.1 pyyaml-6.0.2 requests-2.32.3 requests-file-2.1.0 requests-toolbelt-1.0.0 tqdm-4.67.1 typing-extensions-4.12.2 urllib3-1.26.20 wheel-0.45.1
Reading CMake configuration...
Generating assembly for certificate bundle...
Dependency Graph
|-- noise-c @ 0.1.6
Compiling .pioenvs/esphome-web-1f3948/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/esphome-web-1f3948/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/esphome-web-1f3948/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/esphome-web-1f3948/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/esphome-web-1f3948/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/esphome-web-1f3948/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/esphome-web-1f3948/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/esphome-web-1f3948/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/esphome-web-1f3948/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/esphome-web-1f3948/src/esphome/components/binary_sensor/automation.cpp.o
Compiling .pioenvs/esphome-web-1f3948/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling .pioenvs/esphome-web-1f3948/src/esphome/components/binary_sensor/filter.cpp.o
Compiling .pioenvs/esphome-web-1f3948/src/esphome/components/climate/climate.cpp.o
Compiling .pioenvs/esphome-web-1f3948/src/esphome/components/climate/climate_mode.cpp.o
Compiling .pioenvs/esphome-web-1f3948/src/esphome/components/climate/climate_traits.cpp.o
Compiling .pioenvs/esphome-web-1f3948/src/esphome/components/cn105/climateControls.cpp.o
In file included from src/esphome.h:35,
                 from src/esphome/components/cn105/Globals.h:2,
                 from src/esphome/components/cn105/cn105.h:2,
                 from src/esphome/components/cn105/climateControls.cpp:1:
src/esphome/components/cn105/uptime_connection_sensor.h:2:10: fatal error: esphome/components/uptime/sensor/uptime_seconds_sensor.h: No such file or directory
    2 | #include <esphome/components/uptime/sensor/uptime_seconds_sensor.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/esphome-web-1f3948/src/esphome/components/cn105/climateControls.cpp.o] Error 1
========================= [FAILED] Took 282.34 seconds =========================
`
```

And here's the YAML file I'm using:

```
esphome:
  name: esphome-web-1f3948
  friendly_name: Dining Room Heat Pump
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf   

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO20
  rx_pin: GPIO21

# External component reference
external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

# Climate entity configuration
climate:
  - platform: cn105
    id: hp
    name: "Dining Room Heat Pump"
    icon: mdi:heat-pump
    visual:
      min_temperature: 15
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.5
    # Timeout and communication settings
    remote_temperature_timeout: 30min
    update_interval: 4s
    debounce_delay : 100ms
    # Various optional sensors, not all sensors are supported by all heatpumps
    compressor_frequency_sensor:
      name: Compressor Frequency
      entity_category: diagnostic
      disabled_by_default: false
    outside_air_temperature_sensor:
      name: Outside Air Temp
      disabled_by_default: false
    vertical_vane_select:
      name: Vertical Vane
      disabled_by_default: false
    horizontal_vane_select:
      name: Horizontal Vane
      disabled_by_default: false
    isee_sensor:
      name: ISEE Sensor
      disabled_by_default: false
    stage_sensor:
      name: Stage
      entity_category: diagnostic
      disabled_by_default: false
    sub_mode_sensor:
      name: Sub Mode
      entity_category: diagnostic
      disabled_by_default: false
    auto_sub_mode_sensor:
      name: Auto Sub Mode
      entity_category: diagnostic
      disabled_by_default: false
    input_power_sensor:
      name: Input Power
      disabled_by_default: false
    kwh_sensor:
      name: Energy Usage
      disabled_by_default: false
    runtime_hours_sensor:
      name: Runtime Hours
      entity_category: diagnostic
      disabled_by_default: false
# Default logging level
logger:
  hardware_uart: UART1 # Uncomment on ESP8266 devices
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "[key here]"

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: [ssid here]
  password: [password here]
```

**Comment by phidauex** [comment]
Try adding the uptime sensor to your yaml (below). Something changed in 2025.2.0 that prevents the uptime sensor class from loading unless the sensor is explicitly added to the YAML. I know Eric is already investigating.

```yaml
sensor:
  # Uptime sensor.
  - platform: uptime
    name: ${name} Uptime
```

Add this to your configuration, clean the build files, then try building again.
