### ISSUE TITLE
hvac_action or state always shows idle

### ISSUE THREAD

**Issue by fwump38** [echavet/MitsubishiCN105ESPHome#277]
I have this installed on an ATOM S3 Lite roughly following the steps from [here](https://github.com/echavet/MitsubishiCN105ESPHome/discussions/83)

My indoor unit is a ducted air handler: [PVFY-P36NAMU-E1](https://www.mylinkdrive.com/usa/S_Series/R410A_Systems-4/Indoor_Equipment-8/Multi_Position_Air_Handler-5/PVFY_P36NAMU_E1?product&categoryName=Multi_Position_Air_Handler-5) with Outdoor unit: [MXZ-SM36NAMHZ](https://www.mylinkdrive.com/USA/M_Series/R410A_Systems-3/Outdoor_Equipment/R410A_Outdoor/MXZ_SM36NAMHZ2_U1?product&categoryName=R410A_Outdoor) And my working YAML Config: https://gist.github.com/fwump38/25a954c2ae600c36d2982f0e7e30da91

I have the device connected to Home Assistant as well.

I'm experiencing something similar to #9  where the state according to ESP Home (as well as the `hvac_action` attribute in the `climate.heat_pump` entity in Home Assistant always shows as Idle regardless of what stage, sub mode, or auto sub mode the unit is in. I don't get any other info besides those sensors (ie: compressor frequency, power usage etc).

Since most folks using this appear to have mini splits I suspect my ducted unit reports things a little differently. I assume the same logic that was updated in #9 needs to account for my unit but I don't know C++ well enough (or at all) to know how to make a PR to fix that.

**Comment by fwump38** [comment]
FWIW I figured out that my system does not send anything back from `0x06` response to get status (ie: operating status, input power, energy usage, etc)

I ended up making a fork where I hacked together a way to set operating status based on `stage != IDLE` and hvac_action is now reporting correctly.

**Comment by phidauex** [comment]
@fwump38 - Have you had a chance to try the new build? There is a new option to `stage_sensor` allowing you to use it as a fallback for determining operating mode for units that don't report it the "normal" way:

```yaml
stage_sensor:
      name: stage sensor
      use_as_operating_fallback: true
```

**Comment by fwump38** [comment]
Hi - I just tried it. I saw the new option but wasn't sure where to put it. ESPHome Builder doesn't seem to like that config:

```
climate.cn105: [source /config/esphome/heat-pump.yaml:261]
  platform: cn105
  id: hp
  name: Heat Pump
  icon: mdi:heat-pump
  visual: 
    min_temperature: 17
    max_temperature: 31
    temperature_step: 
      target_temperature: 1
      current_temperature: 0.1
  remote_temperature_timeout: 15min
  update_interval: 3500ms
  debounce_delay: 100ms
  stage_sensor: 
    name: Stage
    entity_category: diagnostic
    disabled_by_default: True
    
    [use_as_operating_fallback] is an invalid option for [stage_sensor]. Please check the indentation.
    use_as_operating_fallback: True
```

Should it be somewhere else?

**Comment by phidauex** [comment]
Hmm, you might try specifying refresh: 0s on the external component to make sure it is grabbing the latest copy (otherwise it uses a cached version for some period of time). Otherwise yes, `use_as_operating_fallback` should be under stage_sensor. My configs are validating correctly with the new sensor value (though I haven't tried it in "true" since my units don't have the operating mode issue).

```yaml
external_components:
- source:
    url: https://github.com/echavet/MitsubishiCN105ESPHome.git
    type: git
  refresh: 0s
```
