### ISSUE TITLE
ESP32-S3 Not Connecting

### ISSUE THREAD

**Issue by rwarner** [echavet/MitsubishiCN105ESPHome#281]
I setup an ESP-32 S3 (WROOM-1) and tried following everything but in the logs on boot it says:

> [I][CN105:028]: tx_pin: -1 rx_pin: -1

which shows it's not utilizing the correct TX/RX pins.

This is what I have in my yaml:

```
esphome:
  name: family-room-mitsubishi

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf   

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO17
  rx_pin: GPIO18

# Default logging level
logger:
  level: INFO

# Enable Home Assistant API
api:
  password: ""    

# External component reference
external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

sensor:
  - platform: uptime
    name: Uptime
    internal: true

# Climate entity configuration
climate:
  - platform: cn105
    id: hp
    name: "Family Room Mitsubishi"
    icon: mdi:heat-pump
    visual:
      min_temperature: 10 # Adjust to your unit's min temp. SmartSet units can go to 10C for heating
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.5
    # Timeout and communication settings
    remote_temperature_timeout: 30min
    update_interval: 2s
    debounce_delay : 100ms
```

No idea what I could be missing. Using command line `esphome` to upload

**Comment by rwarner** [comment]
Changed the title to reflect why I'll keep this open for now. I did end up getting it working. I had to swap the tx/rx pins. I thought we had to match tx/rx to tx/rx on the mitsubishi CN port. However, you have to connect

ESP32 RX -> Mitsubishi TX
ESP32 TX -> Mitsubishi RX

Once I swapped them it worked:

```
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf  


uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO18
  rx_pin: GPIO17

```

Not sure if the tx_pin / rx_pin is worth investigating.
