### ISSUE TITLE
Esp32 v4 32 U  + HomeAsisstantGreen + mitsubishi mod pead rp60  does not work..

### ISSUE THREAD

**Issue by gardelf** [echavet/MitsubishiCN105ESPHome#285]
Hello everybody

I can not get that my mitsubishi pead rp60 works with esp32 using this code, place on Home  Assistant green, 

This is the log from esp32 when I run it

INFO ESPHome 2025.4.1
INFO Reading configuration /config/esphome/aire-mybalancepilates.yaml...
INFO Starting log output from 192.168.1.101 using esphome API
INFO Successfully connected to aire-mybalancepilates @ 192.168.1.101 in 0.094s
INFO Successful handshake with aire-mybalancepilates @ 192.168.1.101 in 0.096s
[21:14:23][I][EVT_SETS:013]: checkPendingWantedSettings - wanted settings have changed, sending them to the heatpump...
[21:14:23][I][app:100]: ESPHome version 2025.4.1 compiled on May 14 2025, 12:42:01
[21:14:23][I][EVT_SETS:013]: checkPendingWantedSettings - wanted settings have changed, sending them to the heatpump...
.................................

[21:14:24][W][CN105:176]: Heatpump has not replied for 139 s
[21:14:24][I][CN105:177]: We think Heatpump is not connected anymore..
[21:14:24][I][CN105:010]: setupUART() with baudrate  2400 

And this is the code install in esp32

```yaml
esphome:
  name: aire-mybalancepilates
  friendly_name: Aire Mybalancepilates

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
   baud_rate: 0
#  hardware_uart: UART1 # Uncomment on ESP8266 devices
  level: INFO
  logs:
    EVT_SETS : INFO
    WIFI : INFO
    MQTT : INFO
    WRITE_SETTINGS : INFO
    SETTINGS : INFO
    STATUS : INFO
    CN105Climate: WARN
    CN105: INFO
    climate: WARN
    sensor: WARN
    chkSum : INFO
    WRITE : WARN
    READ : WARN
    Header: INFO
    Decoder : INFO
    CONTROL_WANTED_SETTINGS: INFO
# Swap the above settings with these debug settings for development or troubleshooting
#  level: DEBUG
#  logs:
#    EVT_SETS : DEBUG
#    WIFI : INFO
#    MQTT : INFO
#    WRITE_SETTINGS : DEBUG
#    SETTINGS : DEBUG
#    STATUS : INFO
#    CN105Climate: WARN
#    CN105: DEBUG
#    climate: WARN
#    sensor: WARN
#    chkSum : INFO
#    WRITE : WARN
#    READ : WARN
#    Header: INFO
#    Decoder : DEBUG
#    CONTROL_WANTED_SETTINGS: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "W/VLYO0jxGkWSUqvd4NfVcD2oCqqukGgnNDqVBHHbzA="

ota:
  - platform: esphome
    password: "18102cdba1aa5e92b6111de2d9fe1be9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aire-Mybalancepilates"
    password: "aDcCRtRC3rYP"

captive_portal:




uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO1
  rx_pin: GPIO3


# External component reference
external_components:
  - source: github://echavet/MitsubishiCN105ESPHome


climate:
  - platform: cn105
    id: hp
    name: "${friendly_name}"
    icon: mdi:heat-pump
    visual:
      min_temperature: 10 # Adjust to your unit's min temp. SmartSet units can go to 10C for heating
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.5
    # Timeout and communication settings
    remote_temperature_timeout: 30min
    update_interval: 2s
    debounce_delay : 100ms
    # Various optional sensors, not all sensors are supported by all heatpumps
    compressor_frequency_sensor:
      name: Compressor Frequency
      entity_category: diagnostic
      disabled_by_default: true
    outside_air_temperature_sensor:
      name: Outside Air Temp
      disabled_by_default: true
    vertical_vane_select:
      name: Vertical Vane
      disabled_by_default: false
    horizontal_vane_select:
      name: Horizontal Vane
      disabled_by_default: true
    isee_sensor:
      name: ISEE Sensor
      disabled_by_default: true
    stage_sensor:
      name: Stage
      entity_category: diagnostic
      disabled_by_default: true
    sub_mode_sensor:
      name: Sub Mode
      entity_category: diagnostic
      disabled_by_default: true
    auto_sub_mode_sensor:
      name: Auto Sub Mode
      entity_category: diagnostic
      disabled_by_default: true
    input_power_sensor:
      name: Input Power
      disabled_by_default: true
    kwh_sensor:
      name: Energy Usage
      disabled_by_default: true
    runtime_hours_sensor:
      name: Runtime Hours
      entity_category: diagnostic
      disabled_by_default: true
  
sensor:
  - platform: uptime
    name: Uptime
```
