### ISSUE TITLE
MSZ-FH18NA2 stuck expecting external temperature assignment

### ISSUE THREAD

**Issue by elreydetodo** [echavet/MitsubishiCN105ESPHome#288]
Last month I installed an m5stack Atom S3 Lite to control two of my heat pumps at home. One of them (an MLZ-KP18NA) is working fine. The other (an MSZ-FH18NA2) is not reporting the correct room temperature. I started to get suspicious after a couple weeks when the sensor always seemed to say it was 73.5 F every time I checked it. Some of the days that just seemed infeasible, but I initially didn't think much of it. Today I looked back at the sensor logs, and it has _never_ changed value from there.

I think the unit got into this state because prior to removing my [Kumo Cloud wifi adapter](https://www.acwholesalers.com/Mitsubishi-PAC-USWHS002-WF-2/p102719.html), there was a [Mitsubishi external temperature and humidity sensor](https://www.acwholesalers.com/Mitsubishi-HVAC-PAC-USWHS003-TH-1/p81573.html) providing temperature and humidity details to the unit. I suspect that device was reporting through the Kumo wifi adapter, and that the unit was put into some state to expect only readings from this thing.

To test this out, I have manually set the temperature to 40 C via service call. The heat pump is echoing that back to me in the room temperature, and it doesn't give the value up even after rebooting. I went to the trouble of capturing room temperature packets, and here's what I've got:
```
[20:29:45][D][READ:172]: FC 62 01 30 10 03 00 00 1C 00 A2 D0 D0 FE 00 00 00 00 00 00 00 FE 
```

The value D0 in array position 6 is the temperature. (0xD0 - 0x80) / 2 = 40 C. The thing is telling me the room temperature is exactly what I told it the room temperature was. I guess that's probably expected, but it's not what I want right now. I want the actual temperature sensor in the unit to work.

I attached an m5stack ENV-IV sensor to the controller and I know for sure the _actual_ temperature in the area is 22.15 C right now. I'll be able to tell easily if the thing starts working correctly at some point. I can even temporarily rig that sensor to act as an external temperature sensor, but I don't want to leave it there long term because the rig I'd don't is... let's just say not stable.

Is there a magic incantation I can give my unit to make it resume taking the temperature from the internal temperature sensor?

**Comment by echavet** [comment]
yes, I think you can simply call the use_internal_temperature lambda function or directly id(clim_seb).set_remote_temperature(0) like it is done in the sample yaml configuration files:

```yaml
api:
  services:
    - service: reboot
      then:
        - logger.log: "Redémarrage en cours..."
        - lambda: |-
            ESP.restart();
    - service: set_remote_temperature
      variables:
        temperature: float
      then:
        - lambda: 'id(clim_seb).set_remote_temperature(temperature);'

    - service: use_internal_temperature
      then:
        - lambda: 'id(clim_seb).set_remote_temperature(0);'
```

Havin this in your configuration has the effect to make the API function `set_remote_temperature`available from homeassistant. So you can use an automation or use the "Action" feature from the home assistant Development Tools to call function directly:

```yaml
action: esphome.atom_s3_use_internal_temperature
data: {}
```
