### ISSUE TITLE
Installed and connected but only one entity in Homeassistant

### ISSUE THREAD

**Issue by lockeandev** [echavet/MitsubishiCN105ESPHome#297]
I'm using a waveshare esp32-s3-zero, I've got it flashed and TX from the CN105 is connected to RX on the ESP32 (and vice versa for RX on the CN105).  the esp boots and I can get logs wirelessly, but I only get a firmware entity in Home assistant. I also don't get the web portal.

Here is the verification I'm able to connect via esphome in HASS.

![Image](https://github.com/user-attachments/assets/15e6f60e-b3c7-4537-bd8d-c58ca8a6bfc9)

here is my yaml

```
esphome:
  name: mini-split
  friendly_name: Mini Split

substitutions:
  name: mini-split # Do not use underscores, which are not fully compatible with mDNS
  friendly_name: Mini Split

# For ESP32 Devices
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf 

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO17
  rx_pin: GPIO16

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome
#    refresh: 0s

captive_portal:

# Enable logging
logger:
#  hardware_uart: UART1 # Uncomment on ESP8266 devices
  level: INFO
  logs:
    EVT_SETS : INFO
    WIFI : INFO
    MQTT : INFO
    WRITE_SETTINGS : INFO
    SETTINGS : INFO
    STATUS : INFO
    CN105Climate: WARN
    CN105: INFO
    climate: WARN
    sensor: WARN
    chkSum : INFO
    WRITE : WARN
    READ : WARN
    Header: INFO
    Decoder : INFO
    CONTROL_WANTED_SETTINGS: INFO
#  level: DEBUG
#  logs:
#    EVT_SETS : DEBUG
#    WIFI : INFO
#    MQTT : INFO
#    WRITE_SETTINGS : DEBUG
#    SETTINGS : DEBUG
#    STATUS : INFO
#    CN105Climate: WARN
#    CN105: DEBUG
#    climate: WARN
#    sensor: WARN
#    chkSum : INFO
#    WRITE : WARN
#    READ : WARN
#    Header: INFO
#    Decoder : DEBUG
#    CONTROL_WANTED_SETTINGS: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "redacted"

ota:
  - platform: esphome
    password: "redacted"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mini-Split Fallback Hotspot"
    password: "redacted"


sensor:
  #- platform: homeassistant
  #  name: "Remote Temperature Sensor"
  #  entity_id: ${remote_temp_sensor} # Replace with your HomeAssistant remote sensor entity id, or include in substitutions
  #  internal: false
  #  disabled_by_default: true
  #  device_class: temperature
  #  state_class: measurement
  #  unit_of_measurement: "°C"
  #  filters:
  #  # Uncomment the lambda line to convert F to C on incoming temperature
  #  #  - lambda: return (x - 32) * (5.0/9.0);
  #    - clamp: # Limits values to range accepted by Mitsubishi units
  #        min_value: 1
  #        max_value: 40
  #        ignore_out_of_range: true
  #    - throttle: 30s
  #  on_value:
  #    then:
  #      - logger.log:
  #          level: INFO
  #          format: "Remote temperature received from HA: %.1f C"
  #          args: [ 'x' ]
  #      - lambda: 'id(hp).set_remote_temperature(x);'
#
  # Uptime sensor.
  - platform: uptime
    name: Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 120s

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: IP
    ssid:
      name: SSID
    bssid:
      name: BSSID



# Create a button to restart the unit from HomeAssistant. Rarely needed, but can be handy.
button:
  - platform: restart
    name: "Restart ${friendly_name}"

# Creates the sensor used to receive the remote temperature from Home Assistant
# Uses sensor selected in substitutions area at top of config
# Customize the filters to your application:
#   Uncomment the first line to convert F to C when remote temps are sent
#   If you have a fast or noisy sensor, consider some of the other filter
#   options such as throttle_average.
climate:
  - platform: cn105
    id: hp
    name: "${friendly_name}"
    icon: mdi:heat-pump
    visual:
      min_temperature: 10 # Adjust to your unit's min temp. SmartSet units can go to 10C for heating
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.5
    # Timeout and communication settings
    remote_temperature_timeout: 30min
    update_interval: 2s
    debounce_delay : 100ms
    # Various optional sensors, not all sensors are supported by all heatpumps
    compressor_frequency_sensor:
      name: Compressor Frequency
      entity_category: diagnostic
      disabled_by_default: true
    outside_air_temperature_sensor:
      name: Outside Air Temp
      disabled_by_default: true
    vertical_vane_select:
      name: Vertical Vane
      disabled_by_default: false
    #horizontal_vane_select:
    #  name: Horizontal Vane
    #  disabled_by_default: true
    #isee_sensor:
    #  name: ISEE Sensor
    #  disabled_by_default: true
    stage_sensor:
      name: Stage
      entity_category: diagnostic
      disabled_by_default: true
    sub_mode_sensor:
      name: Sub Mode
      entity_category: diagnostic
      disabled_by_default: true
    auto_sub_mode_sensor:
      name: Auto Sub Mode
      entity_category: diagnostic
      disabled_by_default: true
    input_power_sensor:
      name: Input Power
      disabled_by_default: true
    kwh_sensor:
      name: Energy Usage
      disabled_by_default: true
    runtime_hours_sensor:
      name: Runtime Hours
      entity_category: diagnostic
      disabled_by_default: true
```
