### ISSUE TITLE
Support ESP-IDF

### ISSUE THREAD

**Issue by Bascht74** [echavet/MitsubishiCN105ESPHome#6]
If you are using an ESP32 and you are using bluetooth with it (like I do for the external temperature updates), it is all written over the place that you have to / really should use the ESP-IDF instead of the arduino IDF.

The used api supports that already:
https://github.com/SwiCago/HeatPump/commit/3085196a4f06708b14dc090cc42a617704d0247e

@SwiCago said the following about that...

> ...ESP32 (is) faster, we can lower delay.
> Use UART custom define pin when retry.

Could you support the ESP-IDF with your component as well?
That way the bluetooth part would work more stable and lower delays/quicker response might be possible...

**Comment by echavet** [comment]
Hello [Bascht74](https://github.com/Bascht74) and thanks for your message,
I think I'm gonna need time or help, or both to implement this because I'm not familiar with this architecture. I've just tested to compile a yaml with my sources and the framework set to:
```
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf 
```
if fails with:

> src/esphome/components/cn105/cn105.h:109:5: error: 'HardwareSerial' does not name a type

Perhaps it can be done just by using an alternative to HardwareSerial just for the ESP32. 
I will have a look soon. But if you have advice, you're welcome.

**Comment by Bascht74** [comment]
I am not a programmer, but I will look into it...

**Comment by Bascht74** [comment]
What I found so far:

Switching from your custom UART-Code to the ESPHome one could be the best way to get it all. Maybe it is not so difficult (I cannot assess), because the ESPHome guys wrote
`If you want to integrate a device into ESPHome that uses this (UART) protocol you can pretty much use almost all Arduino-based code because ESPHome has a nice abstraction over the UART bus.`
see: https://esphome.io/custom/uart.html
and: https://esphome.io/components/uart
example: https://github.com/martin3000/ESPhome/blob/master/vaillantx6.h

that way it would be possible to use ESP32 (Arduino/ESP-IDF)/ESP8266(Ardunino), and ESPHome would do the "magic": 
```
uart:
  tx_pin: xx
  rx_pin: xx
  baud_rate: 4800
```

more available functions:
```
// Set TX/RX pins
id(my_uart).set_tx_pin(InternalGPIOPin *tx_pin);
id(my_uart).set_rx_pin(InternalGPIOPin *rx_pin);
// RX buffer size
id(my_uart).set_rx_buffer_size(size_t rx_buffer_size);
// Stop bits
id(my_uart).set_stop_bits(uint8_t stop_bits);
// Data bits
id(my_uart).set_data_bits(uint8_t data_bits);
// Parity
id(my_uart).set_parity(UARTParityOptions parity);
// Baud rate
id(my_uart).set_baud_rate(uint32_t baud_rate);
// Baud rate
id(my_uart).get_baud_rate();
```

**Comment by echavet** [comment]
Hi Bascht74,

thanks for your message.
I did what you've asked in a different branch for the moment.

I have changed the way to configure the UART for both frameworks to work. I have tested quickly on my esp8266 with the arduino framework. And I have compiled but not tested a version  with esp-idf  framework.

Could you test with this branch (uart_config_change) ?


You have to change the source in external_components this way:

```
external_components:
  - source: github://echavet/MitsubishiCN105ESPHome@uart_config_change
    refresh: 0s

```


And you now have to add something like this :

```
uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: 1
  rx_pin: 3
```



Here is an complete yaml example:

```
substitutions:
  name: "hpsejour"
  friendly_name: Climatisation Séjour

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf     
    #type: arduino


uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: 0
  rx_pin: 3
  

# Enable logging
logger:  
  hardware_uart: UART0
  level: INFO
  logs:
    CN105Climate: WARN
    CN105: WARN
    climate: WARN
    sensor: WARN
    chkSum : INFO
    WRITE : WARN
    READ : WARN
    Header: INFO
    Decoder : WARN
    

# Enable Home Assistant API
api:
  services:    
    - service: set_remote_temperature
      variables:
        temperature: float
      then:
        - lambda: 'id(clim_sejour).set_remote_temperature(temperature);'

    - service: use_internal_temperature
      then:
        - lambda: 'id(clim_sejour).set_remote_temperature(0);'
  encryption:
    key: !secret encryption_key

ota:  
  password: !secret ota_pwd

wifi:
 
  networks:
  - ssid : !secret wifi_ssid3
    password: !secret wifi_password3
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heatpump-Sejour Fallback Hotspot"
    password: !secret ota_pwd

captive_portal:

  
time:
  - platform: homeassistant
    id: homeassistant_time

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome@uart_config_change
    refresh: 0s


# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ${name} ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${name} IP
    ssid:
      name: ${name} SSID
    bssid:
      name: ${name} BSSID

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: ${name} Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${name} WiFi Signal
    update_interval: 60s

# Configuration pour l'objet 'climate'
climate:
  - platform: cn105  
    name: ${friendly_name}
    id: "clim_sejour"    
    update_interval: 10s         
```
