### ISSUE TITLE
How to use the vane feature

### ISSUE THREAD

**Issue by Bascht74** [echavet/MitsubishiCN105ESPHome#7]
Hi, 

I was using settings for the horizontal and vertical vane with the old component

```
#    horizontal_vane_select:
#      name: Horizontale Luftstromrichtung
#    vertical_vane_select:
#      name: Verticale Luftstromrichtung

```

You wrote that this is available with your component, too: 

> Additional components: vane orientation (fully supporting the Swicago map), compressor frequency for energy monitoring, and i-see sensor.

But how?

I don't find any hint/documentation/example about it!
Maybe I am blind, could you send me to the right place?

Sebastian

**Comment by Bascht74** [comment]
I fould information about differencing both verical / horizontal vanes and naming them in the yaml here:
https://github.com/wrouesnel/esphome-mitsubishiheatpump/commit/db95f70e16f6fab3bdb6a01aae4a27b54f5755f0

**Comment by echavet** [comment]
Hello,
For the moment there is an extreComponent feature that builds a select named "Van orientation" associated with the climate component. It is filled with options from the VAN_MAP from the SwiCago lib.
It's a good idea to offer a way to customize the name. 
But for now it can be done (override name) in Home Assistant.
I will provide this option asap.

**Comment by Bascht74** [comment]
Thx for your answer.

I have this option: 
<img width="323" alt="image" src="https://github.com/echavet/MitsubishiCN105ESPHome/assets/66269310/2c3a3dd2-27d4-405f-a521-33f020ff82ac">

But... is it for the vertical or horizonatal vane?
I have both:
<img width="673" alt="image" src="https://github.com/echavet/MitsubishiCN105ESPHome/assets/66269310/0d557450-e272-46f7-a0b9-20f0e558ea86">

in the SwiCago lib:
```
heatpumpSettings settings = {
    "ON",  /* ON/OFF */
    "FAN", /* HEAT/COOL/FAN/DRY/AUTO */
    26,    /* Between 16 and 31 */
    "4",   /* Fan speed: 1-4, AUTO, or QUIET */
    "3",   /* Air direction (vertical): 1-5, SWING, or AUTO */
    "|"    /* Air direction (horizontal): <<, <, |, >, >>, <>, or SWING */
};

bool operator==(const heatpumpSettings& lhs, const heatpumpSettings& rhs) {
  return lhs.power == rhs.power && 
         lhs.mode == rhs.mode && 
         lhs.temperature == rhs.temperature && 
         lhs.fan == rhs.fan &&
         lhs.vane == rhs.vane &&
         lhs.wideVane == rhs.wideVane &&
         lhs.iSee == rhs.iSee; 
}
```
So the "wideVane" (= horizontal) is missing, right now only the vertical is available within your component. 
The question is, if you could provide the horizontal as well as a select entity...

**Comment by echavet** [comment]
It's for the vertical.
Horizontal is not supported yet because I have no module to test it.
But I will implement it asap

**Comment by Bascht74** [comment]
Thx, I will test it then :-)
I have two different models that support it...

**Comment by echavet** [comment]
The [new branch ](https://github.com/echavet/MitsubishiCN105ESPHome/tree/extra_components) is a work in progress to implement [wrouesnel](https://github.com/wrouesnel) extra select options for vertical and horizontal vane. 
I'm currently testing the component stability before merging. it looks good for the moment.

**Comment by echavet** [comment]
```yaml
climate:
  - platform: cn105  
    name: ${friendly_name}
    compressor_frequency_sensor:
      name: Compressor frequency (clim Sejour)    
    vertical_vane_select:
      name: Orientation de la Vane Verticale
    horizontal_vane_select:
      name: Orientation de la Vane Horizontale
    remote_temperature_timeout: 30min
    update_interval: 10s   
```
