### ISSUE TITLE
Processing timeouts for the external temperature feature

### ISSUE THREAD

**Issue by Bascht74** [echavet/MitsubishiCN105ESPHome#8]
Hi, sorry to disturb you again.

One last thing: 
As you now, I am using the external temp. sesors (I thing like you do). 
In the old integration there were some options about a fallback to the internal sensors:

```
#    remote_temperature_operating_timeout_minutes: 5 # The number of minutes before a set_remote_temperature request becomes stale, while the heatpump is heating or cooling. Unless a new set_remote_temperature request was made within the time duration, the heatpump will revert back to it's internal temperature sensor.
#    remote_temperature_idle_timeout_minutes: 20 # The number of minutes before a set_remote_temperature request becomes stale while the heatpump is idle. Unless a new set_remote_temperature request is made within the time duration, the heatpump will revert back to it's internal temperature sensor.
    # remote_temperature_ping_timeout_minutes: 5 # The number of minutes before a set_remote_temperature request becomes stale, if a ping request wasn't received from your ESPHome controller. This will result in the heatpump reverting to it's internal temperature sensor if the heatpump loses it's WiFi connection.
```

I thought this is very usefull if HA become unavailable or the battery for the bluetooth temp sensor dies. 
How is the fallback implemented within your component? Is there a strategy or anything by default?
I don't want to heat up the room becaus the external temp doesn't get updated...

Sebastian

**Comment by echavet** [comment]
Yes I agree. I saw this is a great idea. I will implement this soon.
Thanks for you message

**Comment by echavet** [comment]
done with only one option: remote_temperature_timeout
because I didn't see the point of having 3 timeout??
          

```
climate:
  - platform: cn105  
    name: ${friendly_name}
    id: "esp32_clim"
    compressor_frequency_sensor:
      name: Compressor frequency (clim Sejour)    
    vertical_vane_select:
      name: Orientation de la Vane Verticale
    horizontal_vane_select:
      name: Orientation de la Vane Horizontale
    remote_temperature_timeout: 30min
    update_interval: 10s   
```
