### ISSUE TITLE
Cannot connect to heatpump - tested with D1 mini, 

### ISSUE THREAD

**Issue by HansVanEylen** [echavet/MitsubishiCN105ESPHome#85]
I've been trying to connect to my MSZ-AP25VGK (wall unit with built-in WiFi) using 

- a D1 mini (https://www.amazon.com.be/-/nl/dp/B0CJJ8L1DG?psc=1&ref=ppx_yo2ov_dt_b_product_details)
- an ESP32 ([MH-ET Live ESP32 Development Board WiFi+Bluetooth Ultra-Low Power Consumption Dual Core ESP-32 ESP-32S ESP 32])
- an Atom Echo (ESP32-Pico) I had lying around

The D1 mini was setup correctly in ESPHome (2024.4.2) but the logs showed

[E][CN105:032]: --> Heatpump did not reply: NOT CONNECTED <--
[I][CN105:033]: Trying to connect again...
[W][CN105:157]: Heatpump has not replied for 40 s
[I][CN105:158]: We think Heatpump is not connected anymore
[I][CN105:093]: setupUART() with baudrate 2400

Both ESP32 devices gave similar output:

[16:44:29][I][app:100]: ESPHome version 2024.4.2 compiled on May  1 2024, 16:31:16
[16:44:29][E][CN105:317]: sync impossible: heatpump not connected
[16:44:29][E][CN105:317]: sync impossible: heatpump not connected

but when I powered them on, the horizontal vane of the MSZ opened and closed, so there must be something going on. I tried three different baud rates : 2400, 4800 and 9600. All gave the same result.

Config for the D1 mini (I removed the wifi setup and api key info):

```
substitutions:
  name: acbureaud1mini
  friendly_name: AC Bureau D1 mini

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: d1_mini

uart:
  id: HP_UART
  baud_rate: 9600
  tx_pin: 1
  rx_pin: 3

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome
#    refresh: 0s

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

logger:
  hardware_uart: UART1
  level: INFO

# Create a button to restart the unit from HomeAssistant. Rarely needed, but can be handy.
button:
  - platform: restart
    name: "Restart ${friendly_name}"

climate:
  - platform: cn105
    name: "${friendly_name}"
    icon: mdi:heat-pump
    visual:
      min_temperature: 15
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
    compressor_frequency_sensor:
      name: ${name} Compressor Frequency
    vertical_vane_select:
      name: ${name} Vertical Vane
    horizontal_vane_select:
      name: ${name} Horizontal Vane
    remote_temperature_timeout: 30min
    debounce_delay : 500ms
    update_interval: 4s
```

Config for the ESP32 (in this case the Atom):

```
esphome:
  name: acbureau2
  friendly_name: ACBureau2

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf   

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO32
  rx_pin: GPIO26

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome@v1.2.2

captive_portal:

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

climate:
  - platform: cn105
    name: "${friendly_name}"
    icon: mdi:heat-pump
    visual:
      min_temperature: 15
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
    compressor_frequency_sensor:
      name: ${name} Compressor Frequency
    vertical_vane_select:
      name: ${name} Vertical Vane
    horizontal_vane_select:
      name: ${name} Horizontal Vane
    remote_temperature_timeout: 30min
    debounce_delay : 500ms
    update_interval: 4s

logger:
    level: INFO
```

I did read https://github.com/echavet/MitsubishiCN105ESPHome/issues/70, so I will be getting a voltage regulator for the D1 mini, but I thought this wouldn't be necessary for the ESP32 devices?
Is there anything else I'm missing?

thanks,
Hans

**Comment by mfinnz** [comment]
I'm having the same problem still after adding a 3.3V regulator to a D1 mini, as documented in #70 

I'm getting exactly the same result, it is getting no reply from the heatpump. If I use the code from GeoffDavis repository set to 2400 baud I can send commands and the heatpump responds so I know that is the correct baud rate and at least the TX line is working.

**Comment by mfinnz** [comment]
I've just now added 10kOhm resistors as above, between the RX and TX lines to the 5V line, but no change in behaviour. On the D1 Mini I am measuring 3.56v across the RX pin and 3.3V across TX, which seems a little odd. I've triple checked my connections and it all seems correct.

**Comment by echavet** [comment]
> I've just now added 10kOhm resistors as above, between the RX and TX lines to the 5V line, but no change in behaviour. On the D1 Mini I am measuring 3.56v across the RX pin and 3.3V across TX, which seems a little odd. I've triple checked my connections and it all seems correct. I've tried a third D1 Mini, but not luck, so I doubt the devices are faulty. I also gave mitsubishi2mqtt a go, and it can't connect either. So it's not the code, but hoping we can pool info and solve it

Well, if you're sure that:the board connectors (pins) are okay on both sides,your cable is good (you have performed an electrical continuity test),it doesn't work with other controllers (and you have verified you're using the correct Rx and Tx pin numbers),your unit is known to work with any of the Swicago implementations,then I'm afraid you don't have many options left!What happened to me once, when I was using a specific connection scheme with both a heat pump and a Raspberry Pi (for collecting logs) connected to two different UARTs on the controller, was that I couldn't get the controller to read the heat pump responses either. My error was using the Raspberry Pi's ground for the controller instead of the heat pump's ground. It's really important for both sides of the UART to share the same ground. I think the most crucial thing is to ensure a nice and stable ground connection between the two. So, I would try using a pull-down resistor rather than a pull-up. However, I must admit my knowledge of hardware electronics is very limited, so this could also be a terrible piece of advice!

**Comment by echavet** [comment]
I have tested 👍 these setup:
```yaml
esp8266:
  board: d1_mini
uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: 1
  rx_pin: 3
```

**Comment by mfinnz** [comment]
Thanks for your suggestions. I have reversed the connection for the 10kOhm resistors so they connect to the GND as a pull down resistor, but it's still the same. The board I am using is this one [https://www.aliexpress.com/item/1005005121150737.html](url) I have tried 3 of them, so unlikely it's a faulty board.

I may end up just getting ESP32 board as others have had problems with ESP8266, or seeing if I can order the one you use.

I am using this setup:

```
# For ESP8266 Devices
esp8266:
  board: d1_mini

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: 1
  rx_pin: 3
```

Also I use this for the components, I thought that means I am using the latest, v 1.3? If not, do I just download the latest release zip file and how do I install it? I thought it did it at install/build time using the external component, but I'm quite new to this.

```
external_components:
  - source: github://echavet/MitsubishiCN105ESPHome
    refresh: 0s

```
